### ISSUE TITLE
Highlight default values of params

### ISSUE THREAD

**Issue by satazor** [jsdoc2md/jsdoc-to-markdown#10]
```js
/**
 * Do something.
 *
 * @param  {String}   [task=foo]  The task to do
 */
function foo(task) {
}
```

The above example does not highlight the default value of the `task` argument, which would be cool.
Am I missing something or simply there's no highlighting for it?

**Comment by 75lb** [comment]
fixed in @next, looks like [this](https://github.com/75lb/jsdoc-to-markdown/blob/next/example/format-options/md/param-list-format.md)
