### ISSUE TITLE
Any way to create one output file per directory?

### ISSUE THREAD

**Issue by thephilwells** [jsdoc2md/jsdoc-to-markdown#102]
Not a bug, but a request. It'd be nice to be able to generate one `README.md` file per directory, so that when I navigate my project on Github, each folder has its own doc explaining the files that are in there. Similar to the solution here:

https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class

but in a way that concatenates all the doc for files in that folder into one file.

**Comment by 75lb** [comment]
yes, that's perfectly possible using the jsdoc2md API.. i don't really have time to write the script for you right now, but you need to run `render` for each directory in your project..  simplistic example:

```
jsdoc2md.render({ files: 'lib/one/*.js' }).then(output => fs.writeFile('one,md', output))
jsdoc2md.render({ files: 'lib/two/*.js' }).then(output => fs.writeFile('two.md', output))
etc.
```
