### ISSUE TITLE
@external references don't seem to work on @returns

### ISSUE THREAD

**Issue by Anupheaus** [jsdoc2md/jsdoc-to-markdown#104]
So I have the following in my code:
```
/**
 * @extenal Questions
 * @see https://github.com/<removed>/wiki/API-Questions
 */
```
and then I have this on a property (ES6 class):
```
/**
 * Gets all the questions.
 * @readonly
 * @returns {external:Questions}
 */
get questions() { return this._questions; }
```
and the jsdoc2md generates this:
```
### businessModel.questions ⇒ <code>external:Questions</code>
Gets all the questions.
```
Is this a bug or is there another way to do this please?

**Comment by 75lb** [comment]
is `external:Questions` this correct namepath? Is it listed in [--namepaths](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Listing-namepaths) ?

**Comment by Anupheaus** [comment]
I've not done anything with namepaths and the above works with an @extends...why does it work fine there and not on a @returns?

**Comment by 75lb** [comment]
i can't reproduce this, an external works fine in a `@returns`. So, this works as expected: 

```js
/**
 * @returns {external:TestRunner}
 */
function returnsExternal () {}

/**
 * @external TestRunner
 * @see https://github.com/75lb/test-runner
 */
```

Please run `jsdoc2md --namepaths sourcecode.js` to list all valid namepaths in your code (as i advised last time). If your external namepath is in the list, it is valid. 

I also noticed you misspelt "external" in your snippet: 

```js
/**
 * @returns {external:TestRunner}
 */
function returnsExternal () {}
```

**Comment by Anupheaus** [comment]
Sorry this was a spelling mistake on my part - my sincere apologies for any wasted time on your part 😞

**Comment by 75lb** [comment]
ok, no probs
