### ISSUE TITLE
Backticks in place of <code>

### ISSUE THREAD

**Issue by jaydenseric** [jsdoc2md/jsdoc-to-markdown#105]
Could the output markdown not simply [use backticks](https://daringfireball.net/projects/markdown/syntax#code), in place of `<code>` inline HTML?

**Comment by 75lb** [comment]
in some cases, yes.. in other cases, no. The issue is that markdown within markdown is not valid. 

So, this is valid:

```hbs
`something`
```

This is not: 
```hbs
one         | two 
============|==============
`something` | another thing
```
Rather than have complex logic to determine whether we have a valid context to use backticks, we use `<code>` which is valid throughout.

**Comment by jaydenseric** [comment]
Thats not true, [GFM supports markdown in tables](https://help.github.com/articles/organizing-information-with-tables/#formatting-content-within-your-table), which this library supports. They explicitly show an example of backticks in a table cell.

[https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md)
> By default, dmd generates github-flavoured markdown.

**Comment by 75lb** [comment]
Hi, yes you're right - that particular example is valid now (when this tool came out a couple of years old it was not valid). 

If you like, [create one or more custom partials](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial) and experiment with backticks. If everything still works, send me a patch and we'll make it default.
