### ISSUE TITLE
Arguments in shebang lines are not portable

### ISSUE THREAD

**Issue by UlrichEckhardt** [jsdoc2md/jsdoc-to-markdown#106]
In 1.3.8, you changed the shebang line from "#!/usr/bin/env node" to "#!/usr/bin/env node --no-warnings". Under some OSs (e.g. Linux 3.16) this doesn't work as you intended. It causes "/usr/bin/env" to be called with the single argument "node --no-warnings". A program called "node --no-warnings" is nowhere in the path though and splitting of this argument doesn't take place.

For a discussion on this topic, see:
http://stackoverflow.com/questions/4303128/how-to-use-multiple-arguments-with-a-shebang-i-e#4304187

**Comment by 75lb** [comment]
ok, thanks for letting me know - will look into removing the `--no-warnings` argument.

**Comment by 75lb** [comment]
is there anything stopping you upgrading to jsdoc2md v2? I don't maintain v1 anymore..

**Comment by 75lb** [comment]
i changed my mind because it's such a quick fix - i removed the `no-warnings` flag and released it in v1.3.9.. but generally, i'm not looking to maintain the old version.

**Comment by UlrichEckhardt** [comment]
Thanks for that speedy fix!

I'll be looking at upgrading to version 2. I tried that yesterday already, and the output changed a lot, so I tended towards 1.3.7 then. Maybe those changes are harmless though or can easily be dealt with. I'll take a look into it!

**Comment by 75lb** [comment]
> I tried that yesterday already, and the output changed a lot

Version 2 only introduced minor changes to the output - the release was more about upgrading the API but either way, good luck!
