### ISSUE TITLE
Class getters and setters.

### ISSUE THREAD

**Issue by Industrial** [jsdoc2md/jsdoc-to-markdown#107]
Hi.

The output looks like this:

https://github.com/Industrial/id-redux-modules/blob/adbc765d882501cfb136981d1fa711ea06680c0b/README.md

It features every getter and setter without distinction as a method with the same name

**Comment by 75lb** [comment]
hi. If you document both getter and setter then docs for both will appear in the output. If agree, it would be better if there was distinction, maybe it should say:

```
Kind: instance setter of GlobalClass
```

... but it's not a feature anyone has asked for until now.. Generally, there's no need to document both getter and setter. For example, this class will output docs for both:

```js
/**
 * A class.
 */
class Something {

  /**
   * Gets the size
   * @returns {string}
   */
  get size () {}

  /**
   * Sets the size
   * @param {string}
   */
  set size (val) {}
}
```

Personally, i think it's sufficient to document just one of the getter/setter pair as a `@type`. This removes the duplication in the output presenting a cleaner-looking API:

```js
/**
 * A class.
 */
class Something {

  /**
   * The size
   * @type {string}
   */
  get size () {}

  set size (val) {}
}
```
