### ISSUE TITLE
Ability to run jsDoc with custom plugins

### ISSUE THREAD

**Issue by cramatt** [jsdoc2md/jsdoc-to-markdown#109]
jsDoc supports custom plugins, for example [here is one for angularjs](https://github.com/allenhwkim/angular-jsdoc/blob/master/common/plugins/ngdoc.js). Because of the way jsdoc-to-markdown abstracts jsdoc, it does not seem possible to add plugins in this way. Additionally it seems plugins, like the dmd example, do not afford a way to extend this functionality. Any thoughts or ideas here?

**Comment by 75lb** [comment]
you can pass custom jsdoc configuration to `--configure`, or  [`options.configure`](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgetjsdocdataoptions--promise).. specify your plugins in the conf file as documented [here](http://usejsdoc.org/about-plugins.html)
