### ISSUE TITLE
rendered markdown code examples shows encoded quotations

### ISSUE THREAD

**Issue by kottin** [jsdoc2md/jsdoc-to-markdown#117]
I feel like this is something I'm doing wrong. I'm using a custom template to render my docs. When I include an example in my jsdoc string on a function that has a single quote it in, I end up getting the encoded value in my resulting markdown. Here is what I'm doing...

My template file looks like this (back ticks changed to quotes intentionally here)
```
#### Examples
{{#each examples}}
'''js
{{this}}
'''
{{else}}
N/A
{{/each}}
```

My jsdoc looks like this
```
...
* @example
 * let dbHost = config.get('dbConfig.host');
```

If I output the JSON from jsdoc2md it looks fine

```
...
"examples": [
      "let dbHost = config.get('dbConfig.host');"
    ],
...
```

but then the output I get when I pipe to my .md file looks like this

```js
let dbHost = config.get(&#x27;dbConfig.host&#x27;);
```

Am I doing something wrong here or is this intended behavior? I would like for the code example to show the single quote mark and not the encoded value.

**Comment by 75lb** [comment]
could you please post some steps to help me reproduce.. ideally, send a link to a gist or some code i can run.. if you're using a custom template, i will need to see that too.. 

read the "HTML Escaping" docs at http://handlebarsjs.com, just in case that is related..

**Comment by kottin** [comment]
HTML escaping did the trick. I knew it was something I was doing! Thanks for the speedy help. Y'all are doing great work here.
