### ISSUE TITLE
Can I merge modules with a similar name?

### ISSUE THREAD

**Issue by Redsandro** [jsdoc2md/jsdoc-to-markdown#118]
I often split out each function to its own file for modularity, and auto-require them.
How can I specify that certain files are part of the same module?

---

`barFunc.js`
```js
/**
 * This function is part of MyModule
 * @module MyModule
 */

/**
 * Do something with bar.
 * @alias barFunc
 * @param {string} bar
 * @returns {string}
 */
module.exports = bar => {}
```

`bazFunc.js`
```js
/**
 * This function is part of MyModule
 * @module MyModule
 */

/**
 * Do something with baz.
 * @alias bazFunc
 * @param {string} baz
 * @returns {string}
 */
module.exports = baz => {}
```

`fooFunc.js`
```js
/**
 * This function is part of MyModule
 * @module MyModule
 */

/**
 * Do something with foo.
 * @alias fooFunc
 * @param {string} foo
 * @returns {string}
 */
module.exports = foo => {}
```

---

```
jsdoc2md *.js
```

# Expectation:

---

## Modules

<dl>
<dt><a href="#module_MyModule">MyModule</a></dt>
<dd><p>This function is part of MyModule</p>
</dd>
</dl>

## Functions

<dl>
<dt><a href="#barFunc">barFunc(bar)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with bar.</p>
</dd>
<dt><a href="#bazFunc">bazFunc(baz)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with baz.</p>
</dd>
<dt><a href="#fooFunc">fooFunc(foo)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with foo.</p>
</dd>
</dl>

<a name="module_MyModule"></a>

## MyModule
This function is part of MyModule

<a name="barFunc"></a>

## barFunc(bar) ⇒ <code>string</code>
Do something with bar.

**Kind**: global function  

| Param | Type |
| --- | --- |
| bar | <code>string</code> | 

<a name="bazFunc"></a>

## bazFunc(baz) ⇒ <code>string</code>
Do something with baz.

**Kind**: global function  

| Param | Type |
| --- | --- |
| baz | <code>string</code> | 

<a name="fooFunc"></a>

## fooFunc(foo) ⇒ <code>string</code>
Do something with foo.

**Kind**: global function  

| Param | Type |
| --- | --- |
| foo | <code>string</code> | 

---

# Actual Result

---

## Modules

<dl>
<dt><a href="#module_MyModule">MyModule</a></dt>
<dd><p>This function is part of MyModule</p>
</dd>
<dt><a href="#module_MyModule">MyModule</a></dt>
<dd><p>This function is part of MyModule</p>
</dd>
<dt><a href="#module_MyModule">MyModule</a></dt>
<dd><p>This function is part of MyModule</p>
</dd>
</dl>

## Functions

<dl>
<dt><a href="#barFunc">barFunc(bar)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with bar.</p>
</dd>
<dt><a href="#bazFunc">bazFunc(baz)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with baz.</p>
</dd>
<dt><a href="#fooFunc">fooFunc(foo)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with foo.</p>
</dd>
</dl>

<a name="module_MyModule"></a>

## MyModule
This function is part of MyModule

<a name="module_MyModule"></a>

## MyModule
This function is part of MyModule

<a name="module_MyModule"></a>

## MyModule
This function is part of MyModule

<a name="barFunc"></a>

## barFunc(bar) ⇒ <code>string</code>
Do something with bar.

**Kind**: global function  

| Param | Type |
| --- | --- |
| bar | <code>string</code> | 

<a name="bazFunc"></a>

## bazFunc(baz) ⇒ <code>string</code>
Do something with baz.

**Kind**: global function  

| Param | Type |
| --- | --- |
| baz | <code>string</code> | 

<a name="fooFunc"></a>

## fooFunc(foo) ⇒ <code>string</code>
Do something with foo.

**Kind**: global function  

| Param | Type |
| --- | --- |
| foo | <code>string</code> |

**Comment by Redsandro** [comment]
I've been hacking at this, but I think the structure of both handlebars and the jsdoc api is too foreign for me to make all the right guesses.

I can filter the modules to be unique, but then member functions simply disappear from the output. I don't understand why, because in the `--json` output you can see that the modules are the same. There is no unique identifier that the members belong to. The only difference is the `order` number.

Ah well. I'll go celebrate weekend now. I'll just leave my (working) dmd edits here so I don't feel like I've wasted an hour.

---

`selectors.js:52`
```js
/**
 * render the supplied block for each module
 * @static
 */
function modules (options) {
  options.hash.kind = 'module'
  options.unique = 'name' // Added
  return handlebars.helpers.each(ddata._identifiers(options), options)
}
```

`ddata.js:449`
```js
function _identifiers (options) {
  var query = {}

  for (var prop in options.hash) {
    if (/^-/.test(prop)) {
      query[prop.replace(/^-/, '!')] = options.hash[prop]
    } else if (/^_/.test(prop)) {
      query[prop.replace(/^_/, '')] = new RegExp(options.hash[prop])
    } else {
      query[prop] = options.hash[prop]
    }
  }
  return arrayify(options.data.root)
    .filter(where(query))
    .filter(unique(options.unique)) // Added
    .filter(function (doclet) {
      return !doclet.ignore && (state.options.private ? true : doclet.access !== 'private')
    })
}
```

`ddata.js:786` (new)
```js
/**
Return function for filtering array based on specific key uniqueness
@param  {string} key Key to be unique
@return {function} Array returning function
 */
function unique(key) {
  var mem = {}
  return function(el) {
    //   return true // ignore this func // debug
    if (!key) return true
    if (!el[key]) return false
    if (!mem[el[key]]) {
       mem[el[key]] = true
       return true
    }
    return false
  }
}
```

**Comment by 75lb** [comment]
how does the output documentation for the above code look in plain jsdoc? I vaguely remember hitting this issue myself a couple of years ago, it may be solvable by tagging the functions in separate files with fully-qualified @alias namepaths linking them to the desired module. You may find you need to drop the `@module` tag in the separate files - I will check when i get some time. Run `jsdoc2md --namepaths` against your codebase to see the valid namepaths.

**Comment by Redsandro** [comment]
:warning: Admittedly, I'm doing this from memory as I was hacking in `/tmp` and files are gone now.

----

## Modules

<dl>
<dt><a href="#module_MyModule">MyModule</a></dt>
<dd><p>This function is part of MyModule</p>
</dd>
</dl>

## Functions

<dl>
<dt><a href="#barFunc">barFunc(bar)</a> ⇒ <code>string</code></dt>
<dd><p>Do something with bar.</p>
</dd>
</dl>

<a name="module_MyModule"></a>

## MyModule
This function is part of MyModule

<a name="barFunc"></a>

## barFunc(bar) ⇒ <code>string</code>
Do something with bar.

**Kind**: global function  

| Param | Type |
| --- | --- |
| bar | <code>string</code> |

**Comment by Redsandro** [comment]
But for now I worked around this by replacing every `@module MyModule` in code with `@memberof MyModule` except for one.

`@memberof` can also be in function jsdoc in stead. I believe in your documentation you make note of this, except you recommend `@alias module:MyModule`. However, this way you cannot make use of `@alias myFunction` for `module.export` type functions, so I think `@memberof` is superior in that regard, and the documentation could reflect this.

:warning: Except I'm not sure if it is the same. Perhaps hierarchy changes, and complex documentation has their member lists different. Not tested for more-than-basic use cases.
