### ISSUE TITLE
Can I mark a function as a method while keeping alias?

### ISSUE THREAD

**Issue by Redsandro** [jsdoc2md/jsdoc-to-markdown#119]
I'm not sure if this is possible. I hope you'll forgive me for asking this question here.

I have a module and a lot of files that export a single function automatically in the module with the filename as exported name. I would like all the exports to reflect this.

* `index.js`
* `myTest1.js`
* `myTest2.js`
* `someFunc3.js`
* etc...

```js
/**
 * Tests
 * index.js
 * @module tests
 */

/**
 * test 1
 * myTest1.js; automatically exported from module:tests as filename without extension
 * @alias myTest1
 */
module.exports = () => {}
```

> ## Modules
> 
> <dl>
> <dt><a href="#module_tests">tests</a></dt>
> <dd><p>Tests</p>
> </dd>
> </dl>
> 
> ## Functions
> 
> <dl>
> <dt><a href="#myTest1">myTest1()</a></dt>
> <dd><p>test 1</p>
> </dd>
> </dl>
> 
> <a name="module_tests"></a>
> 
> ## tests
> Tests
> 
> <a name="myTest1"></a>
> 
> ## myTest1()
> test 1
> 
> **Kind**: global function

Lists everything I want, but this is not actually a global function. Rather an exported function from `module:tests`.

---

```js
/**
 * Tests
 * @module tests
 */

/**
 * test 1
 * @alias module:tests 
 */
module.exports = () => {}
```

> <a name="module_tests"></a>
> 
> ## tests
> Tests
> 
> <a name="exp_module_tests--module.exports"></a>
> 
> ### module.exports() ⏏
> test 1
> 
> **Kind**: Exported function  

Correctly marked as exported function, but missing:

* alias/name
* modules list
* functions list

---

This comes close;

```js
/**
 * Tests
 * @module tests
 */

/**
 * test 1
 * @alias myTest1
 * @memberof module:tests
 */
module.exports = () => {}
```

> <a name="module_tests"></a>
> 
> ## tests
> Tests
> 
> <a name="module_tests.myTest1"></a>
> 
> ### tests.myTest1()
> test 1
> 
> **Kind**: static method of <code>[tests](#module_tests)</code>  

Correctly marked as belonging to `tests`, but missing:

* **⏏** 
* `Kind: Exported function`
* modules list
* functions list

**Comment by 75lb** [comment]
the Modules list will only appear if multiple modules are found in the input files. The Functions list appears when there are two or more global functions defined.

The `Kind: Exported function` will appear where a function has the same `@alias` as the `@module` it sits beneath (yes it must be beneath). Follow [this guide](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-a-CommonJS-module-(module.exports)) for best results (note "What not to do" at the bottom).

**Comment by Redsandro** [comment]
> The Kind: Exported function will appear where a function has the same `@alias` as the `@module` __it sits beneath__ (yes it must be beneath).

Perhaps this is a limitation of the `jsdoc` spec. When including an entire source tree into the parser, because all files are imported automatically in a modular context, there will only be one file (e.g. `index.js`) that defines the actual `@module`. Auto-imported files with names that are parsed earlier (e.g. `getUser.js`) will not sit beneath the module, and you [cannot copy the `@module` jsdoc definition](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/118) into those files so the function sits beneath, because you'll end up with a duplicate module for every file.

**Comment by 75lb** [comment]
while working on this, i recommend you generate docs using [jsdoc](https://github.com/jsdoc3/jsdoc). It's because the general rule is: if it doesn't work in jsdoc, it won't work in jsdoc2md. What you're doing is fairly advanced so i'd ensure everything looks sane and valid, working as expected in jsdoc documentation before trying in jsdoc2md.
