### ISSUE TITLE
Which partial prints the top level class name?

### ISSUE THREAD

**Issue by skarfacegc** [jsdoc2md/jsdoc-to-markdown#121]
My module only contains one class.  (It's primarily a CLI tool)

I want to suppress the ```# Classname ``` header
I suspect it's in the globals-* area, but I'm not entirely sure where the specific rendering comes from.

**Comment by skarfacegc** [comment]
Figured out that API Documentation was coming from a header comment that I missed.  Still can't figure out how to squash the ```# Class``` output

**Comment by 75lb** [comment]
well, [this](https://github.com/jsdoc2md/dmd/blob/master/partials/all-docs/docs/docs.hbs) is the template for each identifier.. if you don't want the header, omit it: 

```hbs
{{#class name="MyClass"}}
{{>body}}
{{>member-index~}}
{{>members~}}
{{/class}}
```

`MyClass` must be a valid namepath. Use `jsdoc2md --namepaths` to list all valid namepaths in the supplied source files.
