### ISSUE TITLE
Anchor with id rather than name

### ISSUE THREAD

**Issue by KevinAst** [jsdoc2md/jsdoc-to-markdown#122]
I am using jsdoc-to-markdown (ver: 3.0.0) to document the API in my project: https://astx-redux-util.js.org/1.0.0/.

For some reason, jsdoc2md creates anchors using **name** `<a name="ref">`, instead of **id** `<a id="ref"`.  As far as I know, the id is required by Markdown (and html for that matter) in order to link to it.

My current process applies a fix by overriding the header.hbs handlebar partial, changing `name=` to `id=` (you can see it at [`tooling/docs/header.hbs`](https://github.com/KevinAst/astx-redux-util/blob/v1.0.0/tooling/docs/header.hbs)), however **this seems like it should not be necessary**.

This seems so basic that I can't believe it is a bug.  **Am I missing something?**

Your help is greatly appreciated.

BTW: Great Library!

**Comment by 75lb** [comment]
hi! yes, it's because jsdoc2md output is primarily viewed on Github (in readme and API docs). Github has a whitelist for which attributes are respected in markdown source and `id` is not one them (id attributes get stripped). So, i used `name` which produced a working link in most browsers. But it's not always useful in environments other than Github, as you discovered. 

In your case, tweaking the header partial was the best idea.

**Comment by KevinAst** [comment]
Thanks for the quick reply!  *This gives me more insight into your dilemma (i.e. so many markdown parsers).*

When you say that Github flavored markdown strips the id attribute, would there be **anything wrong** with supplying **both** the `name` and `id` attributes?  This approach may accommodate more environments without the need to override partials.

**Thoughts?**

**FYI:** You may be interested in my [docs site](https://astx-redux-util.js.org/).
- I am promoting a very polished set of docs using Gitbook, while still relying on my embedded JSDoc comments for the API - **thanks to your jsdoc-to-markdown utility**.
- I know your primary thrust is Github-based readmes/apis, but **this takes it a step further**!
- I have created a **comprehensive [gist](https://gist.github.com/KevinAst/7e12648245ff2a8e9c1557135014b933) that details how I accomplished this**.
- If you think this info is valuable, **feel free to promote it** in your site.

**Thanks again for the great library!**

**Comment by 75lb** [comment]
> When you say that Github flavored markdown strips the id attribute..

not GFM, Github (as in github.com) strips the `id`.
https://github.com/github/markup

I will investigate leaving the `id` attribute in but for now, because it's not something that's been requested before, i think your tweaked header partial makes most sense.
