### ISSUE TITLE
Integrating GitBook with JSDoc using jsdoc-to-markdown

### ISSUE THREAD

**Issue by KevinAst** [jsdoc2md/jsdoc-to-markdown#124]
Your package is very much appreciated!  It was the cornerstone that allowed me to promote a very polished set of docs **_integrating GitBook with JSDoc_**.

I really wanted to drive my documentation using GitBook, promoting a very polished set of docs, but I didn't want to give up the auto-generation of my low-level API from my embedded JSDoc comments.

Here is an example of the end result (_notice the API is machine generated via jsdoc2md_): https://astx-redux-util.js.org/

I have written a comprehensive article that describes how I accomplished this: [Integrating GitBook with JSDoc to Document Your Open Source Project](https://medium.com/@kevinast/integrate-gitbook-jsdoc-974be8df6fb3).  I know your primary thrust is GitHub-based readmes, but **_this takes it to the next level_**!

I wanted to try to get the word out, and **I suspect this is something that your users may be interested in**.  If you feel this article has value, **_feel free to promote it in your site_** (_either you readme or your wiki_).

**Thanks again for the great package!**

**Comment by 75lb** [comment]
thanks, i may create a separate wiki page at some point to mention things like this but for now i don't know of any great demand.
