### ISSUE TITLE
[Question] Select identifiers belonging only to the current module in a block selector

### ISSUE THREAD

**Issue by johnBartos** [jsdoc2md/jsdoc-to-markdown#126]
Suppose I have the following partial:
````
// const-table.hbs
{{#module~}}
# {{name}}
###### {{description}}

|Code|Name|Description|
|:----:|:----:|:-----------|
{{#identifiers kind="constant"}}
|{{defaultvalue}}| {{name}} | {{description}} |
{{/identifiers}}
{{/module~}}
````

Which I use within a template:

````
{{#module name="Code"}}
{{>const-table}}
{{/#module}}

{{#module name="Category"}}
{{>const-table}}
{{/#module}}
````

On the following module:
````
/**
 * Codes are numerical values which represent a specific error
 * @module Error Code
 * */

/**
 * A network request returned with an HTTP status indicating failure
 *  @constant {number}
 *  @default 4001
 *  */
export const BAD_HTTP_STATUS = 4001;
/**
 * A network request was made without proper crossdomain credentials
 * @type {number}
 * @default 4002
 * */
export const CROSSDOMAIN_ERROR = 4002;
/**
 * A network request was made to an HTTP resource from HTTPS
 * @type {number}
 * @default 4003
 * */
export const BLOCKED_MIXED_CONTENT = 4003;
````
(the other module contains the same syntax)

How would I go about restricting each instance of `const-table` to the identifiers found only within the module itself? As it stands my `const-table` template includes identifiers from all modules and not just the ones I have restricted it to. I have tried this:

{{#identifiers kind="constant" memberof="{{../id}}"}}

But no element passes this, despite `memberof` and `../id` being equal (according to my debugging).

**Comment by 75lb** [comment]
this doesn't look valid syntax to me: `{{#identifiers kind="constant" memberof="{{../id}}"}}`, I may be wrong (it's been a while) but i don't think nested curly braces are valid.. 

also, I don't think your `const-table` partial needs to be wrapped in a `{{#module}}` if the higher-level partial is calling it within the context of `{{#module name="Code"}}`.

Some handlebars homework required, i think.. i'll be honest - i'm not a fan and future versions will not use it.
