### ISSUE TITLE
Doesn't work with async functions

### ISSUE THREAD

**Issue by selfrefactor** [jsdoc2md/jsdoc-to-markdown#128]
I fail to use the service, as I am using `async` function. Are there any plan to start supporting `async` syntax and if so, when?

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2016-features

**Comment by iCrawl** [comment]
Any updates on this? Esp with the release of node 8 async/await is more than just something you babel down.
Also considering jsdoc supports the syntax since 3.5.

**Comment by 75lb** [comment]
@iCrawl I already posted the link to the solution https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2016-features

**Comment by iCrawl** [comment]
I am aware you did. I was simply asking if theres any plans to implement it without including those babel dependencies and convert them to generators for the docs.

**Comment by 75lb** [comment]
Ah, i see - you're asking to make jsdoc2md work with ES2017 code by default (without jsdoc plugins). Yes, that is coming soon - i'm testing the latest jsdoc release atm.

**Comment by victusfate** [comment]
That link isn't working, should I just bump jsdoc2md (latest release patches)?

**Comment by 75lb** [comment]
apologies, the links in the above comments now work (i updated them).. Here is the link:
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2017-features

Regarding this issue, I am still testing jsdoc 3.5.3 with jsdoc2md. The jsdoc upgrade does remove the need for babel plugins but also introduces new issues, which i'm looking into.

**Comment by victusfate** [comment]
Thanks @75lb -> really appreciate your work developing jsdoc-to-markdown
update: tried the above and it appears to skip most of my class method docs
would happily try out an experimental branch babelfree

**Comment by 75lb** [comment]
it's probably nothing to do with babel.. [read the docs again](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)), especially this part

> Given that jsdoc2md only generates markdown for documented identifiers and modules, you must document each identifier you want to appear in output.

Your class methods will only appear in output if both the parent class *and* the module (if it lives in a module) are documented.

**Comment by victusfate** [comment]
If I comment out the async class methods the docs show up aok, thanks for the tip though. I'll wait and come back to it when ready.

**Comment by 75lb** [comment]
I uploaded a pre-release which uses jsdoc 3.5.4 for you to try: 

```
$ npm install -g jsdoc-to-markdown@next
```

**Comment by scholtzm** [comment]
I tried to get this to work with a class that contains `async` methods and `js2doc` would generate invalid files. Commenting out the `async` method and disabling setup steps from [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2017-features) would produce a valid file.

I can try to provide reproduction case if needed.

**Comment by gerardobort** [comment]
I'm having the same issues as @scholtzm described. It seems that passing the code through `jsdoc-babel`, it parses the comment blocks partially, skipping all the method definitions within the classes.
