### ISSUE TITLE
Feature Request: Embed Into Markdown

### ISSUE THREAD

**Issue by fidian** [jsdoc2md/jsdoc-to-markdown#130]
I would like to have a `README.md` with a bit more content than just the documentation generated by this tool. Would it be possible to include an option that would embed the generated markdown between two tags in the README?

    Sample Readme File
    ------------------
    
    Words go here to describe stuff
    
    API
    ---

    [//]: # (JSDOC2MD-START)
    ... automatically generated content goes here
    [//]: # (JSDOC2MD-END)

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-README-template

**Comment by fidian** [comment]
Sorry, I wish I noticed that earlier. Thanks for pointing me in the right direction!

**Comment by 75lb** [comment]
no problem

**Comment by 75lb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add req/res view events to Server.js](https://trello.com/c/g2q4bMrS/152-add-req-res-view-events-to-serverjs)
