### ISSUE TITLE
how to make myself template

### ISSUE THREAD

**Issue by swliu920322** [jsdoc2md/jsdoc-to-markdown#131]
i am a chinese.i use this tool to transform annotation to markdown files. the template you supply is very good, but i need some custom attribute.can you guide me how to do it? thanks!

**Comment by swliu920322** [comment]
i find some useful info in dmd/partials files

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki

**Comment by swliu920322** [comment]
@75lb  how to use default value attribute,now i put all tag in my hbs file

{{>main-index~}}
{{#orphans ~}}
{{>header~}}
    {{>deprecated~}}
    {{>description~}}
    {{>scope~}}
    {{>summary~}}
    {{>augments~}}
    {{>implements~}}
    {{>mixes~}}
    {{>default~}}
    {{>chainable~}}
    {{>overrides~}}
    {{>returns~}}
    {{>category~}}
    {{>throws~}}
    {{>fires~}}
    {{>this~}}
    {{>access~}}
    {{>readOnly~}}
    {{>requires~}}
    {{>customTags~}}
    {{>see~}}
    {{>since~}}
    {{>version~}}
    {{>authors~}}
    {{>license~}}
    {{>copyright~}}
    {{>todo~}}
    {{#if params}}

    {{/if}}
    {{#if (optionEquals "param-list-format" "table")~}}
        {{#if (optionEquals "no-gfm" true)}}
            {{>params-table-html~}}
        {{else}}
            {{#if params}}
{{tableHead params "name|参数" "type|类型" "defaultvalue|默认值" "description|描述" ~}}
                {{#tableRow params "name" "type" "defaultvalue" "description" ~}}
                    | {{#if @col1}}{{>param-table-name}} | {{/if~}}
                    {{#if @col2}}{{>linked-type-list types=type.names delimiter=" \| " }} | {{/if~}}
                    {{#if @col3}}{{>defaultvalue}} | {{/if~}}
                    {{#if @col4}}{{{stripNewlines (inlineLinks description)}}} |{{/if}}
                {{/tableRow}}
            {{/if}}
        {{/if~}}
    {{/if~}}
    {{>properties~}}
    {{>examples~}}
    {{>member-index~}}
    {{>separator~}}
    {{>members~}}
{{/orphans~}}

**Comment by swliu920322** [comment]
/**
 * A quite wonderful function.
 * @param {object} - (1) - privacy gown
 * @param {string} - show
 * @param {string} - show1
 * @returns {survival}
 */
function protection(a, b, c) {
}

**Comment by swliu920322** [comment]
@75lb thanks, now i use your template, i put all minimum tag to my hbs file and delete some unused, you are so kind,
