### ISSUE TITLE
How to use plugin jsdoc-babel in jsdoc2md.render()

### ISSUE THREAD

**Issue by taoqf** [jsdoc2md/jsdoc-to-markdown#133]
```js
gulp.task('docs', () => {
	const fs = require('fs')
	const jsdoc2md = require('jsdoc-to-markdown')

	const output = jsdoc2md.renderSync({
		files: 'dist/**/*.js',
		plugin: "jsdoc-babel",
		plugins: ["node_modules/jsdoc-babel"],
		babel: {
			presets: ["es2015"],
			plugins: ["transform-async-to-generator"]
		}
	});
	fs.writeFileSync('api.md', output)
});
```
It seems neither `plugin` nor `plugings` will work.

**Comment by 75lb** [comment]
if you look at the [render docs](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdrenderoptions--promise) for `options` it says "Accepts all getJsdocData options plus the following", meaning you can also pass in `configure` (the option you want). 

Create a jsdoc config file (as described [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2016-features)) then pass its path to `configure`.

**Comment by taoqf** [comment]
do not get it, this doesn't work.
```js
gulp.task('docs', () => {
	const fs = require('fs')
	const jsdoc2md = require('jsdoc-to-markdown')

	const output = jsdoc2md.renderSync({
		files: 'dist/**/*.js',
		// source: ['dist/**/*.js'],
		// plugin: "jsdoc-babel",
		configure: {
			plugins: ["node_modules/jsdoc-babel"],
			babel: {
				presets: ["es2015"],
				plugins: ["transform-async-to-generator"]
			}
		}
	});
	fs.writeFileSync('api.md', output)
});
```

**Comment by 75lb** [comment]
you didn't read my reply, read it again: 

>  **Create a jsdoc config file (as described here) then pass its path to `configure`**.

**Comment by taoqf** [comment]
I think I did, but you know, I was trying to use gulp, nor gulpfile.js plus jsdoc config file,  is there a way to do this?btw, how could this be use? 

[options.plugin] | string \| Array.<string> | Use an installed package containing helper and/or partial overrides.
-- | -- | --

**Comment by 75lb** [comment]
some info on `options.plugin` [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin).

Your gulp config must look like this: 

```
const output = jsdoc2md.renderSync({
		configure: 'path-to-jsdoc-config.json'
	});
```

**Comment by taoqf** [comment]
thanks, is there a way to config without a json file?

**Comment by 75lb** [comment]
no, not yet. The json file is required by jsdoc (jsdoc-to-markdown is a
wrapper around jsdoc).
