### ISSUE TITLE
Upgrade underlying jsdoc 

### ISSUE THREAD

**Issue by 75lb** [jsdoc2md/jsdoc-to-markdown#134]
[Jsdoc version 3.5.0](https://github.com/jsdoc3/jsdoc/releases) was released recently which is able to parse any ES2017 code without the need for Babel plugins. This will mean jsdoc2md users will no longer need to follow the process described [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2017-features).

I'm testing v3.5.3 with jsdoc2md now, there are a few issues but no blockers. A new jsdoc2md release is imminent. 

I'm also considering dropping the `--html` feature as it gets little use.

**Comment by 75lb** [comment]
I published a pre-release which uses `jsdoc@^3.5.3`. Generally it works fine but I've found a few differences in output which i'm reviewing. Please try it for yourself and let me know if you find any issues. 

```
$ npm install -g jsdoc-to-markdown@next
```

**Comment by 75lb** [comment]
Has anyone had time to test `jsdoc-to-markdown@next`? Does everything working ok?

@victusfate @hydrabolt @weizhongtan @IUnknown68 @wemakeweb @beejjacobs @arronhunt

**Comment by 75lb** [comment]
Fixed and released in [v4.0.0](https://github.com/jsdoc2md/jsdoc-to-markdown/releases/tag/v4.0.0) 👍

**Comment by Rybadour** [comment]
I'm confused, you're still using jsdoc-parse 3.0 doesn't this mean it's still using jsdoc 3.0? I've recently ran into a problem with "export class" not being recognized as an ES6 class. This appears to be fixed in JsDoc 3.5. Thoughts?

**Comment by 75lb** [comment]
jsdoc2md uses jsdoc-api, which uses jsdoc v3.5.. exporting values from ECMAScript modules works fine.. [examples here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)).
