### ISSUE TITLE
Question : How to configure --access public

### ISSUE THREAD

**Issue by avighier** [jsdoc2md/jsdoc-to-markdown#135]
Hi,

During 1 hour, I have tryed to configure --access jsdoc to avoid documenting @protected methods, but without success.

Does someone know how to do ?

Thanks.

**Comment by 75lb** [comment]
create a [config file](http://usejsdoc.org/about-configuring-jsdoc.html) with your options then pass the config file path to `--configure`, e.g. 

```
$ jsdoc2md --configure jsdoc.json src/*.js
```

**Comment by avighier** [comment]
Hi,

Thanks for the anwser. But I should be stupid ... That doesn't work for me.

jsdoc.json
```
{
    "opts": {
        "access": "public"
    }
}
```

When I run `node_modules/.bin/jsdoc -c jsdoc.json  src/**/*.js` : it works !
When I run `node_modules/.bin/jsdoc2md --configure=jsdoc.json  src/**/*.js` : It don't 

Note that `node_modules/.bin/jsdoc2md --configure=notExists.json  src/**/*.js` doesn't throw error. It seems to ignore --configure.

**Comment by avighier** [comment]
Note I have 'jsdoc-to-markdown@3.0.0'
