### ISSUE TITLE
Parse out additional constants

### ISSUE THREAD

**Issue by summercloud** [jsdoc2md/jsdoc-to-markdown#136]
My js code like this
```
/**
 * ------------------------------------------------------------
 * KLButton 按钮
 * @author Cody Chan <int64ago@gmail.com>
 * ------------------------------------------------------------
 */

const validator = require('validator');
```
and use jsdoc2md.renderSync() to render
but the result markdown is 
```
## validator
------------------------------------------------------------
KLButton 按钮

**Kind**: global constant  
**Author:** Cody Chan <int64ago@gmail.com>
------------------------------------------------------------  
```
i didn't set validator in /**...*/
why is rendered out?
did i do something wrong?

**Comment by 75lb** [comment]
jsdoc thinks that your `/** ... */` comment is documentation for `validator`. I would try adding a `@file` (or similar) tag to that comment but anyway, this is a question for the Jsdoc project, not jsdoc2md. 

Always ensure your documentation renders correctly using [jsdoc](http://usejsdoc.org/) first. If it doesn't work in jsdoc, it won't work in jsdoc2md.
