### ISSUE TITLE
JSDOC_ERROR: There are no input files to process.

### ISSUE THREAD

**Issue by UsulPro** [jsdoc2md/jsdoc-to-markdown#137]
Hi! I tried to figure out how to use this tool. I wanted to parse my `src/index.js` but without any success:

![image](https://user-images.githubusercontent.com/14885189/30166111-00ff23a6-93eb-11e7-917a-972258b96cb8.png)

Do I miss some steps which should be done before it?

**Comment by 75lb** [comment]
you are using the command correctly, it's like this:

```
$ jsdoc2md -f file1.js file2.js file3.js
```

Which terminal on which platform are you using? If it's WIndows, try putting quotes around your file expression: 

```
$ jsdoc2md -f "*.js"
```

**Comment by UsulPro** [comment]
I use Gnome terminal on Ubuntu.
I tried both: `jsdoc2md -f "example.js"` and `jsdoc2md -f example.js` - it still throws this error
Do I need to setup something else except installing `jsdoc-to-markdown` as a devDependency? Or it should be installed globally?

**Comment by 75lb** [comment]
strange, i just tested it successfully on Gnome terminal on Ubuntu.. maybe try reinstalling it.. which version of node and npm do you have?

**Comment by UsulPro** [comment]
node 7.10
npm 4.2

**Comment by UsulPro** [comment]
@75lb I casually found the cause of the error!
It appears when I add an empty line to jsdoc comments.
Steps to reproduce:

1. This works:
```js
/**
 * filters messages accordingly to include/exclude settings
 * @param {*} messages 
 * @param {*} exclude 
 * @param {*} include 
 */
```

2. This throws an error:
```js
/**
 * filters messages accordingly to include/exclude settings
 *
 * @param {*} messages 
 * @param {*} exclude 
 * @param {*} include 
 */
```

**Comment by UsulPro** [comment]
Finally, I dug out that the error appears when you have a folder starting with the underscore in your path. In my case it was `_sm-react`, but it reproducible with any other names: 
`x_x` works
`_xx` doesn't work. 

To reproduce you can clone `https://github.com/sm-react/storybook-addon-console.git` to `_xx` folder and `yarn && yarn dev:docs`. The first pass works fine, but if you change anything in `src/index.js` you'll see this error.

For me, it is not so critical to change the name of the folder, so I'm going to close this issue. Still not sure is it reproducible on other machines except the mine.

**Comment by 75lb** [comment]
i tracked it down to jsdoc (which jsdoc2md uses internally).. by default, jsdoc ignores file names beginning with a leading underscore - no idea why..

See the "Default configuration options" section of the [config file instructions](http://usejsdoc.org/about-configuring-jsdoc.html). 

You can pass in a custom jsdoc config using the `--configure` option of jsdoc2md.

**Comment by UsulPro** [comment]
...heh so it's an expected behavior :sweat_smile:
looks like the reason is to keep private parts of code
Thanks for pointing that!
