### ISSUE TITLE
Support multiple types inside <> e.g. Promise<Device, ResponseError>

### ISSUE THREAD

**Issue by plasticrake** [jsdoc2md/jsdoc-to-markdown#138]
Look like `jsdoc2md` doesn't support having multiple types inside <>. `jdsoc` seems to have no issue with this.

I'm documenting my promises this way: 
```
@return {Promise<Device, ResponseError>}
```
And jsdoc2md seems to not create links to Device or ResponseError. However this will at least:
```
@return {Promise<Device>}
```
I know jsdoc2md has its own @fulfil and @reject tags, but I'm trying to generate documentation with other tools as well.

Is this something that can be supported?

Thanks! 😸

**Comment by plasticrake** [comment]
I created a pull request here: jsdoc2md/dmd#51

**Comment by 75lb** [comment]
Closing as the PR submitted was closed
