### ISSUE TITLE
ERROR, Cannot find module.

### ISSUE THREAD

**Issue by stefanwalther** [jsdoc2md/jsdoc-to-markdown#139]
Hi,

I was trying to follow the approach how you have defined the setup in this project:

First I installed `jsdoc-to-markdown` as a local dev-dependency.
Then I have added the following script:

```js
"scripts": {
   "api-docs": "./node_modules/jsdoc-to-markdown/bin/cli.js src/index.js --heading-depth 1 --template docs/api-docs-template.hbs > docs/api.md; echo "
}    
```

The content of the `api-docs-template.hbs` looks as follows:

```html
{{#module name="jsdoc-to-markdown"}}{{>docs}}{{/module}}
```

When I now run `npm run api-docs` (I am using node v8.4.0), the file `./docs/api.md` gets created, but with the following content

```
ERROR, Cannot find module.
```
If I though run just `./node_modules/jsdoc-to-markdown/bin/cli.js src/index.js --heading-depth 1` I get the correct result in stdout.

What am I missing?
I was able to just create the file (`./node_modules/jsdoc-to-markdown/bin/cli.js src/index.js --heading-depth 1 > docs/api.md`), but I was curious what you were doing here ...

Thx for your help in advance!

Regards
Stefan

**Comment by 75lb** [comment]
inside the template you need to specify a valid module namepath from your
source code..  run `jsdoc2md --namepaths your-source.js` to get a list of
valid namepaths in your code.. pass a module namepath to the {{module}}
helper

**Comment by stefanwalther** [comment]
Thx a lot!

**Comment by VityaSchel** [comment]
Still getting error. Might be an issue with ".js" in end of module name and it also must be same as specified in package.json.
