### ISSUE TITLE
caching causes issues

### ISSUE THREAD

**Issue by hundekoerper** [jsdoc2md/jsdoc-to-markdown#147]
When attempting to generate docs like this, I run into issues where all generated markdown files are duplicates of the same file. However when I disable caching I have no issues whatsoever.

```js
  const renders = files.map(file => jsdoc2md.render({source: file}));

  Promise.all(renders)
    .then(docs => {
      docs.forEach((doc, index) => {
        const filePath = paths[index];
        const fileName = path.basename(filePath, path.extname(filePath));
        const target = path.resolve(targetPath, `${fileName}.md`);

        console.log('Creating docs for:', fileName);

        fs.writeFileSync(target, doc);
      });
      return;
    })
    .then(() => {
      console.log('\nDone generating docs.\n');
    })
    .catch(error => {
       [...]
    });
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc-to-markdown            | [next (version with updated jsdoc)](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/134)
| Node.js          | 8.2.1
| npm              | 5.5.1
| Operating system | MacOS Sierra 10.12.6

**Comment by chrisdothtml** [comment]
Same issue here. One file was picking up the cache of a completely different file. Led to half an hour of very confused debugging. Disabling caching also fixed for me

**Comment by 75lb** [comment]
could someone post a failing test case to help me reproduce this please?

**Comment by 75lb** [comment]
never mind, i have reproduced it when you pass in input via `source`.

**Comment by 75lb** [comment]
Fixed in [jsdoc-api](https://github.com/jsdoc2md/jsdoc-api) v4.0.2. For now, caching is disabled when passing in input via the `source` property. Please update or reinstall jsdoc2md to pick up the change.
