### ISSUE TITLE
feature request: support TypeScript style class code

### ISSUE THREAD

**Issue by vvakame** [jsdoc2md/jsdoc-to-markdown#15]
Please support TypeScript style class code.

http://goo.gl/JMi7Wu
TypeScript convert class syntax to prototype style code, but it emit immediate function pattern.
but I can't found ignore immediate function in jsdoc-to-markdown.

I want do this image.
```
$ jsdoc2md lib/**/*.js -j | \
  sed -e 's/<anonymous>~//' | \
  sed -e 's/"memberof": "<anonymous>",//' | \
  sed -e 's/"scope": "inner"/"scope": "global"/' | \
  dmd --template README.tmpl.md > README.md
```
but dmd not support --template option.

**Comment by 75lb** [comment]
hmm, this is a difficult one for me to fix.. jsdoc is for javascript, not typescript.. i do not control the output of the typescript compiler therefore i cannot predict what it will generate, or whether that generated code will be compatible with the jsdoc syntax.. closing.
