### ISSUE TITLE
How to output the md file in Chinese

### ISSUE THREAD

**Issue by BenzLeung** [jsdoc2md/jsdoc-to-markdown#150]
I found a repository named "dmd-locale-en-gb". It seem useful to localize the output. But I wonder how to create a "dmd-locale-chinese" and use it output a Chinese markdown doc.

(Forgive my pool English)

**Comment by 75lb** [comment]
I'm sorry, that repository is dead - i will delete it. However, I will leave this issue open as multi-lingual output is required. Currently, you need to [create a custom partial](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial) for each section of the output you wish to translate.

**Comment by BenzLeung** [comment]
I just built a plugin called ["dmd-plugin-zh-cn"](https://github.com/BenzLeung/dmd-plugin-zh-cn). It output md file in Simplified Chinese.
