### ISSUE TITLE
ES5 object getter/setter

### ISSUE THREAD

**Issue by GMartigny** [jsdoc2md/jsdoc-to-markdown#153]
Hi,
Using ES5 object getter and setter, the output markdown is kind of misleading. The output has 2 functions with the same name and not much else to differentiate them.

I might be doing something wrong, so here a code example :

```js
class Whatever {
	/**
	 * Get prop value
	 * @return {String}
	 */
	get prop () {
		return this._prop;
	}
	/**
	 * Set prop value
	 * @param {String} val - New value
	 */
	set prop (val) {
		this._prop = val;
		this.rebuild();
	}
}
```

Output :

```md
#### prop
Set prop value

**Kind**: instance property of [<code>Whatever</code>](#Whatever)

| Param | Type | Description |
| --- | --- | --- |
| val | <code>String</code> | New value |

#### prop ⇒ <code>String</code>
Get prop value

**Kind**: instance property of [<code>Whatever</code>](#Whatever)
```

Expected, at least a Getter / Setter tag for each and perhaps some smart way to show it's a "magic" getter/setter :

```md
#### **Setter** prop
Set prop value

**Kind**: instance property of [<code>Whatever</code>](#Whatever)

| Param | Type | Description |
| --- | --- | --- |
| val | <code>String</code> | New value |

#### **Getter** prop ⇒ <code>String</code>
Get prop value

**Kind**: instance property of [<code>Whatever</code>](#Whatever)
```

**Comment by 75lb** [comment]
Document one of the two getter/setter functions as a property - because that's essentially what it is.

Something like this. 

```js
/**
 * The class to do that thing.
 */
class Whatever {
  constructor () {
    /**
     * A property
     * @type {string}
     */
    this.prop = null
  }
  get prop () {
    return this._prop;
  }
  set prop (val) {
    this._prop = val;
    this.rebuild();
  }
}
```

Output.

<a name="Whatever"></a>

## Whatever
The class to do that thing.

**Kind**: global class
<a name="Whatever+prop"></a>

### whatever.prop : <code>string</code>
A property

**Kind**: instance property of [<code>Whatever</code>](#Whatever)
