### ISSUE TITLE
Is there a wiki policy?

### ISSUE THREAD

**Issue by ozum** [jsdoc2md/jsdoc-to-markdown#155]
Hi,

I added a wiki page about [how to document TypeScript](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-TypeScript). 

I added it directly, because I couldn't see any rule/policy to add wiki pages. If there is any, I could revise my entry accordingly.

**Comment by 75lb** [comment]
hi, yes I saw your entry - thanks for that. Good work. There is currently no wiki policy but I read your work and it seems useful. However, I have zero knowledge about Typescript so I'm not qualified to comment on the article content.
