### ISSUE TITLE
Custom helper documentation

### ISSUE THREAD

**Issue by CarbonCollins** [jsdoc2md/jsdoc-to-markdown#157]
Hi,

i was looking on the wiki earlier today in order to try and add a helper function into the templating for a project i was working on, however i was unable to find any documentation on how to add it.

Does this documentation exist and if so is it just missing the link on the wiki page here: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki

Thanks,

**Comment by 75lb** [comment]
Hi Steve,

You’re right, the wiki is lacking that article. I’ll have a quick look into it now. 

L

**Comment by 75lb** [comment]
there is a quick note about creating a new helper on this page
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin

**Comment by CarbonCollins** [comment]
awesome, I'll have a quick read.

thanks for the quick response
