### ISSUE TITLE
Encoding issue when writing to file

### ISSUE THREAD

**Issue by eslachance** [jsdoc2md/jsdoc-to-markdown#158]
When I use `jsdoc2md src/index.js > doc.md` I get what seems to be an encoding issue: ` ΓçÆ ` appears insead of `⇒` in the output. How do I resolve this?

**Comment by eslachance** [comment]
Uhm, thanks for closing with no comment or response whatsoever? Great service!

**Comment by IAIOMAN117EDU** [comment]
I was looking into this for the very same reason, its a shame the developers of this project are not taking ownership of their errors.

**Comment by 75lb** [comment]
Hi, could you post a fresh issue with:

* details of your OS, node, jsdoc2md and terminal versions
* a reproduction case: some input i can use to reproduce, debug and fix the issue. 

cheers 👍

**Comment by zlw11063** [comment]
Hi there,

Same issue here. The deets:

**OS**: Windows 10
**Node**: v8.9.0
**Editor**: VSCode 1.23.1
**jsdoc2md**: Downloaded today using typical global install with npm

Here is the command I ran:
```
jsdoc2md .\dataHandler.js > test.md
```

Here are some of the jsdoc comments I have that caused it:
```js
/**
 * Gets an item from storage.
 * @async
 * @param {object} itemInfo - the details about the item
 * @return {object} the retrieved item
 */
async function getItem(itemInfo) {
    // This is a stub function, is empty for now
}

/**
 * Gets a category from storage.
 * @async
 * @param {object} categoryInfo - the details about the category
 * @returns {object} the retrieved category
 */
async function getCategory(categoryInfo) {
    // This is a stub function, is empty for now
}
```

The elements in the MD file containing the incorrect symbol:
```
<dt><a href="#getItem">getItem(itemInfo)</a> ΓçÆ <code>object</code></dt>
<dd><p>Gets an item from storage.</p>
</dd>
<dt><a href="#getCategory">getCategory(categoryInfo)</a> ΓçÆ <code>object</code></dt>
<dd><p>Gets a category from storage.</p>
</dd>
```

Loving the package so far. The documentation is incredibly clean - would just love to see this minor bug figured out. Let me know if I can help any other way.

**Comment by lstak** [comment]
I bumped into same issue. It seems that Powershell (by default) does not handle the output stream as utf8, hence the encoding issues with the CLI. A small node program using the package doesn't have the encoding issues:

````
const jsdoc2md = require('jsdoc-to-markdown')
const fs = require('fs')

jsdoc2md.render({ files: 'my-file.js' })
  .then(output => fs.writeFile('docs.md', output, ()=> process.exit(0))
)
````
works as expects

**Comment by 75lb** [comment]
Hi, thanks for the detail and reproduction cases, I'm on holiday with the kids atm but will get onto this ASAP. If anyone has a fix so far please post a PR, even if only a partial fix - it will give me more context. 

@Istak Which OS are you using?

**Comment by lstak** [comment]
This is on Windows 10. I believe this is not a bug in jsdoc2md, but rather the unintuitive way Powershell is dealing with character encoding:

jsdoc2md sends output to stdout in UTF8, but without a BOM. And without a BOM, Powershell assumes the character stream is in system encoding (which is not UTF8). So, just piping the output of jsdoc2md in a file like jsdoc2md myfile.js > doc.md will lead to character encoding issues.

You can force the input/output encoding in Powershell to be utf8 like so:

`` $OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding =
                    New-Object System.Text.UTF8Encoding
``

After this,, jsdoc2md myfile.js > doc.md will produce a utf8 file without encoding issues. Beware, though, that if you look at the output of jsdoc2md myfile.js you will see ? characters. This is not an encoding issue, but the result of Powershell using a font that doesn't have characters for eg the arrow used in dmd.

I hope this makes sense.

**Comment by 75lb** [comment]
This seems to be a Windows-only issue. Here's a summary of what i've found so far: 

*Using Windows `cmd`*
- Output to terminal (e.g. `jsdoc2md something.js`): incorrect character shown. 👎 
- Output to file (e.g. `jsdoc2md something.js > something.md`): correct character shown. 👍 

*Using Windows powershell*
- Output to terminal: incorrect character shown. 👎 
- Output to file: incorrect character shown. 👎 

If you pipe your docs to a file using `cmd` you should be fine.

Powershell users, if the font used by the terminal doesn't include the `⇒` glyph, I can't fix that. However, the output piped to a file needs to work and not include the `ΓçÆ` characters. As @lstak said, the solution for Powershell users would be for `dmd` to include a BOM character (`'\uFEFF'`) as the first character in the output. As this is a niche requirement for Powershell users only I can't make it the default, however i could add a `jsdoc2md --bom` flag to include it. How does that sound?

**Comment by lstak** [comment]
I like the solution. It should definitely not be the default, but with this flag you can use jsdoc2md CLI in Powershell, without having to set the input/output encoding settings in Powershell. 

Thanks for you support!
