### ISSUE TITLE
How to hide **Kind** tag

### ISSUE THREAD

**Issue by DemonCloud** [jsdoc2md/jsdoc-to-markdown#159]
```js
  /**
   * A qute wonderful function app
   * @param a {object} - privacy gown
   * @param b {object} - security
   * @example
   * RAP.app(funck)
   */
   function app(a,b){}
```

it will auto generate **Kind** property, how do i disable it

**Comment by aisapatino** [comment]
You could use a custom partial - either

- Provide an empty [`scope.hbs`](https://github.com/jsdoc2md/dmd/blob/47459a97944227b381271556f4538835a1bf9575/partials/all-docs/docs/body/scope.hbs)
or
- Provide a copy of [`body.hbs`](https://github.com/jsdoc2md/dmd/blob/47459a97944227b381271556f4538835a1bf9575/partials/all-docs/docs/body/body.hbs#L3) with the `{{>scope}}~` line removed

Here's more info on how to use custom partials: [jsdoc-to-markdown/wiki/Create-a-custom-partial](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial)

For example:
1. Create an empty scope template:
  `$ touch scope.hbs`
2. Pass it to jsdoc2md to override the default scope.hbs template
  `$ jsdoc2md --partial scope.hbs --files src/*.js`

**Comment by 75lb** [comment]
thanks @aisapatino , yes this is currently the recommended way to tweak the output.
