### ISSUE TITLE
Splitting a single file in multiple .md files

### ISSUE THREAD

**Issue by vdininski** [jsdoc2md/jsdoc-to-markdown#16]
Is splitting a single monolithic file with `jsdoc`-style comments in separate files supported? If a single file exposes multiple `classes` is there a way to generate separate files for each definition? Perhaps using some other meta-information or using a parameter which takes into account the type definitions?

**Comment by 75lb** [comment]
yes, there is a way.. are you using the stable `5.*` release, or the `@next` release? If you are using `@next` i can show you how..

**Comment by vdininski** [comment]
We have made some tests using the 5.* release, however we are open to using the `@next` release as long as the API is somewhat stable and probably won't change much before releasing

**Comment by 75lb** [comment]
best to use @next, it's so far ahead of the current release.. yes, a few things will change over time but the library and command-line APIs should be fairly stable.. if they do break in future releases, you can choose not to upgrade until you are ready.. 

install it
```
$ npm install -g jsdoc-to-markdown@next
```
then take a look at this output example.. it demonstrates how to cherry-pick certain classes:
https://github.com/75lb/jsdoc-to-markdown/blob/next/example/identifier-blocks/md/class.md

the template used to create this markdown is here: https://github.com/75lb/jsdoc-to-markdown/blob/next/example/identifier-blocks/template/class.hbs

the script i used to render it: 
https://github.com/75lb/jsdoc-to-markdown/blob/next/example/identifier-blocks/render.js

**Comment by vdininski** [comment]
Thanks, this seems like exactly the thing that we need!

**Comment by 75lb** [comment]
good, i hope so.. obviously this is bleeding edge stuff (i'm still documenting it all) so don't be shy to tell me of any issues.. i still have work to do before release..

**Comment by vdininski** [comment]
Except for class cherry-picking is there a way to essentially split a monolithic js file with multiple classes in separate MD files using the same template?

**Comment by 75lb** [comment]
so, you have one massive JS input file and you want to split the documentation out into multiple output files? For example, document one class or object per output file?

**Comment by vdininski** [comment]
Exactly. I can think of one way to do it - a grunt job which would dynamically generate templates and execute jsdoc against each one. While this is fine with this approach I would have to also maintain a list of the "classes" for which the documentation is to be generated. Instead wouldn't it be better if there was a flag which would tell the generator to apply a template on each `@class` definition and output a single file per class.

**Comment by 75lb** [comment]
leave it with me @vdininski, will get back to you

**Comment by 75lb** [comment]
here's an example script, dynamically creating one output file per class in the input source: https://github.com/75lb/jsdoc-to-markdown/blob/next/example/scripts/class-per-file.js

**Comment by 75lb** [comment]
@CarbonCollins the example [now lives in the wiki](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class)

**Comment by piranna** [comment]
Any plan to add an option for that in the command line? Ideally, there should be 1-to-1 mapping between source code files and docs files...

**Comment by 75lb** [comment]
@piranna sorry, no immediate plans for that
