### ISSUE TITLE
[Feature Request] @summary placement

### ISSUE THREAD

**Issue by ozum** [jsdoc2md/jsdoc-to-markdown#162]
Hi,

Currently `@summary` tag only shows in the bottom of details.

Would it be possible
* give priority to `@summary` over `@description` in table of contents to show summary instead of long description.
* show summary at the top of details instead of bottom.

I did a drawing to summarize my message:
![drawing](https://user-images.githubusercontent.com/1497060/39955291-eea9ad1e-55d4-11e8-8bb8-934defd16a62.png)

Kind regards,

**Comment by 75lb** [comment]
Hi, you can customise the output... [instructions here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial)
