### ISSUE TITLE
Empty instance name / typicalname

### ISSUE THREAD

**Issue by vitalets** [jsdoc2md/jsdoc-to-markdown#166]
I'm creating a library that exports a single class. So it is obvious what instance is meaned in docs.
Is it possible to show only methods starting with dot?
E.g.:
### .resolve()
Resolves promise.

### .reject()
Rejects promise.

I tried to set `@typicalname` to empty string but it does not work.

**Comment by 75lb** [comment]
have a look at this page: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Cherry-picking-which-documentation-appears-in-output
