### ISSUE TITLE
.mjs support 

### ISSUE THREAD

**Issue by luwes** [jsdoc2md/jsdoc-to-markdown#169]
Are there any plans to support .mjs files?
I'm getting `JSDOC_ERROR: There are no input files to process.`

**Comment by 75lb** [comment]
Hi.. jsdoc2md uses jsdoc internally, which accepts `.js` files by default.. you can override this in the jsdoc config file (which you then pass to jsdoc2md using the `--configure` option) - [see here](https://github.com/jsdoc3/jsdoc/issues/1430).

**Comment by luwes** [comment]
Strange, it's not error-ing but `"docs": "jsdoc2md src/*.mjs -c jsdoc.config.js > API.md"` only outputs the docs of the first file in my `src` folder.
