### ISSUE TITLE
How to do a commonJS doc with 1 exports.default?

### ISSUE THREAD

**Issue by mesqueeb** [jsdoc2md/jsdoc-to-markdown#171]
This page was of great use. It works for me with named exports like so, but not with a single
`exports.default = index` export at the bottom.

https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-a-CommonJS-module-(exports)

Any advice greatly appreciated!

**Comment by 75lb** [comment]
First, ensure your source code documents correctly using [jsdoc](https://github.com/jsdoc3/jsdoc). If it documents correctly in jsdoc but not jsdoc2md, paste your code here so we can reproduce and debug it.

**Comment by mesqueeb** [comment]
@75lb It's not working in regular jsdoc, so I guess this is not the place to ask...
