### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pldg** [jsdoc2md/jsdoc-to-markdown#172]
I've installed jsdoc-to-markdown globally, open terminal in my project and run `jsdoc2md index.js` but nothing happen.

I've also tried to install jsdoc-to-markdown locally as stated in the [wiki](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-npm-run) and run this npm script `jsdoc2md index.js > api.md`, it output `api.md` but the file is empty.

The project in where I run those test is [sharp-image-processing](https://github.com/pldg/sharp-image-processing), as you can see [index.js](https://github.com/pldg/sharp-image-processing/blob/master/index.js) has some jsdoc comments inside, its seems like jsdoc-to-markdown doesn't recognize them.

Is this a bug or am I doing something wrong?

**Comment by 75lb** [comment]
read the jsdoc2md wiki pages on how to document a module - all modules must
start with a `@module` tag.. not a bug
