### ISSUE TITLE
One page per module + summary?

### ISSUE THREAD

**Issue by MisterTicot** [jsdoc2md/jsdoc-to-markdown#176]
That's not a issue but a question.

How can I create on page per module (each module has its own file) and have a kind of tabbed browsing such as what I did here: https://github.com/MisterTicot/sep-0007-bis/blob/master/README.md

The project I'd like to document is here: https://github.com/cosmic-plus/node-jsutils

P.S: I guess I could do my own script for that; I'm simply asking if there's already some building capability that could help here.

**Comment by 75lb** [comment]
Have a look at these pages

* https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class
* https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Cherry-picking-which-documentation-appears-in-output
