### ISSUE TITLE
export default class not working

### ISSUE THREAD

**Issue by darlenya** [jsdoc2md/jsdoc-to-markdown#177]
Hi, 
when I use the default key word when exporting a class the parser is not working as expected. When the 'default' key word is deleted, it works.

Example class:

```
/**
 * A great description
 *
 */
export default class DemoClass extends InterfaceDemo {
  /**
   * validate the loaded data.
   * @return errors {array} An array with all the errors found
   */
  validate() {
    return[]
  }

  /**
   * Executes the process
   */
  async process() {
    // Do great stuff
  }
}
```

**Comment by 75lb** [comment]
Hi, does your code document correctly using jsdoc directly? If it doesn't work in jsdoc it won't work in jsdoc2md either..

**Comment by darlenya** [comment]
Hi, your are right, in JSDoc directly it is also not working. I will open an issue there. Thanks. 
So I close this.
