### ISSUE TITLE
Error: spawn ENAMETOOLONG   on  Windows

### ISSUE THREAD

**Issue by zsmj1994** [jsdoc2md/jsdoc-to-markdown#178]
jsdoc2md src/modules/**/*.js
I've got an error `error: spawn ENAMETOOLONG`  on windows
macos works fine
when i have too many files the thing blows up.
Are there any solutions?

**Comment by 75lb** [comment]
This is a Windows OS issue, not a bug in jsdoc2md.. there's not much I can do, sorry.
