### ISSUE TITLE
security vulnerability in @4.0.1 with dmd > handlebars 

### ISSUE THREAD

**Issue by k-grube** [jsdoc2md/jsdoc-to-markdown#183]
```                       === npm audit security report ===                        
                                                                                
# Run  npm update handlebars --depth 3  to resolve 1 vulnerability
                                                                                
  High            Prototype Pollution                                           
                                                                                
  Package         handlebars                                                    
                                                                                
  Dependency of   jsdoc-to-markdown [dev]                                       
                                                                                
  Path            jsdoc-to-markdown > dmd > handlebars                          
                                                                                
  More info       https://npmjs.com/advisories/755   
```

**Comment by 75lb** [comment]
Just re-install jsdoc-to-markdown, yours is out of date. 

Besides, there is zero security threat anyway: jsdoc2md is an offline, local command-line tool, not a public-facing, always-on server exposed to attack.

**Comment by k-grube** [comment]
How did that work?  I had 4.0.1 installed.  Did uninstall, and install again and now it's not flagging the vulnerability.

**Comment by k-grube** [comment]
Sorry for the double post.

Thanks for looking into this so quickly.   I thought I had checked everything, was about to send a pull to update the dependencies on jsdoc2md/dmd, but I'm confused why your uninstall/install instructions actually worked.  I do understand that it's not a real vulnerability, just trying to get the warning message to go away from one of my libraries.
