### ISSUE TITLE
meta info

### ISSUE THREAD

**Issue by hz9527** [jsdoc2md/jsdoc-to-markdown#185]
doc info whitout meta info. I want to see where is the info.but getTemplateData can get meta info.

**Comment by 75lb** [comment]
I don't understand, please post an example of the meta info you expect to see.

**Comment by hz9527** [comment]
getTemplateData api can get doc from some file(meta info), but i can't get meta info in md.so can i use some options to ctrl ?
![Lark20190411-160049](https://user-images.githubusercontent.com/12823607/55940597-05371080-5c73-11e9-8f67-05bac49049f6.png)

**Comment by 75lb** [comment]
have a look at the Wiki pages about "customising output": https://github.com/jsdoc2md/jsdoc-to-markdown/wiki#customising-output

**Comment by 75lb** [comment]
I will close this as it's not an issue with jsdoc-to-markdown, however you are welcome to ask more questions.

**Comment by hz9527** [comment]
> have a look at the Wiki pages about "customising output": https://github.com/jsdoc2md/jsdoc-to-markdown/wiki#customising-output

ok, 3q. because i read code. & i found that, i should know about so many libs, like dma、handlerbars and so on. but i try use helper,but i don't kown how it's work.
i think i can hold it

**Comment by 75lb** [comment]
Yes, I understand. I agree, it should be more simple to customise the output. This will be improved in the future.
