### ISSUE TITLE
Allow for all modules without manually writing within the handlebars file

### ISSUE THREAD

**Issue by nwhite89** [jsdoc2md/jsdoc-to-markdown#19]
I am wanting to have multiple files (different modules) generate within a single markdown file. I'm not bothered about the ordering (alphabetical makes sense for this). In order to do this currently I will need to write

```
{{#module name="foo"~}}
  {{>body~}}
  {{>exported~}}
{{/module}}

{{#module name="bar"~}}
  {{>body~}}
  {{>exported~}}
{{/module}}
```

I think it would be better to allow for simply

```
{{>body~}}
{{>exported~}}
```

Having it when there is no module specified it outputs all of the JSDoc within the body ? or perhaps a set wrapper such as ``{{#module all}}``

**Comment by 75lb** [comment]
i wrote a quick example of how this is done in the new version: https://github.com/75lb/jsdoc-to-markdown/blob/next/example/identifier-blocks/modules.md

install and try it: 

```
$ npm install -g jsdoc-to-markdown@next
```

**Comment by nwhite89** [comment]
ah I see :+1: great @75lb thanks
