### ISSUE TITLE
Error: The partial docs could not be found

### ISSUE THREAD

**Issue by gfazioli** [jsdoc2md/jsdoc-to-markdown#192]
hi there, in my `package.json` I have

```js
... 
"build:utils": "jsdoc2md --files ./resources/assets/jsx/app/utils/*.ts* --configure ./jsdoc2md.json > ./resources/assets/jsx/docs/utils.md",
```
if I run by shell (MacOS, jsdoc2md v5.0.0)

```
$ jsdoc2md --files ./resources/assets/jsx/app/utils/*.ts* --configure ./jsdoc2md.json > ./resources/assets/jsx/docs/utils.md
```

all works fine, but if I run

```
$ yarn build:utils
```
I got

```
yarn run v1.17.0
$ jsdoc2md --files ./resources/assets/jsx/app/utils/*.ts* --configure ./jsdoc2md.json > ./resources/assets/jsx/docs/utils.md
Error: The partial docs could not be found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

any clue?

**Comment by 75lb** [comment]
do the docs generate ok using jsdoc?

**Comment by gfazioli** [comment]
I think so :D I mean, I installed just `jsdoc2md` by `yarn`

**Comment by 75lb** [comment]
jsdoc2md uses jsdoc internally - If your docs fail to generate using jsdoc, they will fail using jsdoc2md.. please check your docs generate correctly using jsdoc, thanks. If it fails, it's an issue with either your docs or jsdoc.

**Comment by gfazioli** [comment]
the doc is correctly generated by using 
```bash
$ jsdoc2md --files ./resources/assets/jsx/app/utils/*.ts* --configure ./jsdoc2md.json > ./resources/assets/jsx/docs/utils.md
```

it fails only when I use 

```shell
$ yarn build:utils
```

it seems related to `yarn` or package script, anyone got the same?

**Comment by linorabolini** [comment]
I got this error, jsdoc works for me. I checked all the source code and arrived to the DmD node package.

I checked the `partials` folder and I compared the one I have with the one in the repo.

The one in the repo *HAS* a `docs` folder. my node_modules doesn't have it. I think it might be related to yarn or some dependency lock. Will keep investigating.

**Comment by 75lb** [comment]
thanks for the workaround @linorabolini ..

closing as this is not an issue with jsdoc2md itself.
