### ISSUE TITLE
How to use options.name-format in render()?

### ISSUE THREAD

**Issue by julianguyen** [jsdoc2md/jsdoc-to-markdown#195]
The description for `name-format` in the [API docs](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoctomarkdown-) reads:
> Format identifier names in the code style, (i.e. format using backticks or <code></code>).

I'm uncertain as to how this param works.

**Comment by 75lb** [comment]
Hi, this flag formats identifier names in code blocks. 

With `--name-format`: 

## `globalFunction(one)` ⇒ <code>number</code>
a global function

**Kind**: global function
**Returns**: <code>number</code> - - returned value

| Param | Type | Description |
| --- | --- | --- |
| one | <code>number</code> | first param |

- - -

Without `--name-format`: 

## globalFunction(one) ⇒ <code>number</code>
a global function

**Kind**: global function
**Returns**: <code>number</code> - - returned value

| Param | Type | Description |
| --- | --- | --- |
| one | <code>number</code> | first param |

**Comment by 75lb** [comment]
I have updated the docs.
