### ISSUE TITLE
i get no docs

### ISSUE THREAD

**Issue by coderew** [jsdoc2md/jsdoc-to-markdown#196]
my js file content is:
```
export default {
  /**
   * @description minus
   * @param {Number} skuId
   * @param {Number} price
   * @param {Number} skuType
   * @return {Number} result
   */
  getJingBeanNum: function (skuId, price, skuType) {
  }
};
```

and i use the below js file to generate docs:
```
const fs = require('fs-extra');
const path = require('path');
const jsdoc2md = require('jsdoc-to-markdown');

jsdoc2md
  .render({
    files: path.resolve(process.cwd(), './test.js')
  })
  .then(x => {
    console.log("x----->", x);
    fs.outputFile(path.resolve(process.cwd(), './docs/README.md'), x);
  });
```

but i get noting docs,why

**Comment by 75lb** [comment]
read the docs: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)

**Comment by 75lb** [comment]
> 2. Given that jsdoc2md only generates markdown for documented identifiers and modules, you must document each identifier you want to appear in output - including the module. Therefore, you must use @module at the top of file to document the module.
