### ISSUE TITLE
The string '\001' crashes jsdoc "Octal literal in strict mode"

### ISSUE THREAD

**Issue by silverbucket** [jsdoc2md/jsdoc-to-markdown#197]
Trying to parse my index.js and jsdoc2md fails due to an offending line of code using an octal literal.

```
$ node_modules/.bin/jsdoc2md index.js > API.md
JSDOC_ERROR: ERROR: Unable to parse index.js: Octal literal in strict mode (309:24)
```

Line 309:
```js
      const message = '\001ACTION ' + job.object.content + '\001';
```

```
$ node_modules/.bin/jsdoc2md --version
5.0.0
```

**Comment by 75lb** [comment]
that's not an issue with jsdoc2md.. octal escape sequences [are deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal)

**Comment by AriartWt** [comment]
Just as a reference for those who struggles with that kind of error, you can convert an octal escape sequence to an hexadecimal escape sequence.

I needed this kind of escape to color CLI outputs in bash terminal. the \o033 can be converted to \x1B in my case.

It will output the same character, but JSDoc will not complain.
