### ISSUE TITLE
Unable to parse function receiving a functions array

### ISSUE THREAD

**Issue by gabmontes** [jsdoc2md/jsdoc-to-markdown#198]
I have a function that receives an array of functions like this:

```js
/**
 * @param {(() => any)[]} list An array of functions.
 */
function myFunction (list) {
  // function's code
}
```

When trying to parse it with `jsdoc2md`, I get the following error:

```
ERROR: Unable to parse a tag's type expression for source file test.js in line 1 with tag title "param" and text "{(() => any)[]} list An array of functions.": Invalid type expression "(() => any)[]": Expected ")" or "|" but "=" found.
```

What is the proper way of documenting the `list` parameter so `jsdoc2md` is able to parse it?

**Comment by 75lb** [comment]
Sorry, but I'm not sure.. this is a general jsdoc syntax question, please check the jsdoc documentation. If you find an issue specifically related to jsdoc2md, let me know thanks.
