### ISSUE TITLE
Splitting to multiple .md files with cli

### ISSUE THREAD

**Issue by DarrenPaulWright** [jsdoc2md/jsdoc-to-markdown#201]
Can I split my docs to multiple .md files with the cli? I couldn't find any documentation on this. I was hoping to do something like this in my package.json scripts:
```
jsdoc2md src/**/*.js > docs/*.md
```

Thanks!

**Comment by 75lb** [comment]
does [this example](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class) help?

**Comment by DarrenPaulWright** [comment]
Not really. I'd rather not have to copy a script to every library I publish to get this functionality. It would be great if it was built in to the cli.

**Comment by 75lb** [comment]
I don't plan to add that feature to the CLI at any time soon, sorry.. you don't need to copy a script into every library, you can write the script once, give it a [`bin` value in package.json](https://docs.npmjs.com/files/package.json#bin) then link it globally using `npm ln`.
