### ISSUE TITLE
Issue using jsdoc-http-plugin

### ISSUE THREAD

**Issue by xadamxk** [jsdoc2md/jsdoc-to-markdown#202]
I am attempting to use jsdoc-to-markdown to convert jsdoc to markdown, and inject the documentation for it at the bottom of a read me file.

I am trying to use the jsdoc-http-plugin because I would like to use the extra tags the library offers.

The npm/yarn script I am using to run it looks like this:
`jsdoc2md -c docs/jsdoc.json -t docs/README.hbs --files server.js > README.md`

jsdoc.json contents:
`{
    "source": {
        "include": [
            "server.js"
        ]
    },
    "plugins": [
        "jsdoc-http-plugin"
    ],
    "markdown": {
        "idIdHeadings": true
    }
}`

server.js contains the documentation I am parsing.

**The issue I am having is** that the jsdoc-http-plugin doesn't seem to be loading because the body tags for that plugin are not being parsed. I made an issue on this repository rather than that repository because I can't get any plugins to load, which I assume is my problem.

Would anyone help me be able to figure out why my plugins aren't loading?

**Comment by 75lb** [comment]
do the plugins load correctly when using them directly with the latest jsdoc?

**Comment by 75lb** [comment]
is this resolved or still an issue?

**Comment by xadamxk** [comment]
Sorry, I never got a notification for the first comment. No it doesn’t seem to be working with what’s on their master branch. Hmmm. I’ll work it out on their repo, thanks

**Comment by bionicles** [comment]
same issue
