### ISSUE TITLE
Can not create docs

### ISSUE THREAD

**Issue by speller** [jsdoc2md/jsdoc-to-markdown#203]
Hi, I'm trying to port my existing docs to the markdown format. I have the following `jsdoc` config:

```
{
    "tags": {
        "allowUnknownTags": true
    },
    "source": {
        "include": "src",
        "includePattern": "\\.?js$",
        "excludePattern": "(node_modules/|docs)"
    },
    "plugins": [
        "plugins/markdown",
        "node_modules/jsdoc-export-default-interop/dist/index"
    ],
    "opts": {
        "template": "node_modules/docdash",
        "encoding": "utf8",
        "destination": "docs/",
        "recurse": true,
        "verbose": true
    },
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": false
    }
}

```

My classes are located in `.mjs` files. `jsdoc` works fine with the following command and creates a number of documentation files:

```
$ yarn run jsdoc -c jsdoc.json app.mjs
yarn run v1.16.0
warning package.json: No license field
$ /mnt/c/develop/projects/pg/node_modules/.bin/jsdoc -c jsdoc.json app.mjs
Parsing /mnt/c/develop/projects/pg/app.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/AbstractDbObject.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/AbstractSchemaObject.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Attribute.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/ChangesContext.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Column.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/DataBase.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/ForeignKey.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Function.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Index.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/PrimaryKey.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Role.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Rows.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Schema.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Table.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Trigger.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/Type.mjs ...
Parsing /mnt/c/develop/projects/pg/src/db-classes/utils.mjs ...
Parsing /mnt/c/develop/projects/pg/src/loader.mjs ...
Parsing /mnt/c/develop/projects/pg/src/plugins/AbstractPlugin.mjs ...
Parsing /mnt/c/develop/projects/pg/src/plugins/PostgraphilePlugin.mjs ...
Parsing /mnt/c/develop/projects/pg/src/psql.mjs ...
Parsing /mnt/c/develop/projects/pg/src/utils.mjs ...
Generating output files...
Finished running in 1.10 seconds.
Done in 1.26s.
```

But when I'm trying to run jsdoc2md with the same parameters I'm getting absolute nonsense:

```
$ yarn run jsdoc2md -c jsdoc.json app.mjs
yarn run v1.16.0
warning package.json: No license field
$ /mnt/c/develop/projects/pg/node_modules/.bin/jsdoc2md -c jsdoc.json app.mjs
<a name="buildChanges"></a>

## buildChanges(prevState, curState, prevVersion, curVersion) ⇒ <code>array</code>
Compare old and current states and return changes object with differences

**Kind**: global function

| Param |
| --- |
| prevState |
| curState |
| prevVersion |
| curVersion |

Done in 0.30s.
```

1. All files in the `src` folder are ignored. Only the app.mjs file is processed.
2. The `docs` folder is empty. But I need documentation files to be created there.
3. Docs are printed to stdout. Why? If it is supposed to save the output to an `.md` file, it also will contain the `yarn` command output, which is unacceptable. Also, I prefer having multiple MD files instead of a single one.
4. It seems like some options in the jsdoc.json configuration file are ignored. At least, `source.include`, `opts.destination`. And I didn't find any documentation which options are effective which not. I also didn't find any CLI options documentation.

How to make this command ` yarn run jsdoc2md -c jsdoc2.json app.mjs` working as expected, same as `jsdoc`?

**Comment by 75lb** [comment]
1. Because you only passed `app.mjs` as input to jsdoc2md. Supply all the files you want to document e.g. `src/*.mjs`.
2. The jsdoc configuration file is passed directly to jsdoc and not read or consumed by jsdoc2md.
3. Stdout is the default output stream, you need to pipe that output to a file. 
4. See answer 2. Jsdoc and jsdoc2md are two completely different tools with different APIs, authors and behaviour. There are some CLI option docs [here](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md) and under `jsdoc2md --help`. Also, the wiki has some docs.

> How to make this command yarn run jsdoc2md -c jsdoc2.json app.mjs working as expected, same as jsdoc?

This [wiki page](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class) gives an example of how to use jsdoc2md programmatically to achieve "one output file per class".

**Comment by speller** [comment]
@75lb 
1. This doesn't work:
```
$ yarn run jsdoc2md src/*.mjs
yarn run v1.19.1
$ xx/node_modules/.bin/jsdoc2md 'src/*.mjs'
JSDOC_ERROR: These files do not exist: src/*.mjs
error Command failed with exit code 1.
```
What I'm doing wrong here? The example from the wiki page also doesn't work (https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-npm-run)

**Comment by 75lb** [comment]
there seems to be an issue with `yarn run`, it has also been reported [here](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/192). I don't use yarn will take a look into it. If you figure out why `npm run` works but `yarn run` does not, let me know. 

Jsdoc2md supports standard bash [pattern matching](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Pattern-Matching), which includes the `!(pattern-list)` exclusion syntax. For example, operate on all directories except `node_modules` and `__tests__`:


```
$ renamer -d --find pic --replace photo "!(node_modules|__tests__)/**"
```

**Comment by speller** [comment]
Thanks for the pattern mentioning. But I still have many difficulties. Could you check my repository https://github.com/dbascode/dbascode and help me to fix docs generation issues, please? The autogenerated docs are here: https://github.com/dbascode/dbascode/blob/master/API.md . Docs generation is run by the script command `api-docs`

1. Some classes are missed. Example: `AbstractDbObject`, `Column`.
2. Some entries are duplicated: `TREE_INITIALIZED`, `processCalculations`, `PostgreSqlPlugin.init`
3. Strange section "Members".
4. Tests are not excluded: `Jest` is still in the docs while I've used the following pattern: `./src/**/!(__tests__)/*.mjs`.

**Comment by speller** [comment]
I even tried this command: `yarn run jsdoc2md --files "./src/dbascode/AbstractDbObject.mjs" > API4.md` but it creates a file with a lot of classes **except** `AbstractDbObject`. Why so?

**Comment by 75lb** [comment]
> Could you check my repository

Before I do this, could you please confirm your docs generate correctly using [jsdoc](https://github.com/jsdoc/jsdoc). Jsdoc2md uses jsdoc internally, so if your docs are broken in jsdoc they will be broken in jsdoc2md.

**Comment by zababurinsv** [comment]
My *.mjs files not work too

jsdoc compiled this file
```
jsdoc  -c jsdoc.docs.json -r server_books.mjs -d ./test.md
```

Not compiled this file
```
jsdoc2md -c jsdoc.api.json --files server_books.mjs > API.md 
```

But compiled this file

```
Not compiled this file
```
jsdoc2md -c jsdoc.api.json --files server_books.js > API.md 
```
```
