### ISSUE TITLE
No docs created for `export default function test () {}`

### ISSUE THREAD

**Issue by PascalSalesch** [jsdoc2md/jsdoc-to-markdown#207]
Hey,

the following doc results in an empty output,
using the `jsdoc2md`-cli

```
/**
 * Main function.
 *
 * @param {object} options - Options.
 */
export default function main ({ a }) {
}
```

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)

**Comment by PascalSalesch** [comment]
grazie, sorry.
