### ISSUE TITLE
[FEATURE REQUEST] : Output from CLI

### ISSUE THREAD

**Issue by anikethsaha** [jsdoc2md/jsdoc-to-markdown#208]
_Please ignore this issue if this already exists. or close it by telling how to do it as I couldn't find it in the docs_

Motivation
---
It is really a great tool for quick `.md` files generation using CLI at a single command.
But I feel a bit of work is that we need to copy-paste the current markdown rendered from the CLI to our files. (At least that's how I did )

Current
---
The CLI is just rendering the markdown generated from the core API

Feature
---
Simply a new output flag `--output` which will create a `.md` file with the name same as the input `.js` file and the rendered markdown will be written in it

I would be happy to do this in the core if this is accepted. 

Alternate
---
There are few packages which are using this package as dep and generating the `.md` files but those are not clear to me ( at least the usage ).
So alternatively I will be creating CLI for the same 

Thanks for the great tool

**Comment by DigitalBrainJS** [comment]
This is not necessary. This is a cli tool, so it works with pipelines, and you just need to redirect its output from the console to some file. 
jsdoc2md index.js> API.md
or in a case of hbs template:
jsdoc2md -t jsdoc2md/README.hbs index.js > README.md
You can read more about this here: https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file

**Comment by anikethsaha** [comment]
THanks a lot ! this is the perfect solution. 
I didnt check this source code and though it was a console.log but I think its stdout write!
