### ISSUE TITLE
@this tag is not supported

### ISSUE THREAD

**Issue by mdreizin** [jsdoc2md/jsdoc-to-markdown#21]
It looks like that `@this` is not supported. Please see http://usejsdoc.org/tags-this.html

**Comment by 75lb** [comment]
it is supported in the next version.. please see the instructions at the top of the README (https://github.com/75lb/jsdoc-to-markdown) and install the next version.. let me know if it fixes your issue

**Comment by 75lb** [comment]
this is supported in the latest version, see [here](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/tags/this)
