### ISSUE TITLE
import typedef from another file with import not work

### ISSUE THREAD

**Issue by baanloh** [jsdoc2md/jsdoc-to-markdown#212]
The following jsdoc return an error :

```jsdoc
@returns {Promise<import('sqlite3').RunResult>}
```

the error :

`
JSDOC_ERROR: ERROR: Unable to parse a tag's type expression for source file * in line 46 with tag title "returns" and text "{Promise<import('sqlite3').RunResult>}": Invalid type expression "Promise<import('sqlite3').RunResult>": Expected "!", ",", "=", ">", "?", "[]", or "|" but "(" found.
`

**Comment by 75lb** [comment]
Hi, jsdoc2md uses jsdoc internally. This is a jsdoc issue, please report it on the [jsdoc repo](https://github.com/jsdoc/jsdoc/issues).

In general, if you have an issue please first ensure your code works correctly with jsdoc directly. It must work in jsdoc before it will work in jsdoc2md.

**Comment by gabmontes** [comment]
For those looking for a workaround until `jsdoc` properly manages `import()`, see https://github.com/jsdoc/jsdoc/issues/1537#issuecomment-768290233.

**Comment by KaKi87** [comment]
@gabmontes Local imports may work but non-local ones don't.
