### ISSUE TITLE
Where is output?

### ISSUE THREAD

**Issue by skeddles** [jsdoc2md/jsdoc-to-markdown#214]
I run "./node_modules/.bin/jsdoc2md --source src/index.js", i get the following two lines of output, and don't see any generated files anywhere.

> game@1.0.0 jsdoc2 Y:\Projects\game
> jsdoc2md --source src/index.js

I am trying to generate an MD file for index.js. Where is it? 

--help doesn't say anything about output, and I can't find it in the wiki

**Comment by 75lb** [comment]
You need to use `jsdoc2md --files *.js` or just `jsdoc2md *.js`.

`--source` is for passing a string of source code, e.g. `jsdoc2md --source "const example = 1"`

**Comment by skeddles** [comment]
I tried that but it just prints in the console and doesn't generate any files

**Comment by AFIDclan** [comment]
> I tried that but it just prints in the console and doesn't generate any files

This seems to happen if you don't have file summary at the top of the file.
