### ISSUE TITLE
Export default prevents constructor from being shown and it becomes just functions, without a class

### ISSUE THREAD

**Issue by D-Marc1** [jsdoc2md/jsdoc-to-markdown#216]
Doing the following doesn't work.

```js
export default class myClass {
  constructor(param) {}
  myMethod(){}
}
```

What ends up happening is jsdoc2md thinks `myMethod()` is a standalone function, not inside of a class. It only works if I remove `export default` right before I generate the docs. I can confirm this doesn't happen in regular jsdoc also.

**Comment by 75lb** [comment]
this issue is documented here
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)

**Comment by D-Marc1** [comment]
My apologies! I didn't see that when I tried to google my question for some reason.

It looks like it's working for me now, though now the section top is `modules`, instead `classes`, and everything is prefixed with `modules`. I think I almost prefer the format that I had previously, which was a result of just removing `export default` right before I run `jsdoc2md`.

Anyway, thanks again for the response! I will close this so it's not cluttering your issues, as there's already an answer to this.
