### ISSUE TITLE
{>member-index~}} not producing a member index if module has only one member

### ISSUE THREAD

**Issue by laumair** [jsdoc2md/jsdoc-to-markdown#217]
Facing an issue similar to https://github.com/jsdoc2md/jsdoc-to-markdown/issues/34 with the following template:

```
{{#module name="extract-json"~}}
    {{>body~}}
        {{>member-index~}}
        {{>members~}}
{{/module~}}
```

I tried fixing it with [this](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/34#issuecomment-163299400) solution but doesn't seem to work.

**Comment by 75lb** [comment]
By default, a minimum of 2 members is required for a member-index to print.

To change the minimum to 1, create a file called `.jsdoc2md.json` in your project folder with this content: 

```
{
  "memberIndex": {
    "minDescendants": 1
  }
}
```

Then generate the docs again.

**Comment by laumair** [comment]
@75lb Works fine, thanks!
