### ISSUE TITLE
Error: Expected "|" but "&" found

### ISSUE THREAD

**Issue by VasilevVitalii** [jsdoc2md/jsdoc-to-markdown#218]
error when i generate .md file from this code:

```javascript
/**
 * @typedef type1
 * @property {string} p1
 */
/**
 * @typedef type2
 * @property {string} p2
 */
/**
 * @typedef {type1 & type2} type3
 */
/** @type {type3} */
let a = undefined
```

**Comment by 75lb** [comment]
Please check this works correctly in jsdoc.. if it doesn't work in jsdoc, it's not as issue with jsdoc2md.. 

Shouldn't this:

```js
/**
 * @typedef {type1 & type2} type3
 */
```

be this?

```js
/**
 * @typedef {type1 | type2} type3
 */
```

**Comment by wmertens** [comment]
`type1 & type2` is different from `type1 |  type2`. It means both types apply at the same time. Typescript is happy with the jsdoc tag.

**Comment by wmertens** [comment]
Indeed, `jsdoc -X file.js >/dev/null` shows errors. Not a bug with jsdoc2md.

**Comment by wmertens** [comment]
I created https://github.com/jsdoc/jsdoc/issues/1898
