### ISSUE TITLE
No way to make a constructor private.

### ISSUE THREAD

**Issue by dtjohnson** [jsdoc2md/jsdoc-to-markdown#22]
This tool is fantastic. I love it already. However, I have a couple classes with constructors I'd consider "private". I want to exclude them from documentation since they shouldn't be called by the user. If I mark the constructor documentation with @private, however, it treats the whole class as private and ignores it.

Is there anyway to ignore a constructor?

**Comment by 75lb** [comment]
pleased you like it! Which version are you using, the current stable release (0.5.11) or @next (0.6.4)?

hmm, interesting conundrum.. in jsdoc, if you mark a class as `@private` then there is no way to distinguish whether you intended the whole class or just the constructor to be private.. so you think making this separation would be useful? I'd need a new tag, something along the lines of @constructorprivate

**Comment by dtjohnson** [comment]
I'm using @next. You can see my documentation here:
https://github.com/dtjohnson/xlsx-populate

The constructors for Sheet and Cell shouldn't be called directly by the user. They are instantiated by the Workbook methods.

Yeah, it's an interesting issue. I looked around for the proper way to do this in JSDoc and it doesn't seem to exist.

**Comment by 75lb** [comment]
not sure of your particular criteria but do you have a case to use a [creational pattern](http://en.wikipedia.org/wiki/Creational_pattern) to abstract away the details of Sheet and Cell construction? 

Maybe use a factory pattern, in the same vein as the native JS factory method `Object.create`

**Comment by dtjohnson** [comment]
I'm not sure that helps me. The code is fine. I don't need to forbid the use of the constructor. Just don't want it in the documentation since it shouldn't normally be used by a consumer. (In fact, it would be tough since those classes aren't exposed directly.) I just want a way to opt-out the constructor from the docs.
