### ISSUE TITLE
Only generating documentation from global functions

### ISSUE THREAD

**Issue by alystair** [jsdoc2md/jsdoc-to-markdown#220]
I have a handful of global functions which are in the process of being moved to our master object. That being said, when I attempt generating markdown, only the global functions are being rendered. I've checked --namepaths and see them being listed (`pd.HOOKABLE.exec`, `pd.DOM.elementTitle` etc) - how do I make it work specifically for the `pd` sub-object functions?

**Comment by 75lb** [comment]
As described [in the wiki](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)), for a sub-object to appear in the documentation it must have a doclet, and all levels above it must have docs too.. 

Did you resolve this?

**Comment by alystair** [comment]
These aren't modules, just functions within objects within objects. I solved it by adding a matching `@namespace` at the start of the script.

**Comment by alystair** [comment]
This might be something to add to the jsdoc2md documentation/FAQ. Your discretion to close since I solved it.

**Comment by 75lb** [comment]
> I solved it by adding a matching `@namespace` at the start of the script.

Yes, this is what I was suggesting - for a documented nested identifier (property/method etc) to appear in the output, its parent namespace/class must be documented too.. also, if the file is a module it must be a `@module` tag.. if it's not a module, all top level identifiers will be marked as `global`..
