### ISSUE TITLE
How to getJsdocData from string content?

### ISSUE THREAD

**Issue by daolou** [jsdoc2md/jsdoc-to-markdown#221]
#### example: 
```js
const codeStr = `
/**
 * @description demo
 */
function fn(){
  console.log(1111)
}
`

// TODO: getJsdocData from codeStr
```

**Comment by 75lb** [comment]
See the `[options.source]` parameter to pass source code as a string into `jsdoc2md.getJsdocData`:
https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgetjsdocdataoptions--promise
