### ISSUE TITLE
如何更改class 生成的标题

### ISSUE THREAD

**Issue by LiuWeiMr** [jsdoc2md/jsdoc-to-markdown#222]
class 方法生成的标题包含：类前缀、方法名、返回结果，例如：

`### signal.sendBroadcastMessage(moduleId, data, [options]) ⇒ [<code>Promise.&lt;PromiseReturn&gt;</code>](#GlobalVariable.PromiseReturn)`

如何更改生成结果，使用自定义的标题，期望将上边的结果为：
`### 发送透传广播消息的接口`

**Comment by 75lb** [comment]
Hi, could you write in English please? I translated your message, maybe you need to customise one or more of the partials: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial
