### ISSUE TITLE
@linkcode not recognized?

### ISSUE THREAD

**Issue by cszach** [jsdoc2md/jsdoc-to-markdown#223]
Hi!

I'd like to begin by saying that jsdoc-to-markdown is a great tool that I've been using for quite some time now.

I recently started using more JSDoc tags and found out that the `@linkcode` tag is not recognized by jsdoc2md. The `@link` tag is still picked up, but not `@linkcode`. Is there any reason for not supporting it or maybe you just haven't considered it yet?

I'd love it if jsdoc2md can integrate `@linkcode` into its family of recognized tags. Could you?

Thank you very much. :heart:

**Comment by 75lb** [comment]
Support for `@linkcode` was [merged recently](https://github.com/jsdoc2md/dmd/issues/85) and will be in the next version of jsdoc-to-markdown.. in the meantime, you can test the prerelease if you like where you can find the support: 

```
npm install jsdoc-to-markdown@next
```
