### ISSUE TITLE
How do I document dynamic generated methods? Is name tag supported?

### ISSUE THREAD

**Issue by DigitalBrainJS** [jsdoc2md/jsdoc-to-markdown#225]
I'm trying to document a dynamic generated method, so I use `name` tag for this, but it doesn't generate any namepaths/documentation. 
```javascript
class Animal{
    /**
     * Creates a new animal instance
     */
    constructor() {
    }

    /**
     * foo method
     */
    foo(){}

    /**
     * @name Animal#bar
     * @function
     * @memberof Animal
     * @description test
     * @param {number} x
     * @returns {boolean}
     */
}
```
jsdoc2md --namepaths index.js
````
{
  "module": [],
  "class": [
    "Animal"
  ],
  "constructor": [
    "Animal"
  ],
  "mixin": [],
  "member": [],
  "namespace": [],
  "constant": [],
  "function": [
    "Animal#foo" // Animal#bar is missing
  ],
  "event": [],
  "typedef": [],
  "external": []
}
````
But my IDE recognizes the method correctly:
![image](https://user-images.githubusercontent.com/12586868/95752284-757b8380-0ca8-11eb-959b-e0f9d91af0ce.png)

**Comment by 75lb** [comment]
Hi, does this work as expected when generating docs directly using jsdoc?

**Comment by 75lb** [comment]
Also, make sure you have a `@module` defined at the top: [read this](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export))
