### ISSUE TITLE
Can we use conf.json file ?

### ISSUE THREAD

**Issue by mkubdev** [jsdoc2md/jsdoc-to-markdown#226]
I'm trying to use jsdoc configuraiton file to allow the generation sorted alphabetically, but the output is corrupted...

* my conf.json :
```json
{
    "tags": {
        "allowUnknownTags": true
    },
    "source": {
        "includePattern": ".+\\.js(doc)?$",
        "excludePattern": "(^|\\/|\\\\)_"
    },
    "plugins": [],
    "opts": {
        "encoding": "utf8",
        "lenient": false,
        "sort": true 
    }
}
```

* I call jsdoc2md with -c parameter :
`jsdoc2md -c jsdoc_conf.json apimastercommand.js > test4.md`

This is a standard configuration file from JSDOC3. When i set `sort` to `true`, this doesn't work. Is there any way to order members alphabetically ?

**Comment by 75lb** [comment]
Hi, i'm not sure why your jsdoc sort config is not working - does it work when using jsdoc directly? 

To take control and sort results manually, see [this wiki page](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class) for an example on how to use the jsdoc2md API. You could use similar code, except you would need to sort `templateData` to your taste before passing it into `jsdoc2md.renderSync`.

**Comment by mkubdev** [comment]
@75lb Hi! Thank you for the [wiki page](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class). I can't get it work from scratch with CLI + config file, but it's working with custom sorting code from the api. Have a good day :)
