### ISSUE TITLE
JSDoc Error while parsing typescript

### ISSUE THREAD

**Issue by PythonCreator27** [jsdoc2md/jsdoc-to-markdown#227]
I am not sure whether or not to post this on the `jsdoc` repo or this one, so apologies in advance.
I get the following error when I try to parse a typescript file:
```
JSDOC_ERROR: ERROR: Unable to parse C:\advaiyalad\programming\javascript\Projects\regex-js\src\RegexTester.ts: Unexpected reserved word 'private' (6:16)
```
I can see that JSDoc is picking up `private` as a reserved keyword, but I am using it like regular in typescript:
```typescript
export class SomethingHere {
    // fields and methods not shown to save space
    constructor(private regex: RegExp) {}
}
```
This is a regular typescript 'hack'.
Why is JSDoc giving me this error, and is there a way to fix it?

jsdoc2md config file (`jsdoc2md.json`):
```json
{
    "source": {
        "includePattern": "\\.ts$",
        "excludePattern": "\\.(test|spec).ts"
    },
    "plugins": ["plugins/markdown", "node_modules/jsdoc-babel"]
}
```

Babel config:
```jsonc
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "12",
                    "chrome": "60",
                    "ie": "11",
                    "firefox": "60",
                    "edge": "12",
                    "opera": "60",
                    "safari": "12"
                }
            }
        ],
        "@babel/preset-typescript"
    ]
}
```

Doc build script in `package.json`:
```json
{
        "build:doc": "jsdoc2md --files ./src/*.ts --configure ./jsdoc2md.json > file.md"
}
```

<details>
<summary>Version and Platform Info</summary>
OS: Windows 10 Home<br>
Build number: 19041<br>
System type: x64<br>
Terminal emulator: VSCode's built in terminal<br>
Terminal program: Git Bash (Git v2.29.2.windows.2)<br>
`jsdoc-to-markdown` version: 6.0.1<br>
`jsdoc-babel` version: 0.5.0<br>
</details>

**Comment by 75lb** [comment]
jsdoc2md use jsdoc internally to parse the code - first ensure your code documents correctly using jsdoc directly.. does jsdoc work correctly with your code?

**Comment by PythonCreator27** [comment]
Sorry, the problem was that `babel` wasn't being run. I had to add the `babel.extensions` array to make babel parse the files.
