### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by ddnn55** [jsdoc2md/jsdoc-to-markdown#233]
I'm probably doing something wrong. Why do I get no output on this file?
https://github.com/ddnn55/daylight/blob/6d184e7e8ef86c469085a1e5decdb4c983ee6f42/src/main.js

```
$ ./node_modules/.bin/jsdoc2md --source src/main.js
$
```

**Comment by 75lb** [comment]
read this https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export)
