### ISSUE TITLE
How to generate custom property? (eg. @feedback)

### ISSUE THREAD

**Issue by alystair** [jsdoc2md/jsdoc-to-markdown#238]
I made a `feedback.hbs` file, using a slightly modified version of `customElement.hbs`, then added `{{>feedback~}}` into `body.hbs` and finally added `feedback.hbs` to the partial options list when running the script... what am I missing?

**Comment by 75lb** [comment]
You can use any arbitrary custom tag, e.g. this code

```
/**
  * this function has a wonderful custom tag
  * @createdIn Nigeria
  */
function customTaggedFunction () {}
```

renders this: 

```
## customTaggedFunction()
this function has a wonderful custom tag

**Kind**: global function  
**Createdin**: Nigeria  
```

Regarding your specific case, if it is failing and you have followed the [wiki guide](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial), then please post something I can run and reproduce to see and debug the issue first hand..

**Comment by alystair** [comment]
I'm aware of default `customElement`, this is what I did:

1. created `feedback.hbs` (used customElement as starting point)
```hbs
{{#if feedback}}{{#each feedback}}**Provide {{titleCase tag}}** via {{#with (parseType value)~}}
{{#if type}}{{>link to=type}}{{/if}}{{#if description}}{{{inlineLinks description}}} issue thread{{/if}}{{/with}}  
{{/each}}{{/if~}}
```
2. added `{{>feedback~}}` into own copy of `body.hbs`
3. added some `@feedback [issue name](https://example.com/)` to JSDOC
4. Ran `npx jsdoc-to-markdown --partial docs/body.hbs docs/feedback.hbs docs/docs.hbs --files assets/pagedriver.js > docs/reference-core.md`

and they all render as a basic customElement, ignoring feedback.hbs...

**Comment by 75lb** [comment]
ok, good.. so is this issue resolved?

**Comment by alystair** [comment]
..no? Please see final sentence in my response. `@feedback` is being rendered as default customElement and ignoring feedback.hbs

**Comment by 75lb** [comment]
to save some time could you post a reproduction case i can run, see failing and debug.. a gist would ideal, something i can quickly checkout and debug..

**Comment by alystair** [comment]
Sure thing, will do so in an hour or so once I'm in front of a computer 👍

**Comment by alystair** [comment]
https://gist.github.com/alystair/96ece3b9ca2027bf8b44de70cd2fc54f

**Comment by 75lb** [comment]
thanks..  use the `--json` flag to print the data object that is passed into the dmd handlebars template:

```
$ npx jsdoc2md test.js --json

[
  {
    "id": "customTaggedFunction",
    "longname": "customTaggedFunction",
    "name": "customTaggedFunction",
    "kind": "function",
    "scope": "global",
    "description": "This function has a wonderful custom tag",
    "params": [],
    "customTags": [
      {
        "tag": "feedback",
        "value": "https://github.com/jsdoc2md/jsdoc-to-markdown/issues/238"
      }
    ],
    "meta": {
      "lineno": 5,
      "filename": "test.js",
      "path": "/Users/lloyd/Documents/tmp/96ece3b9ca2027bf8b44de70cd2fc54f"
    },
    "order": 0
  },
  {
    "id": "customTaggedFunction2",
    "longname": "customTaggedFunction2",
    "name": "customTaggedFunction2",
    "kind": "function",
    "scope": "global",
    "description": "Text link",
    "params": [],
    "customTags": [
      {
        "tag": "feedback",
        "value": "[Text link](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/238)"
      }
    ],
    "meta": {
      "lineno": 11,
      "filename": "test.js",
      "path": "/Users/lloyd/Documents/tmp/96ece3b9ca2027bf8b44de70cd2fc54f"
    },
    "order": 1
  }
]
```

You can see in the above json your custom `@feedback` tags are passed into dmd via the `customTags` property, which is an array. So your `feedback.hbs` custom partial needs to loop `customTags` (not `feedback`).

```hbs
{{#if customTags}}{{#each customTags}}**Provide {{titleCase tag}}** via {{#with (parseType value)~}}
{{#if type}}{{>link to=type}}{{/if}}{{#if description}}{{{inlineLinks description}}} issue thread{{/if}}{{/with}}
{{/each}}{{/if~}}
```

**Comment by alystair** [comment]
AHA! Ok. I guess in this situation, I must remove `{{>customTags~}}` from `body.hbs` because these custom tags duplicate there - but this means all other non-customized tags won't be generated?

**Comment by alystair** [comment]
Hrm it seems if I have multiple custom tags, each one gets rendered as the other (ex. I make another partial for `@aka` tag)...

**Comment by 75lb** [comment]
you could cherry-pick from the customTag array via path expressions:
https://handlebarsjs.com/guide/expressions.html#literal-segments

Or if you loop over the customTags with `{{#each}}` you could make a decision on what gets rendered with an `{{#if}}`..

Might be easier to write a JS helper, rather than complex handlebars partials.. see here
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin
