### ISSUE TITLE
One .md-file per .js-file

### ISSUE THREAD

**Issue by phun-ky** [jsdoc2md/jsdoc-to-markdown#24]
I see this code here:

    var jsdoc2md = require("jsdoc-to-markdown");
    var gutil = require("gulp-util");
    var fs = require("fs");
     
    gulp.task("docs", function(done){
        var src = "lib/**/*.js";
        var dest = "api.md";
        var options = {};
        
        gutil.log("writing documentation to " + dest);
        jsdoc2md.render(src, options)
            .on("error", function(err){
                gutil.log(gutil.colors.red("jsdoc2md failed"), err.message);
            })
            .pipe(fs.createWriteStream(dest));
    });

And I am trying to make the given code produce one `.md`-file per `.js`-file.. and so far no luck.. basically, I want this behaviour:

    gulp.task("docs", function(){

      var src   = 'docstarget/**/*.js';
      
      return  gulp.src(src)
                .pipe(jsdoc2md.render())
                .on("error", function(err){
                  gutil.log(gutil.colors.red("jsdoc2md failed"), err.message);
                })
                .pipe(rename(function(path){
                  path.extname = '.md'
                }))
                .pipe(gulp.dest('doxify'));
                
    });

But that code gives me:

    jsdoc2md failed Invalid non-string/buffer chunk

How can I achieve what I want? I am using `@module`-tag, so I cant use the gulp plugin..

I am using this version: `"jsdoc-to-markdown": "^0.5.11",`, getting same result in `"jsdoc-to-markdown": "^0.6.4",`

**Comment by phun-ky** [comment]
Found a way now, but it's nasty:

    gulp.task("docs", function(){

      var src   = 'docstarget/**/*.js';

      return  gulp.src(src)
                .pipe(tap(function(file){
                  fs.createReadStream(file.path)
                  .pipe(jsdoc2md.render())
                  .pipe(fs.createWriteStream(file.path.replace(/.js/g,'.md')));
                }))
                .on("error", function(err){
                  gutil.log(gutil.colors.red("jsdoc2md failed"), err.message);
                });


    });

**Comment by 75lb** [comment]
hi, will look into this when i get a moment but i notice you're missing a return statement.. 

in the example [here](https://github.com/75lb/jsdoc-to-markdown#as-a-gulp-task) notice it is `return jsdoc2md.render(src, options)` - your code above lacks the `return`.. does adding it help in your case?

**Comment by phun-ky** [comment]
No, that does not help :/

**Comment by 75lb** [comment]
hi! You should no longer need this hack, or the custom gulp task.. the latest plug-in version should just work, meaning you can use [this method](https://github.com/jsdoc2md/gulp-jsdoc-to-markdown#one-markdown-file-out-per-source-file-in) to get "one markdown out per js in".. make sure you adhere to the caveat mentioned on the plugin docs.. let me know how it goes..

**Comment by 75lb** [comment]
inactive, assuming resolved..
