### ISSUE TITLE
Class Functions aren't documented in TypeScript

### ISSUE THREAD

**Issue by dmccormack3** [jsdoc2md/jsdoc-to-markdown#241]
I've followed the wiki page for how to document Typescript, and it compiles without any console errors. My project is a number of Angular Service Classes. The documentation from the classes is output but the individual class functions are missing. Here is a snippet from my code:

```
/**
 * Class for the user (this doc is output)
 * @hideconstructor
 */
@Injectable()
export class CurrentUserApiService{

    /**
     * Gets the object containing the users details (this isn't output)
     * @returns  The users current details
     */
    private getUserDetails = () : any => {
        return [];
    }
}
```

### jsdoc2md.json

```
{
  "source": {
    "includePattern": ".+\\.service.ts?$",
    "excludePattern": ".+\\.(test|spec|module).ts"
  },
  "plugins": [
    "plugins/markdown",
    "node_modules/jsdoc-babel"
  ],
  "babel": {
    "extensions": ["ts", "tsx"],
    "ignore": ["**/*.(test|spec).ts"],
    "babelrc": false,
    "presets": [["@babel/preset-env", { "targets": { "node": true } }], "@babel/preset-typescript"],
    "plugins": [
      ["@babel/plugin-proposal-decorators", {"legacy": true}],
      ["@babel/proposal-class-properties", { "loose" : false }]
    ]
  }
}
```

### Npm Script

 `   "apiDocs": "jsdoc2md --files ./api/current-user/currentUser-api.service.ts --configure ./apiDoc2md.json > ./apidocs/docs/apidocs.md",`

**Comment by 75lb** [comment]
i know very little about Typescript, personally I have never used it (no need).. did you get this working? Do the docs generate correctly is jsdoc? Does the `jsdoc2md --json` command all the tempate input data you expect to see?

**Comment by dmccormack3** [comment]
Never got this working. Have moved away from using this tool for now. The documentation generates as expected in jsdoc.

**Comment by 75lb** [comment]
ok.. closing this issue as stale.

**Comment by dmccormack3** [comment]
Why has this been closed as stale? The issue was never resolved.

**Comment by dmccormack3** [comment]
@75lb Any update on this?

**Comment by 75lb** [comment]
Hi.. it was closed as stale because there is not enough information here for me to quicky reproduce the issue, plus you had moved on and no-one else had reported the issue before or since.. 

Could you do me a favour please - post a fully-functional reproduction case that either myself or another user can run to see the issue and debug it.. that would help speed things up.. a gist or dummy repo along with reproduction steps (commands to run).. thanks!
