### ISSUE TITLE
Enhancement: include JSDocs' --package package.json option

### ISSUE THREAD

**Issue by LeadDreamer** [jsdoc2md/jsdoc-to-markdown#250]
JSDocs has the  ```-P/--package the/path/to/package.json``` option, so it can get various data (dates, authors, version) from package.json.

This does NOT seem to be present in jsdocs2md - or at least, both -P and --p generate an error as not recognized.

https://jsdoc.app/about-including-package.html

I would *very much* like to have this as part of my documentation.

**Comment by 75lb** [comment]
according to the link you shared, you can include the `package.json` file in the list of input files:

```
$ jsdoc path/to/js path/to/package/package.json
```

Does that not work with jsdoc2md too?

**Comment by LeadDreamer** [comment]
That is my entire point - it DOES NOT work with jsdoc2md.

**Comment by 75lb** [comment]
I would expect it to work as jsdoc2md using jsdoc internally - the input files passed into jsdoc2md are passed directly to jsdoc.. I will have a look

**Comment by 75lb** [comment]
Could you do me favour please and share a simpe reproduction case which I can run to see this working in jsdoc? I will then use the case to debug why it doesn't work in jsdoc2md..

**Comment by LeadDreamer** [comment]
I expected precisely that - but multiple attempts in different formats and order all failed.

**Comment by LeadDreamer** [comment]
Example - this script works:
```
    "docs": "./node_modules/.bin/jsdoc2md --template ../README.hbs --files *.js > README.md"
```
This script fails:
```
    "docs": "./node_modules/.bin/jsdoc2md --template ../README.hbs --package package.json --files *.js > README.md"
```

with messages
```
> jsdoc2md --template ../README.hbs --package package.json --files *.js > README.md

UNKNOWN_OPTION: Unknown option: --package
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @1.0.6 docs: `jsdoc2md --template ../README.hbs --package package.json --files *.js > README.md`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @1.0.6 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2021-06-11T21_34_44_395Z-debug.log
```

**Comment by LeadDreamer** [comment]
I ran
```
    "docs": "./node_modules/.bin/jsdoc2md --template ../README.hbs --files *.js  package.json > README.md"
```
which did not produce an error message, but also did not include any form of version or other information I could see in the output

**Comment by 75lb** [comment]
I need a reproduction case which I can run and see this working in **jsdoc** (not jsdoc2md).. please paste a jsdoc command I can run along with a trivial source file and a package.json file containing data which gets picked up in the docs output by jsdoc.. once I have this and can see it working correctly in jsdoc, I can use the same files to debug why it fails to work in jsdocmd.

**Comment by LeadDreamer** [comment]
Running
```
jsdoc *.js package.json
```
does produce HTML which includes the correct version information

**Comment by LeadDreamer** [comment]
well, it's an open-source project (not tiny, not yet as documented/tested as I would like), but it's present in the repository:
https://github.com/LeadDreamer/firebase-wrappers
specifically the sub-module
.\FirebaseFirestoreWrapper

I'll have to live with it for now as I'm not sure I have time to reproduce a tiny subset.  Note the number of options I used in my NPM script for this package.

**Comment by LeadDreamer** [comment]
I've tried on top-level as well, same result

**Comment by 75lb** [comment]
Thanks for that.. OK, it seems this package-reading feature is offered specifically by the default jsdoc html template.. from the docs: 

> For example, the ***default template*** shows the project's name and version number in the documentation

I.e. it's a jsdoc specific thing - jsdoc2md does not support or use the jsdoc html templates..

I recommend using custom tags.. jsdoc2md supports arbitrary custom tags, e.g. 

```
/**
 * A variable with custom tags.
 * @sitcom Only Fools and Horse
 * @character Rodney Trotter
 * 
*/
const customTagged = true
```

So you could update your module docs to include a `@version` tag. 

```
/**
 * @module FirebaseFirestoreWrapper
 * @version 1.0.2
 * @description A set of helper-wrapper functions around firebase firestore, storage
 * and auth. Intent is to treat Firestore as a hierarchical
 * record-oriented database; originally conceived to port from one
 * database to another.
 */
```

This will include the version number in the markdown output. If you want the version number to be read from `package.json` you'll need to implement a custom helper (mentioned [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin)).

**Comment by LeadDreamer** [comment]
The entire POINT is to use the info from package.json, which allows the npm versioning tools, etc etc etc.  The entire POINT is to NOT maintain multiple locations.  Anything in /* */ is BY DEFINITION static.

I'll look at the custom helper, but since I'm building a start-up already, with a large-scale front end, a firebase backend with cloud functions AND this wrapper library - and not being paid a salary for any of it - I doubt I have any extra cycles to learn ANOTHER new system - I've already had to modify multiple open-source projects to get things working.
