### ISSUE TITLE
better intellisense 

### ISSUE THREAD

**Issue by jimmywarting** [jsdoc2md/jsdoc-to-markdown#251]
I normally never document the return type. vs code can figure it out just by looking at what the code returns, so can closure compiler.

<img src="https://user-images.githubusercontent.com/1148376/128860437-ec6fe063-08af-4999-8c82-1e8761dc6786.png" width=200>

Only time i document return it is when it returns something it dose not know anything about. like Promises or:

```js
/** @return {number} */
function foo() {
  return globalThis.bar // got assigned from somewhere else...
}
```

I use typescript a lot but without all the typescript syntax (using jsdoc instead)
https://www.youtube.com/watch?v=iP5XwRT2tNw
I Love typing and vanilla js but hate typescript syntax.

it seems like tsc can figure out better how to parse the code. 
I wonder if it would be better to utilize tsc to generate a t.ds file instead with allowJs  + checkJs combo and then somehow format the d.ts file to something else

https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by jimmywarting** [comment]
i do not document the argument either sometimes cuz it can also be discovered

<img src="https://user-images.githubusercontent.com/1148376/128862509-3dba6b48-9409-4afe-9c20-95203417124c.png" width=400> 

i guess it would be superior to utilize tsc for it's typing. tsc also use jsdoc if it's provided

**Comment by 75lb** [comment]
Hi, I have no plans to involve Typescript with this project- sorry.. This project is just a wrapper around jsdoc and unfortunately, the jsdoc project has been stale for many years..

**Comment by 75lb** [comment]
Typescript is just one of [many](https://www.slant.co/topics/101/~best-languages-that-compile-to-javascript) languages that compile to Javascript. Adding support for Typescript, Ruby, Dart, Clojurescript etc etc just adds to the maintenance burden and compromises the stability of the project.
