### ISSUE TITLE
An individually exported class with a constructor doesn't get rendered

### ISSUE THREAD

**Issue by niknbr** [jsdoc2md/jsdoc-to-markdown#252]
jsdoc-to-markdown - `7.0.1`
node - `v14.16.1`
os - `mac os`

### Description

❌  When we individually export a class having a constructor, the markdown doesn't get rendered: 
```javascript
/**
 * An example class
 *
 * @class
 */
export class TestClass {
  constructor() {
  }
}
```

✅ It works when we export the class separately:
```javascript
/**
 * An example class
 *
 * @class
 */
class TestClass {
  constructor() {   // has a constructor
  }
}

export { TestClass }  // exported separately
```
```
<a name="TestClass"></a>

## TestClass
An example class

**Kind**: global class  
```

✅ It works when we export the class individually, but without a constructor:
```javascript
/**
 * An example class
 *
 * @class
 */
export class TestClass {  // class exported inline
	// no constructor
}
```
```
<a name="TestClass"></a>

## TestClass
An example class

**Kind**: global class  
```

**Comment by 75lb** [comment]
Yeah.. unfortunately it's a long-standing issue with jsdoc - it's crudely documented [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-a-CommonJS-module-(module.exports)#what-not-to-do).

I'm afraid you'll need to use your success case in the example above - just like the rest of us! This project is a wrapper around jsdoc which has quite a few outstanding issues.
