### ISSUE TITLE
How do I actually get markdown out of the cli?

### ISSUE THREAD

**Issue by Pomax** [jsdoc2md/jsdoc-to-markdown#257]
I installed `'jsdoc-to-markdown": "^7.0.1"`, then ran `npx jsdoc2md myfile.js`, fixing all the errors it flagged (mostly missing return/throws text) until there were none left, and now it doesn't flag any errors anymore but also does not generate anything. There's no markdown output on stdout, and no files have been created, so... how do I use this tool to actually generate markdown from jsdoc comments? O_o

**Comment by Pomax** [comment]
Sure, but that was not the problem here.

**Comment by trev-dev** [comment]
Which mistakes did you make? I can get jsdoc output for my project, but I can't get jsdoc2md output.

**Comment by 75lb** [comment]
> Which mistakes did you make? I can get jsdoc output for my project, but I can't get jsdoc2md output.

that's normally due to the lack of a `@module` tag (read [this](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(single-default-export))

**Comment by trev-dev** [comment]
Yeah...I have a file header in all of my javascript files. Every file that's actually a module has a module declaration. I have some files that are for the purposes of describing things in the global namespace (Component namespaces & types). I *am* using JSDoc in tandum with TypeScript to describe my types, but it's not technically TypeScript. All of my files are JS.

I get some really nice documents via JSDoc, everything links and is organized just-so. I get a bunch of errors for the TypeScript BS that simply cannot be dealt with but it still works. Via jsdoc-to-markdown I get the same errors, 0 output.

**Comment by Pomax** [comment]
sounds like you want to file a new issue with a description of your specific situation. Given that this is a closed issue, probably the worst case to discuss a new (and rather different, from the sounds of it) problem.

**Comment by trev-dev** [comment]
> sounds like you want to file a new issue with a description of your specific situation. Given that this is a closed issue, probably the worst case to discuss a new (and rather different, from the sounds of it) problem.

Got it. Let me make a reproducible example and do that.
