### ISSUE TITLE
Where is the CIL documentation?

### ISSUE THREAD

**Issue by ErrorBot1122** [jsdoc2md/jsdoc-to-markdown#265]
Where is it????

**Comment by 75lb** [comment]
There are the `jsdoc2md --help` docs for the CLI.. Also, a lot of the options will documented here
https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md

What are you trying to do?

**Comment by ErrorBot1122** [comment]
I wanted to add jsdoc plugins but I don't need to anymore. I just wanted you to add documentation on the readme or somewhere, so people don have to download

*P.S: You can do a very simple version if you want...*
