### ISSUE TITLE
Instance method listed as static

### ISSUE THREAD

**Issue by matteocontrini** [jsdoc2md/jsdoc-to-markdown#27]
Hi,
I am using the method [posted here](http://sebastian.formzoo.com/2013/06/05/organising-and-structuring-a-big-node-js-module/) for splitting a class prototype in multiple files (submodules).
The problem is that prototype functions are marked as static this way, because looking at the submodule files only that's what you understand. But it's wrong, because they're all prototype functions.

Is there something that can be done to avoid this?

Thank you!

**Comment by matteocontrini** [comment]
The [`@instance`](http://usejsdoc.org/tags-instance.html) tag doesn't seem to work

**Comment by 75lb** [comment]
you need the [@alias](http://usejsdoc.org/tags-alias.html) tag..

will check the instance tag now..

**Comment by matteocontrini** [comment]
"alias" works, but it's pretty verbose because I need to write `ClassName#functionName` for every function. The "instance" tag would be great...

**Comment by 75lb** [comment]
`@instance` tag works fine, [see here](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/tags/instance).. 

you don't need to write `@alias` against every class member (the functions etc.) - you only write it at class level..

**Comment by matteocontrini** [comment]
Thanks.
It works if I set both `@alias` (on the object declaration inside the submodule) and `@instance` (on functions).

**Comment by 75lb** [comment]
hmm, sounds a bit messy.. ideally, jsdoc should be able to infer what the scope of your identifiers are from parsing the source code alone.. something feels a bit wrong when too many tags are needed..

**Comment by matteocontrini** [comment]
I had the same impression when I tried but it is probably because of this strange use case of objects. 

There are multiple objects declared in multiple files, with the same name of a class. Probably `@alias` is needed for telling "this is the same class declared somewhere else" and `@instance` for avoiding that the function is marked as static.

**Comment by 75lb** [comment]
maybe re-organise your code a different way, so objects / classes are not split into different files.. one class or object per file..

**Comment by matteocontrini** [comment]
I've just made that change, 2500 lines in the same file were not acceptable for mantaing a Node.js module :)

**Comment by 75lb** [comment]
f**k.. i agree..

**Comment by matteocontrini** [comment]
The `@alias` thing is not quite a solution... it is creating copies of the entire class for each time I use the alias. Oh God.

**Comment by 75lb** [comment]
can you show me? put some example code demonstrating your issue in a gist please..

**Comment by matteocontrini** [comment]
[The problem](https://gist.github.com/matteocontrini/8c33efb90304d2d2c70f)
[How I solved now](https://gist.github.com/matteocontrini/401d62c4b78864a62e7d) (creating multiple actual classes with the same name)

**Comment by 75lb** [comment]
i see.. yes, you might still need to use `@alias` in your piece files.. i've been through similar pain documenting my own stuff but once you get used to it it's nothing..
