### ISSUE TITLE
Moderate severity vulnerability - Uncontrolled Resource Consumption in markdown-it - https://github.com/advisories/GHSA-6vfc-qv3f-vr6c

### ISSUE THREAD

**Issue by jjcamachosanchez** [jsdoc2md/jsdoc-to-markdown#273]
Uncontrolled Resource Consumption in markdown-it - https://github.com/advisories/GHSA-6vfc-qv3f-vr6c
fix available via `npm audit fix --force`
Will install jsdoc-to-markdown@4.0.1, which is a breaking change
node_modules/markdown-it
  jsdoc  >=3.6.0
  Depends on vulnerable versions of markdown-it
  node_modules/jsdoc
    jsdoc-api  >=5.0.1
    Depends on vulnerable versions of jsdoc
    node_modules/jsdoc-api
      jsdoc-to-markdown  >=5.0.0-node12.1
      Depends on vulnerable versions of jsdoc-api
      node_modules/jsdoc-to-markdown

**Comment by JoernBerkefeld** [comment]
or to put it in simpler terms: both dependabot as well as npm audit alert users about an issue in markdown-it 10.0.0 - a version that has been release 2 yrs ago (https://www.npmjs.com/package/markdown-it)

could we update this to the newest version (12.3.2) please?

**Comment by 75lb** [comment]
jsdoc2md is an offline command line tool, not an online server exposed to
the internet - there is zero security vulnerability here... however i will
look into this later, thanks

**Comment by 75lb** [comment]
despite the fact there are zero security concerns here, unfortunately `npm audit` still reports this offline tool as "insecure" which is irritating..  the security warning is coming from [this dependency](https://github.com/jsdoc/jsdoc/blob/3.6.7/package.json#L22) in jsdoc which unfortunately I have no control over.. 

Someone has [already reported it to jsdoc](https://github.com/jsdoc/jsdoc/issues/1964) so I'll leave this issue open until it's resolved upstream..

**Comment by JoernBerkefeld** [comment]
I actually didn't dig deep enough. yes, it's the `jsdoc` pkg which you include via `jsdoc-api`...
Let's hope for a quick response from their team. -- wrong place to complain here, sorry

**Comment by aruiz-futurefinance** [comment]
I think this is resolved now in JSDoc 3.6.10

**Comment by 75lb** [comment]
I pushed an update refreshing the jsdoc2md dependency tree
