### ISSUE TITLE
Weird behaviours with classes when using ES modules

### ISSUE THREAD

**Issue by OiYouYeahYou** [jsdoc2md/jsdoc-to-markdown#274]
When using ES module syntax (`export`/`import`), nothing is emitted if:

- A class is not `default`, or,
- A class is `default` but only the constructor or less is documented

I've tested this on the latest version on npm

Here is one example that doesn't emit content:

```js
export class Example {
  /**
   * Hello world
   * @param {boolean} bool Booleans are great
   */
  constructor(bool) {
    console.log(bool)
  }

  /**
   * log a message
   * @param {string} text message
   */
  log(text) {
      console.log(text)
  }
}
```

**Comment by 75lb** [comment]
make sure you have a `@module` tag, see this [wiki page]..

**Comment by 75lb** [comment]
Please re-open if you still have issues
