### ISSUE TITLE
How to recursively document every .(m|c)js(x) files of a project?

### ISSUE THREAD

**Issue by VictorioMolina** [jsdoc2md/jsdoc-to-markdown#279]
Introduction
-

I am moving from the JSDoc's better-docs template to this package, since I prefer .MD files for all the stuff which is related to documentation.

Currently, for generating my docs with JSDoc, I am using the following config file named `jsdoc.js`:

```
module.exports = {
  plugins: [
    "plugins/markdown",
    "node_modules/better-docs/category",
    "node_modules/jsdoc-tsimport-plugin/index.js",
  ],
  source: {
    include: [
      "Main.jsx",
      "app/",
      // "functions/",
    ],
    includePattern: ".+\\.(js(doc|x)?|(m|c)js)$",
    excludePattern: "(node_modules/|docs)",
  },
  sourceType: "module",
  tags: {
    allowUnknownTags: true,
    dictionaries: ["jsdoc", "closure"],
  },
  templates: {
    "cleverLinks": true,
    "monospaceLinks": true,
    "search": true,
    "better-docs": {
      name: "Project name",
      title: "Nav title",
      component: {
        wrapper: "./Main.jsx",
      },
      hideGenerator: false,
      navLinks: [
        {
          label: "Github",
          href: "https://github.com/VictorioMolina",
        },
      ],
    },
  },
  opts: {
    encoding: "utf8",
    destination: "docs",
    recurse: true,
    readme: "README.md",
    template: "node_modules/better-docs",
  },
};

```

And, inside my package.json, I have the following script:

`"docs": "node_modules/jsdoc/jsdoc.js -c jsdoc.js -p"`

-------------------------

Question
-

How can I move from this way of generating docs to _jsdoc-to-markdown_? Is there any public script for parsing the JSDoc of each javascript (.(c|m)js(x)) module?

For example, in this monorepo structure:

```
  app/
     components/
        Buttons/
           FancyButton.jsx
           Buttons.d.js
           index.js

     utils/
        feature1/
           propTypes.js
        global/
           constants.js

     App.jsx

  functions/
     ...serverless stuff...
    
  node_modules/
```

How can I do for getting a **single** _.MD_ **including the JSDoc of each JavaScript module** excluding the `/functions/` and `/node_modules/` directories?

**Comment by 75lb** [comment]
you can customise jsdoc2md behaviour with a script or by default it will create one output file documenting all of the input files passed in.. e.g. process all `.js` files not in `node_modules` or `coverage` recursively in bash: 

```
$ jsdoc2md "!(node_modules|coverage)/**/*.js" > docs.md
```

Alternatively, write a script to handpick the files you want to process - example of jsdoc2md API usage [here](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class)
