### ISSUE TITLE
Missing documentation for classes with constructors

### ISSUE THREAD

**Issue by elementbound** [jsdoc2md/jsdoc-to-markdown#290]
The issue is reproducible on the [nlon](https://github.com/elementbound/nlon) repo, by running jsdoc2md against [packages/nlon/lib/error.mjs](https://github.com/elementbound/nlon/blob/ab3b08a33ed7b93fce5d2da97fda40adbb77c454/packages/nlon/lib/error.mjs), it produces the following output:

```
<a name="PeerDisconnectedError"></a>

## PeerDisconnectedError
<p>Error thrown when trying to send / receive on a peer that's already
disconnected.</p>

**Kind**: global class  

```

The output contains only one class, while the file itself contains multiple. The only thing I've noticed is that `PeerDisconnectedError` has no constructor, while the rest of the classes do. If I pick a class and remove its constructor, the class appears in the output as well.

Note that using the --json switch results in info about all the symbols ( not included for brewity ).

Here's the exact commands to replicate, starting from the root of the repo:

```sh
cd packages/nlon
jsdoc2md -c .jsdoc.js lib/error.mjs
jsdoc2md -c .jsdoc.js lib/error.mjs --json
```

Excellent tool otherwise! Unfortunately this is a deal-breaker for me at the moment, but looking forward to using this in the future.

**Comment by krisha2** [comment]
Looks like the issue could be that "memberof" is set to the same as "id" in the class item in the jsdoc template data when you have a constructor. This workaround seems to work for us:

Use:
	const data = (await jsdoc2md.getTemplateData({files: source})).map(item => {
		if (item.memberof === item.id) {
			delete item.memberof;
		}
		return item;
	});
	const md = await jsdoc2md.render({data});

Instead of:
	const md = await jsdoc2md.render({files: source});

**Comment by 75lb** [comment]
Add this to the top of the file: 

```
/**
 * @module my-module-name
 */
```

It's because the documented class is a child (in the underlying data structure) of an undocumented module. Undocumented identifiers/modules are skipped, resulting in their children being skipped too. [See this](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(multiple-named-exports)).

I need to make this behaviour more clear in the docs as it's by far the most common cause of confusion.
