### ISSUE TITLE
The "⇒" character becomes "ÔçÆ"

### ISSUE THREAD

**Issue by Lenni009** [jsdoc2md/jsdoc-to-markdown#291]
The command I ran: `jsdoc2md .\src\common.js > .\wiki\Functions.md`

All arrows became this weird unicode gibberish.

**Comment by TheBrenny** [comment]
How was this resolved?

**Comment by Lenni009** [comment]
I'm not entirely sure, but it may have been solved by using `sponge` instead of `>` to write the output to a file.
