### ISSUE TITLE
[feature request] Support optional instantiate parent name prefix

### ISSUE THREAD

**Issue by augusttty** [jsdoc2md/jsdoc-to-markdown#293]
By default, the instance method of a class output with a instantiate parent class name prefix on every method.
When the className getting ***longer***, or the methods getting ***too many*** , it seems unnecessary to give every "local" method a prefix.
I expected to omit the parent name, and I do tried the **partial** and the **helper**, but none of theme can achieve without a sideEffect(the signature is shared).And I have to change the **dmd** the source code to achieve that.Can *jsdoc2md* add a configuration to achieve this? 
For example:
# =>source: 
```

/**
 * Chat Service
 */
class ChatService {
  constructor(){}

  /**
   * send a message to a person
   */
  send() {}

  /**
   * receiving message
   */
  receive() {}
}
```
# =>default jsdoc2md output:

<a name="ChatService"></a>

## ChatService
Chat Service

**Kind**: global class  

* [ChatService](#ChatService)
    * [.send()](#ChatService+send)
    * [.receive()](#ChatService+receive)

<a name="ChatService+send"></a>

### chatService.send()
send a message to a person

**Kind**: instance method of [<code>ChatService</code>](#ChatService)  
<a name="ChatService+receive"></a>

### chatService.receive()
receiving message

**Kind**: instance method of [<code>ChatService</code>](#ChatService)

# =>expected output:
//...
<a name="ChatService+send"></a>

### send()
send a message to a person

**Kind**: instance method of [<code>ChatService</code>](#ChatService)  
<a name="ChatService+receive"></a>

### receive()
receiving message

**Kind**: instance method of [<code>ChatService</code>](#ChatService)

**Comment by 75lb** [comment]
I was able to achieve something like what you're looking for by modifying the built-in `{{>sig-name}}` partial, which looks like this: 

```hbs
{{#if virtual}}*{{/if}}{{#with (parentObject)}}{{#if virtual}}*{{/if~}}{{/with~}}
{{#if name}}{{#sig~}}
{{{@depOpen}~}}
{{{@codeOpen}~}}
{{#if @prefix}}{{@prefix}} {{/if~}}
{{@parent~}}
{{@accessSymbol}}{{#if (isEvent)}}"{{{name}}}"{{else}}{{{escape name}}}{{/if~}}
{{#if @methodSign}}{{#if (isEvent)}} {{@methodSign}}{{else}}{{@methodSign}}{{/if}}{{/if~}}
{{{@codeClose}~}}
{{#if @returnSymbol}} {{@returnSymbol}}{{/if~}}
{{#if @returnTypes}} {{>linked-type-list types=@returnTypes delimiter=" \| " }}{{/if~}}
{{#if @suffix}} {{@suffix}}{{/if~}}
{{{@depClose}~}}
{{~/sig}}{{/if~}}
{{#if virtual}}*{{/if}}{{#with (parentObject)}}{{#if virtual}}*{{/if~}}{{/with~}}
```

Try this: 

1. Copy the above into a new file
2. remove line 6 (`{{@parent~}}`) 
3. Save the file as `sig-name.hbs`
4. Run jsdoc2md with your modified partial: `jsdoc2md --partial sig-name.hbs --files *.js`

Hopefully that helps.. Let me know if not.

**Comment by 75lb** [comment]
But if you're still getting undesired side-effects (due to the fact `{{>sig-name}}` is used in multiple places, you might need to make your edit context-aware.. e.g. only strip the parent on class members:

```
{{#if (isClassMember)}}{{else}}{{@parent~}}{{/if~}}
```
