### ISSUE TITLE
Required and optional parameters are not distinguished.

### ISSUE THREAD

**Issue by fabpico** [jsdoc2md/jsdoc-to-markdown#298]
Similar to https://github.com/jsdoc2md/jsdoc-to-markdown/issues/160 but it sounds that Github has a magic behavior that solves it. I don't let render the markdown in Github, but in Storybook. And in Storybook it looks the same as in PhpStorm.

So the official docs of [@param](https://jsdoc.app/tags-param) says:

>Optional parameters and default values
>The following examples show how to indicate that a parameter is optional and has a default value.
>An optional parameter (using JSDoc syntax)
````
/**
 * @param {string} [somebody] - Somebody's name.
 */
````
So when I do this (I need extra `@module` to let the Markdown content being created)
````
/**
 * @module
 * @param {string} [somebody] - Somebody's name.
 */
````
The rendered results has no explicit optional indication.

**PhpStorm**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/c933a427-04f1-406a-8a20-0f373f558e50" width=600/>

**Storybook**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/108ebf72-16d6-411b-b8d4-092252e220c2"/>

When I add a required parameter

````
/**
 * @module
 * @param {string} somebodyRequired
 * @param {string} [somebody] - Somebody's name.
 */
````
There is still no explicit distinction, except the in-name literal brackets.

**PhpStorm**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/0182bbad-7986-4d24-a3dc-14847d164fff" width=600/>

**Storybook**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/e5c383d7-03af-417b-98a0-88552ce65238"/>

Same problem when using [@property](https://jsdoc.app/tags-property)

````
/**
 * @module
 * @property {string} somebodyRequired
 * @property {string} [somebody] - Somebody's name.
 */
````

**PhpStorm**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/012658d6-132e-4018-9948-2990836e6bcf" width=600/>

**Storybook**
<img src="https://github.com/jsdoc2md/jsdoc-to-markdown/assets/4472725/c08b6887-eef2-491e-8113-1417b07ad3f9"/>

**What is expected**
My expectation is that an additional column should be rendered, which explicitely indicates if the param is required or optional.

**Comment by 75lb** [comment]
Hi.. they are distinguished - by the square bracket notation.. square brackets are the generally-accepted standard to indicate "optional".. you will see this convention everywhere:

```
$ git -h
usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]
           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]
           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]
           <command> [<args>]
```

**Comment by 75lb** [comment]
You can add an extra column to the table but the table can begin to look squashed when properties have long descriptions, examples etc.. you need extra space for those columns.. try `--param-list-format list`, `--property-list-format list` or `--member-index-format list`, `--member-index-format grouped`
