### ISSUE TITLE
markdown-it < 13.0.2 security vulnerability

### ISSUE THREAD

**Issue by karlajw** [jsdoc2md/jsdoc-to-markdown#299]
markdown-it is vulnerable to an infinite loop which is triggered via the linkify inline rule. A malicious actor could leverage this vulnerability to deplete system resources, leading to a denial-of-service (DoS).

https://security.snyk.io/vuln/SNYK-JS-MARKDOWNIT-6483324

**Comment by 75lb** [comment]
markdown-it is a dependency of jsdoc, not this project - please report it [there](https://github.com/jsdoc/jsdoc)
