### ISSUE TITLE
separators don't work in some markdown renderers

### ISSUE THREAD

**Issue by DavidMGross** [jsdoc2md/jsdoc-to-markdown#30]
It would be nice if instead of a boolean on/off switch for "separators" you could specify the nature of the separator.  In Stash, for example, the single dash on a line by itself just renders as a single dash on a line by itself, not as a horizontal-rule.  So, something like:

```
jsdoc2md --separators "<hr />"
jsdoc2md --separators "----"
```

...would be helpful.

**Comment by 75lb** [comment]
good idea, thanks.. will look into that :+1:

**Comment by 75lb** [comment]
btw, the `-` separator (single dash on line by itself) is gfm-specific.. if your markdown parser does not like gfm you can disable it with the `--no-gfm` option.. is this any help as a quick win?

**Comment by 75lb** [comment]
you can see how `--no-gfm` affects the separators [in this example](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/example/options/formatting%20options/no-gfm/separator.md)

**Comment by DavidMGross** [comment]
Having horizontal lines suggested by "* * *" isn't much better than having
them suggested by "-" for my purposes.  As a workaround, I pipe the output
from jsdoc2md through a quick perl search-and-replace:

perl -p -i -e \"s/^-\\n/<hr \\/>\\n/g\"


On Thu, May 7, 2015 at 2:19 PM, Lloyd Brookes <notifications@github.com>
wrote:

> you can see how --no-gfm affects the separators in this example
> <https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/example/options/formatting%20options/no-gfm/separator.md>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsdoc2md/jsdoc-to-markdown/issues/30#issuecomment-100022254>
> .
>



-- 
David M. Gross
PLP Consulting

**Comment by 75lb** [comment]
`* * * ` is [vanilla markdown syntax for horizontal rule](http://daringfireball.net/projects/markdown/syntax#hr) - if your parser doesn't support that it doesn't fully support markdown. 

Not to worry, i'm working on internationalisation at the moment - that will allow us to localise/customise all words, symbols, markdown syntax etc.

**Comment by borisovg** [comment]
I've also hit this issue - jsdoc2md generates a single "-" where the line is supposed to be.

According to https://gist.github.com/howar31/5963000#hr only mentions "---", "***" and "___" as valid syntax for a horizontal line.

**Comment by 75lb** [comment]
closing, as most users seem satisfied with the default separator.. [see this wiki page](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial) for a tutorial how to change the default separator.
