### ISSUE TITLE
Add `--clever-links` and `--monospace-links` options

### ISSUE THREAD

**Issue by zanerock** [jsdoc2md/jsdoc-to-markdown#301]
Jsdoc defines options for 'clever links' which render non-URL links (e.g., links to functions, classes, modules, etc.) in monospace font, and also 'monospace links', which renders `{@link}`s in monospace by default.

The clever links and monospace links features would actually be implemented in the 'dmd' project, proposed here [dmd#85](https://github.com/jsdoc2md/dmd/issues/85).

**Comment by 75lb** [comment]
PRs squash-merged into master - this will be in the next version.. in the meantime, give everything a nice test please in the pre-release. 

```
npm install jsdoc-to-markdown@next
```
