### ISSUE TITLE
anchors contain illegal characters

### ISSUE THREAD

**Issue by DavidMGross** [jsdoc2md/jsdoc-to-markdown#31]
Some of the anchors generated by jsdoc2md contain the character "#" (e.g. `&lt;a name="Primer#publish"&gt;&lt;/a&gt;'). I don't think that's a legal character in an HTML anchor, and it does cause problems with some markdown renderers (e.g. Stash) which just omit the anchor link entirely.

See: http://stackoverflow.com/questions/2849756/list-of-valid-characters-for-the-fragment-identifier-in-an-url

**Comment by 75lb** [comment]
Ok, thanks.. maybe we should make the anchor string format a config option, will look into that

**Comment by 75lb** [comment]
this is fixed, will let you know once it is released.. in future the anchor names will look like this (`+` instead of `#`): 

`<a name="Primer+publish"></a>`

**Comment by 75lb** [comment]
this is released in ddata@0.1.19.. reinstall your jsdoc2md tool/plugin to pick it up..let me know if you have any more issues
