### ISSUE TITLE
Prevent pipe escaping

### ISSUE THREAD

**Issue by shaoner** [jsdoc2md/jsdoc-to-markdown#32]
Hi,

I'm completely satisfied with this module which handles everything I need.
However when using this syntax:
```javascript
/**
 * @param {(string|Number)} data
 */
```

It turns into `<code>string</code> \| <code>Number</code>` which seems to not be supported as standard markdown. It is here in github though. But usually it results into defining another column in the output table.

Would it be possible to output the ascii code:
```html
&#124;
``` 
instead of `\|` ?

Since | has no "markdown" meaning here, it should not break anything.

**Comment by 75lb** [comment]
are you using the latest version of the tool/plugin?

**Comment by shaoner** [comment]
No it seems I was not. Thank you.
