### ISSUE TITLE
Example caption support

### ISSUE THREAD

**Issue by whitlockjc** [jsdoc2md/jsdoc-to-markdown#33]
The [example tag allows captions](http://usejsdoc.org/tags-example.html) but when I attempt to use captions, jsdoc2md throws the caption tags and their contents into the example code.  Here is an example:

```js
/**
 * My cool API.
 *
 * @example <caption>Suggested Usage</caption>
 * console.log(myObj.myCoolApi());
 */
function myCoolApi () { }
```

Right now, the generated example _(without header)_ looks like this:

```js
<caption>Suggested Usage</caption>
console.log(myObj.myCoolApi());
```

When I'd expect the generated example to look like this:

```js
console.log(myObj.myCoolApi());
```

I would also like to see the example header use the caption when available.  So based on the example above, I'd like to see `**Example _(Suggested Usage)_**` for the generated example header instead of `**Example**`.  Of course, how you style/display the caption in the end doesn't matter to me as long as it's used in some way so people viewing my examples can also view the caption since it is usually important.

If you're cool with this, I'll do the work and submit a PR.  I just didn't want to go through the effort only to be told you didn't want it.

**Comment by 75lb** [comment]
Hi Jeremy, you're absolutely right - we need to support @example captions..
if a PR is not too much effort for you I would welcome it, otherwise it
will go on my todo list.. your suggestion to add the caption to the example
header makes sense..

**Comment by whitlockjc** [comment]
Don't worry yourself with this, I'll take care of it.  Work on the other stuff and look for my PR.  :)

**Comment by 75lb** [comment]
appreciated :+1:

**Comment by whitlockjc** [comment]
Being new to this project, it seems the actual place to fix this might be `dmd` or `jsdoc-parse`?  Can you confirm/deny so I don't go down a rabbit hole?

**Comment by 75lb** [comment]
the handlebars partial which renders the `@example` tag is here: https://github.com/jsdoc2md/dmd/blob/v1.1.1/partials/all-docs/docs/body/examples.hbs

the `{{#examples}}` helper is defined here: https://github.com/jsdoc2md/dmd/blob/v1.1.1/helpers/helpers.js#L295

yes, it is rather rabbit-holish atm.. it will improve..

**Comment by whitlockjc** [comment]
Thanks for pointing me in the right direction.
