### ISSUE TITLE
Markdown list nesting not being done correctly.

### ISSUE THREAD

**Issue by jviotti** [jsdoc2md/jsdoc-to-markdown#36]
Currently, nested lists use 2 spaces for indentation:

```markdown
* [resin](#resin) : <code>object</code>
  * [.models](#resin.models) : <code>object</code>
    * [.application](#resin.models.application) : <code>object</code>
      * [.getAll()](#resin.models.application.getAll) ⇒ <code>Promise.&lt;Array.&lt;Object&gt;&gt;</code>
      * [.get(name)](#resin.models.application.get) ⇒ <code>Promise.&lt;Object&gt;</code>
      * [.has(name)](#resin.models.application.has) ⇒ <code>Promise.&lt;Boolean&gt;</code>
      * [.hasAny()](#resin.models.application.hasAny) ⇒ <code>Promise.&lt;Boolean&gt;</code>
      * [.getById(id)](#resin.models.application.getById) ⇒ <code>Promise.&lt;Object&gt;</code>
      * [.create(name, deviceType)](#resin.models.application.create) ⇒ <code>Promise.&lt;Number&gt;</code>
      * [.remove(name)](#resin.models.application.remove) ⇒ <code>Promise</code>
      * [.restart(name)](#resin.models.application.restart) ⇒ <code>Promise</code>
      * [.getApiKey(name)](#resin.models.application.getApiKey) ⇒ <code>Promise.&lt;String&gt;</code>
      * [.getConfiguration(name, [options])](#resin.models.application.getConfiguration) ⇒ <code>Promise.&lt;Object&gt;</code>
    * [.config](#resin.models.config) : <code>object</code>
      * [.getAll()](#resin.models.config.getAll) ⇒ <code>Promise.&lt;Object&gt;</code>
      * [.getPubNubKeys()](#resin.models.config.getPubNubKeys) ⇒ <code>Promise.&lt;Object&gt;</code>
      * [.getDeviceTypes()](#resin.models.config.getDeviceTypes) ⇒ <code>Promise.&lt;Array.&lt;Object&gt;&gt;</code>
```

Which causes nested lists to not be displayed correctly:

![screenshot 2015-06-29 12 57 08](https://cloud.githubusercontent.com/assets/2192773/8413434/6522c72a-1e5e-11e5-9ed7-87653227c885.png)

According to the markdown documentation, nested lists should be implemented with 4 spaces or 1 tab.

Manually editing `jsdoc-to-markdown` output to use 4 spaces leads to the expected result:

![screenshot 2015-06-29 13 00 15](https://cloud.githubusercontent.com/assets/2192773/8413482/cf46da06-1e5e-11e5-85e7-6e18e4e5f503.png)

**Comment by 75lb** [comment]
Ok, I thanks.. which markdown renderer are you using to view the final
output?

**Comment by jviotti** [comment]
@75lb I'm using http://marked2app.com.

**Comment by 75lb** [comment]
Thanks, I will test in that.. fyi, Atom has a great markdown editor and
previewer

**Comment by jviotti** [comment]
@75lb Thanks for the tip, Marked2 fits me great as a vim user.

**Comment by jviotti** [comment]
It works fine on GitHub though, so not really high priority for me. I'll also ping Marked2 team to support 2 spaces indentation like GitHub (not standard, but I guess widely used anyway).

**Comment by 75lb** [comment]
fix released, please update and let me know if you have any more issues!
