### ISSUE TITLE
 TypeError: Object function jsdoc2md(options){...} has no method 'render'

### ISSUE THREAD

**Issue by techjeffharris** [jsdoc2md/jsdoc-to-markdown#37]
I'm getting this error when I try to run jsdoc2md as a required module in node.js

     /home/.../.bin/docs.js:127
                         jsdoc2md.render('lib/' + name + '.js').on('error', done).
                                  ^
    TypeError: Object function jsdoc2md(options){
        options = options || {};
        var src = options.src;
        var dmdStream = dmd(options);
        if (src){
            var jsdocStream = jsdocParse(options);
            
            if (options.json || options.stats){
                return jsdocStream;
            } else {
                jsdocStream.pipe(dmdStream);
                jsdocStream.on("error", dmdStream.emit.bind(dmdStream, "error"));
                return dmdStream;
            }
        } else {
            var jsdocStream = jsdocParse(options);

            if (options.json || options.stats){
                return jsdocStream;
            } else {
                var transform = new Transform();
                jsdocStream.pipe(dmdStream);
                jsdocStream.on("error", dmdStream.emit.bind(dmdStream, "error"));
            
                transform._transform = function(chunk, enc, done){
                    jsdocStream.write(chunk);
                    done();
                };
                transform._flush = function(){
                    jsdocStream.end();
                };
                dmdStream.on("readable", function(){
                    var chunk = this.read();
                    transform.push(chunk);
                });
                dmdStream.on("end", function(){
                    transform.push(null);
                });
                dmdStream.on("error", function(err){
                    transform.emit("error", err);
                });

                return transform;
            }
        }
    } has no method 'render'

I have obliterated my node_modules dir, then ran npm install again... 

Any Idea why that might be happening?

**Comment by 75lb** [comment]
The render method doesn't exist - it's from an old version prior to the v1
release.. check the API docs on the readme..

**Comment by techjeffharris** [comment]
Thanks, and sorry for the derp :)

**Comment by 75lb** [comment]
No.problem.. I still have plenty to do on this tool so keep my posted of
any other quirks you don't like
