### ISSUE TITLE
How to replace code tag with backticks?

### ISSUE THREAD

**Issue by ryan-sandy** [jsdoc2md/jsdoc-to-markdown#40]
How to replace `<code>` tag with backticks (`` ` ``)?

I would like to use jsdoc2md with bitbucket but bitbucket does not render `<code>` tags.

**Comment by 75lb** [comment]
have you tried the bitbucket plugin? 

https://github.com/jsdoc2md/dmd-bitbucket

**Comment by ryan-sandy** [comment]
I tried, but it hangs. No error. No output.

On Wed, Aug 5, 2015 at 1:36 PM, Lloyd Brookes <notifications@github.com>
wrote:

> have you tried the bitbucket plugin?
>
> https://github.com/jsdoc2md/dmd-bitbucket
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsdoc2md/jsdoc-to-markdown/issues/40#issuecomment-127982855>
> .
>



-- 
------------------------------
<support@edits.net>EdITS/ERAS
PO Box 7234, San Diego, CA 92167
Ph: (800) 416-1666
www.edits.net • support@edits.netSupport Team <support@edits.net>

<support@edits.net> <support@edits.net>

**Comment by ryan-sandy** [comment]
Never mind go it working.

**Comment by jeffscottward** [comment]
HOW??

**Comment by ryan-sandy** [comment]
Honestly, it's been two years and I don't remember. That was pretty bad of me not to comment. I'll dig around on my work machine tomorrow. I'm not sure I still have anything related to this bug.
