### ISSUE TITLE
Bigger jsdoc-to-markdown use example

### ISSUE THREAD

**Issue by jviotti** [jsdoc2md/jsdoc-to-markdown#41]
Hi, for a bigger example of `jsdoc-to-markdown` you may like to showcase https://github.com/resin-io/resin-sdk.

There is a `DOCUMENTATION.md` file (https://github.com/resin-io/resin-sdk/blob/master/DOCUMENTATION.md) being generated with `jsdoc-to-markdown`.

**Comment by 75lb** [comment]
hi, sorry for the delay - i have been on holiday.. great docs, nice work.. i notice you use promises, did you know you can use @fulfil and @reject tags? Here's the [example page](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/tags/custom%20tags%20(e.g.%20%40fulfil%2C%20%40reject)) and [these docs](https://github.com/jesucarr/tokenbucket) show a live example

**Comment by jviotti** [comment]
@75lb Nice, thanks for the information, will be using those tags soon.
