### ISSUE TITLE
Command line client arguments order.

### ISSUE THREAD

**Issue by ryan-sandy** [jsdoc2md/jsdoc-to-markdown#42]
Are command line arguments supposed to be trailing? The help states options then source, but that order causes the program to hang. When using trailing options, everything works fine. (ex `jsdoc2md scoure.js --plugin dmd-bitbucket`)

**Comment by 75lb** [comment]
the arg order doesn't matter.. although if you have issues try passing the filenames under the `--src` option explicitly (as `--src` is the `defaultOption` it will collect up all hanging args (like filenames) if omitted).. so try 
```
$ jsdoc2md --src scoure.js --plugin dmd-bitbucket
```
or
```
$ jsdoc2md --plugin dmd-bitbucket --src scoure.js
```

**Comment by 75lb** [comment]
i've almost finished a rewrite of `command-line-args` with better docs to explain this behaviour better..
