### ISSUE TITLE
Question: Create Individual Markdown files for Each JS File?

### ISSUE THREAD

**Issue by reggi** [jsdoc2md/jsdoc-to-markdown#43]
Is something like this possible with the command line? Or do I have to use the node api?

```
jsdoc2md ./*.js > ./docs/*.md
```

**Comment by reggi** [comment]
I'm a little confused about how to use the transform stream with my promise chain. Would appreciate help, or alternative.

```javascript
var _ = require('lodash')
var path = require('path')
var jsdoc2md = require('jsdoc-to-markdown')
var Promise = require('bluebird')
var fs = Promise.promisifyAll(require('fs'))
var CWD = process.cwd()

module.exports = function(){
  return fs.readdirAsync(CWD)
  .then(_)
  .call('filter', function(file){
    var valid = ['.js']
    return _.contains(valid, path.extname(file))
  })
  .call('value')
  .map(function (jsFile) {
    return jsdoc2md()
  })
}
```

**Comment by 75lb** [comment]
did you look at the example? https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/scripting/output-file-per-class

**Comment by reggi** [comment]
Nope I didn't see that. Really fascinating. I'm not 100% confident in my abilities with streams :(

I wen't ahead and made a promise wrapper for `jsdoc2md` here [`jsdoc2md-async`](https://github.com/reggi/node-reggi/blob/master/jsdoc2md-async.js)
