### ISSUE TITLE
Feature Request: Ability to Add JSDoc to File via Comment Block

### ISSUE THREAD

**Issue by reggi** [jsdoc2md/jsdoc-to-markdown#44]
I've been wrestling a lot with markdown and jsdoc in general. I'm interested in some extra functionality that `jsdoc2md` doesn't (to my knowledge) provide.

The project by @thlorenz [thlorenz/doctoc](https://github.com/thlorenz/doctoc) adds a table of contents to an existing document. It's in that module's nature to need an existing doc, so it supports this comment syntax

```html
<!-- START doctoc -->
<!-- END doctoc -->
```

And if it finds it in the markdown, it replaces it with the `TOC` something like this:

```html
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->

... stuff

<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

This is ideal because if I run the command again to update it preserves my original file and updates the `TOC`.

I need this same support for `jsdoc2md`. Is this something this module can support? Already does support? 

Understandably it's not necessary to the functionally to update an existing doc, it just overwrites. 

@75lb Interested in your thoughts on supporting a comment block.

**Comment by 75lb** [comment]
hi! jsdoc2md currently uses handlebars for templating, see the `--template` option.. in the future it will use plain ES6 Template Strings.

**Comment by reggi** [comment]
thx
