### ISSUE TITLE
Invalid MD code block conversion

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc2md/jsdoc-to-markdown#46]
I have MD style enabled in my jsDoc comments, using \`\` everywhere.

This library converts them into `&#x60;`, which in turn breaks their content and the layout.

**UPDATE:** I've just noticed that list indent of the MD syntax `-` is also not converted correctly, when it is part of `@param`.

[Here's the code documentation](https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js#L998), which renders a proper list when converted by jsDoc.

[And here's what it looks like](https://github.com/vitaly-t/pg-promise/blob/master/API.md#pg-promise), through this module.

**Comment by 75lb** [comment]
hi.. how does it look if you use the `--no-gfm` option? when set, param tables will be rendered using html rather than md, as seen in [this example](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/example/options/dmd%20options/no-gfm/param-list.md)

**Comment by vitaly-t** [comment]
How do I change the following file to use that option?
```javascript
"use strict";
module.exports = function (grunt) {
    grunt.initConfig({
        jsdoc2md: {
            oneOutputFile: {
                src: "lib/index.js",
                dest: "api.md"
            }
        }
    });
    grunt.loadNpmTasks("grunt-jsdoc-to-markdown");
    grunt.registerTask("default", "jsdoc2md");
};
```

**Comment by 75lb** [comment]
on the grunt plugin readme, see the task config in the example labelled `withOptions`

**Comment by vitaly-t** [comment]
Ok, so I have changed it to:
```javascript
"use strict";
module.exports = function (grunt) {
    grunt.initConfig({
        jsdoc2md: {
            oneOutputFile: {
                src: "lib/index.js",
                dest: "api.md"
            },
            withOptions: {
                options: {
                    "no-gfm": true
                }
            }
        }
    });
    grunt.loadNpmTasks("grunt-jsdoc-to-markdown");
    grunt.registerTask("default", "jsdoc2md");
};
```
But when I run it, the output file is identical to the one without the option. I hope I'm doing it right...

**Comment by 75lb** [comment]
it should be 
```
"use strict";
module.exports = function (grunt) {
    grunt.initConfig({
        jsdoc2md: {
            oneOutputFile: {
                options: {
                    "no-gfm": true
                },
                src: "lib/index.js",
                dest: "api.md"
            }
        }
    });
    grunt.loadNpmTasks("grunt-jsdoc-to-markdown");
    grunt.registerTask("default", "jsdoc2md");
};

```

**Comment by vitaly-t** [comment]
Ops, that's different from what the plug-in suggests....

Anyhow, I've made that change, and it fixed the second problem for lists within `@param`, but the first problem remains.

**Comment by 75lb** [comment]
> Ops, that's different from what the plug-in suggests....

it's not, i copied the code from the README (which assumes the reader knows Grunt)

> 
> Anyhow, I've made that change, and it fixed the second problem for lists within @param, but the first problem remains.


ok, one sec

**Comment by 75lb** [comment]
can you post you remaining problem please, i wasn't clear from re-reading the original post

**Comment by vitaly-t** [comment]
In the post just above I showed an example of where \`\` gets converted into `&#x60;`, exepectedly, which breaks to formatting.

**Comment by vitaly-t** [comment]
Is the problem reproducible on your end?

**Comment by 75lb** [comment]
that's strange.. i replied to this 3 hours ago from email, but my response is not showing.. 

regarding `&#x60;text&#x60`: if you are using the `--no-gfm` option then your output will be html, not markdown.. so in this case use `<code>text</code>` - i.e. html, not backticks.

**Comment by vitaly-t** [comment]
Do you mean, specifically for `@summary`? It seems to work everywhere else. That's what strange.

**Comment by 75lb** [comment]
will take a closer look later.. 

just for the record, the `--no-gfm` option will affect the @param output, but does not affect the @summary tag output as it doesn't use gfm..

**Comment by vitaly-t** [comment]
And I just tried, got [even worse results](https://github.com/vitaly-t/pg-promise/blob/master/API.md#databasefuncfuncname-values-qrm--promise)

It completely fails to process the `@summary` contents. Looks like something is broken in `@summary` support.

**Comment by 75lb** [comment]
ok, thanks.. i have a feeling this might be caused by an update to a module jsdoc2md uses under the hood, it needs a closer look.. use of `&#x60;` it's not something i've written..

**Comment by 75lb** [comment]
Hi Vitaly, are you still having this issue?

**Comment by vitaly-t** [comment]
Well, no, because I had to use a work-around, and avoid using code blocks within summary. Has it been fixed? If so, I will try it next time.

**Comment by 75lb** [comment]
привет виталий, i apologise for the delay.. the "backticks in summary" issue has been fixed and released, please update your jsdoc2md plugin.

i looked at your documentation - great work.. i noticed you return promises, in my opinion it's cleaner to document them using `@fulfil` and `@reject` tags (custom tags - you can use any tag you like in jsdoc2md).

I documented `database.connect()` [here](https://github.com/75lb/pg-promise/tree/master/API#databaseconnect--promise) using this method, to suggest how it's done.. I also used an `@external` with a `@see` link to give us a clickable `Promise` return type.

Also, [this library](https://github.com/jesucarr/tokenbucket) documents a lot of promises, and uses `--param-list-format list`.

**Comment by vitaly-t** [comment]
@75lb Thank you! :+1:
