### ISSUE TITLE
Question: Source code links

### ISSUE THREAD

**Issue by daserge** [jsdoc2md/jsdoc-to-markdown#47]
Is there a way to enable Github source code linking like [Dokker](http://dokkerjs.com/) does?

**Comment by 75lb** [comment]
it's not in the current version, but we could add that.. will look into it when i can (not sure when yet).. PR welcome, if you have a solution..

**Comment by daserge** [comment]
Got it, thanks, @75lb.

**Comment by daserge** [comment]
Filed PRs for this feature, @75lb, can you please take a look?
https://github.com/jsdoc2md/ddata/pull/3
https://github.com/jsdoc2md/dmd/pull/25
https://github.com/jsdoc2md/jsdoc-parse/pull/11

**Comment by 75lb** [comment]
will pull later today - thanks for the contribution

**Comment by 75lb** [comment]
thanks.. playing with it now.. a few initial thoughts

1. I think it should be optional feature, not the default (easy fix)
2. "S" symbol rather large and significant-looking for an aside..  (easy fix: make superscript)
3. will it work for Bitbucket and Github Enterprise users? (will check)
4. This implementation assumes all input source comes from the same repo.. this is not always the case, we can build documentation from multiple repos (e.g. `jsdoc2md projectA/lib.js projectB/lib.js`). As an example, the jsdoc-to-markdown docs are composed from three projects (jsdoc2md, dmd and jsdoc-parse) so `--base-url` would require 3 repo values..

will have a think about that last one..

**Comment by daserge** [comment]
Regarding point `4.` - theoretically we could extract the address from a project' package.json (`repository.url`) file if it exists.

**Comment by daserge** [comment]
Updated the PRs to address `1.` and `2.`, @75lb, please take a look.

**Comment by 75lb** [comment]
ok, thanks.. i've had a look and a think.. i would prefer to implement this feature as a dmd plugin because i'm not quite ready to support it for all use cases in the main app.. however, this would require me to upgrade dmd a bit too.. 

are you in a rush for this feature? I'm very close to beginning a major refactor of jsdoc2md, i have significant structural changes planned.. no features will be lost but i need to change the way it's put together (handbrake will go and it will be broken down into much smaller pieces).. i would prefer to implement this in version 2, which would mean waiting a little while.. that ok?

**Comment by daserge** [comment]
Sure, thanks!

**Comment by 75lb** [comment]
hi Sergey! Did you implement the source code links feature somewhere? Do you have some generated docs with source code links i could look at? I might include it in jsdoc2md v2..

**Comment by daserge** [comment]
Hi Lloyd, yes the source links feature lives in my forks:
https://github.com/jsdoc2md/ddata/pull/3
https://github.com/jsdoc2md/dmd/pull/25
https://github.com/jsdoc2md/jsdoc-parse/pull/11

And the sample:
https://github.com/MSOpenTech/cordova-plugin-camera/blob/505f1a0441eb8f8e2ea07a56dbef46c6238957fc/README.md

Please let me know if I should reopen the PRs.

**Comment by 75lb** [comment]
ok, thanks.. I am making progress with jsdoc2md2 - we can publish this feature as a plugin/add-on.. no need to reopen the PRs - they are for the old version.. i will get back to you soon with more info.

**Comment by daserge** [comment]
@75lb, any news on this topic?

**Comment by 75lb** [comment]
quite a lot of news, but ultimately jsdoc2md v2 is not quite ready.. i'm still working on it and have been delayed, recently.. 

the main focus of the next version is to make the output *much* easier to customise (currently, it takes too long to learn/edit the dmd partials) and more accurate (i.e. so the tool documents precisely what exists, not what you *say* exists via jsdoc comments).. this focus has led to me binning both handlebars and jsdoc entirely! 

I have put a lot of work into the new version but it's not quite ready yet, sorry..

**Comment by 75lb** [comment]
how about you? And news regarding your jsdoc2md usage? Is it still fit-for-purpose?

**Comment by daserge** [comment]
This sounds like a great plan - I've faced that same issues while working on the docs-gen for [cordova-plugin-camera](https://github.com/apache/cordova-plugin-camera/blob/d4a55f20ec1164f521f487110318e0fa431644d8/package.json#L43).

I'm going to update [the proposal](https://github.com/cordova/cordova-discuss/pull/16) now to reflect the current state of jsdoc-to-markdown setup (without source links for now).

Thanks for the great tool, hope it will be evolving even more as per your plans!

**Comment by cramatt** [comment]
Any updates on this ? Thanks!
