### ISSUE TITLE
Moving @return + @see to the bottom

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc2md/jsdoc-to-markdown#48]
I am generating separate MD files for each method, using [grunt-jsdoc-to-markdown](https://github.com/jsdoc2md/grunt-jsdoc-to-markdown).

What I'd like to change in the output though, is to have the `@return` + `@see`sections appear at the bottom, after all the @parameter entries, like in any standard API documentation, and not before it. Is there a way to accomplish this?

In addition, I also would like `@summary` to appear before `@description`, and not the other way round as it is done in the default layout.

**UPDATE:** I have asked the question on [StackOverflow](http://stackoverflow.com/questions/32761534/md-custom-layout-from-jsdoc-to-markdown).

**Comment by 75lb** [comment]
Yes, have a look at the dmd readme.. You can create your own body.hbs
partial locally and pass it to `--partial`

**Comment by vitaly-t** [comment]
@75lb 

I just had a look at the HBS files, couldn't find an example of how to reorganize specific elements in the template as I explained in my example, regarding `@return`, `@see`, `@summary` and `@description`.

Do you know of any template showing how to do that? I just want an example.

Also, how to connect it within grunt-jsdoc-to-markdown.

**Comment by 75lb** [comment]
Create a local copy of this file with your edits

https://github.com/jsdoc2md/dmd/blob/master/partials/all-docs/docs/body/body.hbs

Pass it's filename as the `partial ` option in grunt config

**Comment by vitaly-t** [comment]
@75lb thank you!

**Comment by 75lb** [comment]
You're welcome

**Comment by vitaly-t** [comment]
I was just able run some tests with this, and don't seem to get any results here...

Following your suggestion I created file `docs/template.hbs`, with content:
```javascript
{{>summary~}}
```
then I changed my `gruntfile.js` to:
```javascript
module.exports = function (grunt) {
    grunt.initConfig({
        jsdoc2md: {
            oneOutputFile: {
                options: {
                    "no-gfm": true,
                    "partial": "docs/template.hbs"
                },
                files: files // array of all my files
            }
        }
    });

    grunt.loadNpmTasks("grunt-jsdoc-to-markdown");
    grunt.registerTask("default", "jsdoc2md");
};
```
And I'm getting exactly the same results as before, it seems to either not find the template, or maybe ignores - I don't know, but it reports no problems, runs exactly as before.

Any idea why is it not working?

**Comment by 75lb** [comment]
you grunt config looks fine.. i just tested a custom `partial` with the grunt plugin and it works as expected.. 

what version of grunt-jsdoc-to-markdown, node and npm are you on?

**Comment by vitaly-t** [comment]
That is strange indeed. Must be something trivial, because the explanation was clear, but it just doesn't work.

My version of grunt-jsdoc-to-markdown is 1.1.1, and npm version is 2.6.0

Maybe it will be simpler if you have a quick look at the small library where I'm trying to use it, and see if you can spot what is wrong?

The library is [spex](https://github.com/vitaly-t/spex), and you can install it with:
```
npm install spex
```
That will have the required `gruntfile.js` in the root, and `docs/template.hbs`.

And once installed for dev dependencies, you can run `grunt` as the default task to get all the expected documents in folder `docs`.

**Comment by 75lb** [comment]
sorry, maybe i didn't document it but partial filename is significant.. if you're overriding `body.hbs` then your local file *must* also be `body.hbs`.. rename `template.hbs` to `body.hbs` and update your config

```
options: {
    "no-gfm": true,
    "partial": "docs/body.hbs"
},
```

**Comment by vitaly-t** [comment]
Huh, that now works! :)

**Comment by vitaly-t** [comment]
A little unrelated, but when I use in `body.hbs`
```javascript
{{>summary~}}

---
{{>description~}}
```
It removes the line break before `---`, which in turn breaks the formatting.

How to overcome this?

**Comment by 75lb** [comment]
The ~ character removes whitespace, see the handlebars docs

**Comment by vitaly-t** [comment]
Thank you for your help!
