### ISSUE TITLE
Outputting a single function with templates

### ISSUE THREAD

**Issue by jviotti** [jsdoc2md/jsdoc-to-markdown#50]
How can I output a single function (the whole documentation, not just the name) of a certain module in a `hbs` template file? This is not very clear in the selector helpers documentation.

**Comment by jviotti** [comment]
After some experimentation with Handlebars and after checking https://github.com/jsdoc2md/dmd, I was able to accomplish it with the following snippet:

```
{{#function name="myFunctionName"}}
{{>docs~}}
{{/function}}
```

Thank you very much, closing this issue!

**Comment by 75lb** [comment]
yes, you're right - it's not very clear.. i will have more time to fix this in the near future..
