### ISSUE TITLE
⇒ (=>) not showing on chrome

### ISSUE THREAD

**Issue by BHare1985** [jsdoc2md/jsdoc-to-markdown#54]
See https://github.com/BHare1985/BinaryQuadkey on chrome 46.0.2490.80 with windows

Shows: ![Image of exmaple](http://i.imgur.com/Vu51W2j.png)

It may be better to pick a symbol that is more universal and renders on all browsers?

**Comment by 75lb** [comment]
Hi, which version of windows?

**Comment by BHare1985** [comment]
windows 10

**Comment by 75lb** [comment]
hi! i just installed a Windows10 virtual machine with Chrome 47.0.2526.73 on it.. everything looks fine, IE too..

Something seems wrong as `⇒` is a common character from the [basic multilingual plane](https://en.wikibooks.org/wiki/Unicode/Character_reference/2000-2FFF)..  can you reproduce this issue on other machines?

**Comment by 75lb** [comment]
i forgot to add the screenshot.. 
![screen shot 2015-12-07 at 14 48 16](https://cloud.githubusercontent.com/assets/1247980/11633686/85dceb24-9d04-11e5-8048-074ba79e3d1b.png)
