### ISSUE TITLE
List of methods broken

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc2md/jsdoc-to-markdown#59]
I noticed this issue started happening not so long ago, which wasn't happening before...

* [Database](https://github.com/vitaly-t/pg-promise/blob/f8693c6a6209d06e89653794209c562812089329/API/README.md#module_pg-promise.Database)
* [Task](https://github.com/vitaly-t/pg-promise/blob/f8693c6a6209d06e89653794209c562812089329/API/README.md#module_pg-promise.Task)

All my types now have their list of methods come up as broken. When I compared the output to the previous version, I noticed that I'm getting an extra space to the left now, which in turn breaks the MD layout.

**Comment by 75lb** [comment]
Thanks for letting me know, will fix as soon as i can

**Comment by 75lb** [comment]
fixed and released in dmd 1.3.3, please upgrade your plugin to pick it up.. thanks again :+1:

**Comment by vitaly-t** [comment]
Doesn't quite do the trick, because in my project I'm using `grunt-jsdoc-to-markdown`, which has dependency directly on version `1.3.1`. Perhaps you should release `grunt-jsdoc-to-markdown` with dependency set as `1.3`, which is the same as `1.3.x`, so the changed are picked up.

**Comment by 75lb** [comment]
it does do the trick.. the fix was released in **dmd 1.3.3**.. trash your node_modules then reinstall, you will see `dmd 1.3.3` in the `npm ls` tree.. 

in case you haven't noticed, npm version 3 has been a nightmare so far.. in case you don't have it already, please ensure you have the latest version `npm i -g npm@next`..

**Comment by vitaly-t** [comment]
I think you didn't follow what I said about the dependency...

The latest version of `grunt-jsdoc-to-markdown` that you released is 1.2.0, which is set to use strictly version `1.3.1` of `jsdoc-to-markdown`. Deleting or reinstalling dependencies got nothing to do with that.

You need to update `grunt-jsdoc-to-markdown`, so it is either updated to the latest `1.3.2` of `jsdoc-to-markdown`, or set it to more generic `1.3`.

**Comment by 75lb** [comment]
grunt-jsdoc-to-markdown [has a dependency](https://github.com/jsdoc2md/grunt-jsdoc-to-markdown/blob/master/package.json#L26) on `^1.3.1`, **not** `1.3.1`.
