### ISSUE TITLE
default parameter values always wrapped in quotes

### ISSUE THREAD

**Issue by whitlockjc** [jsdoc2md/jsdoc-to-markdown#60]
Whenever a `@param` tag sets a default value, the rendered value is always in quotes.  I never noticed this before but it came up recently at [json-refs/issues/51](https://github.com/whitlockjc/json-refs/issues/51).  The more I think about it, it can be somewhat confusing to have all values wrapped in quotes because as reported, it does suggest that the value is a string.  Thoughts?

**Comment by 75lb** [comment]
yeah, i know :confused: i [raised this](https://github.com/jsdoc3/jsdoc/issues/900) a year ago with jsdoc3..  i think an effort was made to fix it, but the solution is either incomplete or has regressed.. 

i will investigate it again..

**Comment by whitlockjc** [comment]
Much appreciated.  I'll keep an eye out but if it's out of your control, I'm not too worried about it.

**Comment by 75lb** [comment]
ok.. many jsdoc3 issues are out of my control - in which case i apply fixes downstream (either in [my jsdoc fork](https://github.com/jsdoc2md/jsdoc) or jsdoc-parse)..

**Comment by 75lb** [comment]
i've been playing with param defaults, take a look [here](https://github.com/jsdoc2md/testbed/blob/master/build/global/param-default/3-dmd.md).. you can see how the default array `[ 1, 2, 3 ]` is marked as a string when the type is `string | Array` but an array when `Array | string`.. 

so, as a temporary workaround try swapping the types around so the type of the default value is first.. long-term i'll keep playing then make a suggestion to jsdoc3..

**Comment by whitlockjc** [comment]
Thanks a lot.
