### ISSUE TITLE
error are not thrown

### ISSUE THREAD

**Issue by vvo** [jsdoc2md/jsdoc-to-markdown#62]
Following #61, the error should be thrown as an uncaught exception by default.

This is the behavior of any EventEmitter: if no one is listening to the error event, throw a global error.

But it seems jsdoc-to-markdown is not following this, do you have any idea why?

**Comment by 75lb** [comment]
yes, it should throw - i will investigate.. 

are you 100% sure there is not a `process.on('uncaughtException', function(err) {})` in your codebase?

**Comment by vvo** [comment]
Yep, you can definitely try this in your own render.js example by adding what makes it fails in #61 (node v4)

**Comment by 75lb** [comment]
this was a difficult issue to isolate.. i tracked it down to the behaviour of node itself.. I'm [waiting for an answer](https://github.com/nodejs/node/issues/4533) from them..

**Comment by 75lb** [comment]
fixed and released upstream in jsdoc-api.. if you update jsdoc2md you should find unhandled 'error' events are thrown, again. 

thanks again for the report :+1:

**Comment by vvo** [comment]
Awesome!

**Comment by vvo** [comment]
Do you need to bump jsdoc-to-markdown?

**Comment by 75lb** [comment]
the module stack looks something like this: 
```
gulp-jsdoc-to-markdown & grunt-jsdoc-to-markdown
jsdoc-to-markdown
dmd
jsdoc-parse
jsdoc-api
jsdoc3 
```

the fix for this issue was in jsdoc-api.. Now, i could also bump the versions of each module above it in the stack but it's time consuming and would result in hundreds of patch releases in total, over time..

new installs will pick up the correct modules.. next time you `npm update` your local project you will also pick up the release :+1:

**Comment by vvo** [comment]
thx

**Comment by 75lb** [comment]
no problem, thanks for the reports!

**Comment by cramatt** [comment]
Still seeing this issue - has it been fixed and released?

**Comment by 75lb** [comment]
still seeing the issue in which version of jsdoc2md @cramatt ?

**Comment by cramatt** [comment]
I'm using`jsdoc-to-markdown` version `2.0.0`. I just locked in the version in `package.json`, deleted npm modules, and reinstalled. 

I don't seem be getting the _exact same issue_, but things are still not working as expected. Here are more details: 

My code: 

```
jsdoc2md.render({
  files: [
    'project/*.js',
  ]
}).then(output => {
  fs.writeFile('doc.md', output); // output is empty, no error is thrown.
});
```

- I have a few jsdoc files, 1 is knowingly formatted incorrectly. It's missing the `@name` doc.
- I run jsdoc-to-markdown. 
- `.then` is called but output is empty. 
- There does not seem to be a way to catch the error. Tried adding `.catch` and also a second argument with `(output, err)` and no luck.

**Comment by cramatt** [comment]
Im def able to catch errors, because the following code logs `err [TypeError: templateData.map is not a function]`.  

```
jsdoc2md.render({
  data: {
    files: [
      'project/*.js',
    ]
  }
}).then(output => {
  console.log('output', output);
}, err => {
  console.log('err', err);
});
```

What else could be going on? I'm following your example but I must be doing something wrong. 

Thanks!

**Comment by cramatt** [comment]
Also if I use this via npm script, for example: 

```
"scripts": {
    "docs": "jsdoc2md project/*.js > api.md"
 }
```

The file is empty and no errors are thrown. Not throwing errors here makes it incredibly difficult to debug which file has invalid docs when working with a large set of files.

**Comment by 75lb** [comment]
could you send some source or a link to a gist to help me reproduce this, please.. what you describe is not necessarily invalid behaviour.. if jsdoc2md does not find any documentation at module or global level the output will be empty - this is not an error, this is just a case of there being no docs.
