### ISSUE TITLE
@callback and @module?

### ISSUE THREAD

**Issue by srl295** [jsdoc2md/jsdoc-to-markdown#63]
The `@callback` use as in  http://usejsdoc.org/tags-callback.html works for the  standalone case ( `jsdoc2md foo.js > foo.md` ).

However, I'm trying to use a template to generate my `README.md`. Until I discovered the `{{>main}}` partial, it seemed like using a `@module` was the only way to get docs included ( module-less files throw an error with `{{>docs}}`, etc. Not sure if that's a bug or not. ) 

Anyways. Adding `@module foo` to the top of either the class or the global scoped `@callback` example from usejsdoc.org, results in the callback link not being a link anymore.

For now, I'm working around this by removing `@module` and using `{{>main}}` in my template.

### tl;dr how to reproduce

- save the two examples from http://usejsdoc.org/tags-callback.html into `class.js` and `global.js`
- run `jsdoc2md class.js global.js > good.md` 
- notice that the output in `good.md` has linkified callback references
- now, prepend the following to `class.js`
```
/**
 * @module foo
 */

```
- and prepend this to `global.js`
```
/**
 * @module bar
 */

```
- run `jsdoc2md class.js global.js > bad.md` 

Note the following:
- in foo (`class.js`), `requestCallback` is linkified from the call site, *but not present among documented items*
- in bar (`global.js`), `requestCallback` is present in documented items  *but not linkified at the call site*

**Comment by 75lb** [comment]
this is about name paths.. when you make a function a member of a module it's namepath changes to reflect its new parent.. so the callback name in the example is no longer valid as it doesn't indicate membership of the module.. I'm in the restaurant , will answer properly later

**Comment by 75lb** [comment]
sorry about the delay! `@callback` works fine, you just need to give it the correct [namepath](http://usejsdoc.org/about-namepaths.html).. So, if your callback is an inner member of a module it will need a namepath like `@callback module:example~callbackName`..

please let me know if you have any more issues.
