### ISSUE TITLE
Issues regarding es6 modules and export syntax

### ISSUE THREAD

**Issue by nathanmarks** [jsdoc2md/jsdoc-to-markdown#64]
Hey,

FYI, I fully understand that some issues are out of your control. But i'd love if you were able to point out where jsdoc causes the issues as you're far more familiar with it than I am.

**Problem 1 - named exports:** Cannot seem to get named exports to show properly.

Example code:
```js

/**
 * @module awesomeModule
 */

/**
 * Some awesome function
 * 
 * @returns {Promise} resolves to something even awesomer
 */
export function somethingAwesome () { }
```

This ends up being displayed in the output as a static member of the module. I tried playing around with more block tags but it still ends up being a member of the module. I went at it with https://github.com/jsdoc2md/jsdoc-parse and saw that the `isExported` flag is not set in the output.

**Problem 2 - default exports and other module members:** The solution I see for default exports with jsdoc often used involves using `@alias` or even `@module` in the comment block for the exported function/object/whatever. This seems to create problems though if I want to document a default export **and** named exports from one module. I can't seem to cleanly document the exports.

These 2 problems seem somewhat connected -- I can't document my exports in an obvious manner if I'm using named exports.

The only type of export I can document cleanly is a default export -- especially if I define the module on the block or alias the export to the module.

**Comment by nathanmarks** [comment]
@75lb here's an example where an exported function is not tagged as an export, simply represented as a static member of the module: https://github.com/nathanmarks/js-module-boilerplate#js-module-boilerplateinfo--string

Not to say that isn't correct -- but it'd be nice to be able to have it say "exported function" and be as obvious to the user as:

```js
import { info } from 'js-module-boilerplate';
```

It'd be great if there was a way to be able to have the exports clearly documented in the module index ( default + named). 

Is this possible with jsdoc as it currently stands? If not, what needs to be changed/added to jsdoc for this to be possible? If it's possible to do with `jsdoc-parse` currently, I'm also happy to contribute to make this happen.

**Comment by nathanmarks** [comment]
Here's the `jsdoc-parse` output from the basic example in that repo:

```
[
  {
    "id": "module:js-module-boilerplate",
    "longname": "module:js-module-boilerplate",
    "name": "js-module-boilerplate",
    "kind": "module",
    "description": "The core module of this library",
    "meta": {
      "lineno": 1,
      "filename": "index.js",
      "path": "/Users/PoweredbySearch/Development/repos/nathanmarks/js-module-boilerplate/lib"
    },
    "order": 0
  },
  {
    "id": "module:js-module-boilerplate.info",
    "longname": "module:js-module-boilerplate.info",
    "name": "info",
    "scope": "static",
    "kind": "function",
    "description": "Returns the module name",
    "memberof": "module:js-module-boilerplate",
    "returns": [
      {
        "type": {
          "names": [
            "string"
          ]
        },
        "description": "module name"
      }
    ],
    "meta": {
      "lineno": 12,
      "filename": "index.js",
      "path": "/Users/PoweredbySearch/Development/repos/nathanmarks/js-module-boilerplate/lib"
    },
    "order": 1
  }
]
```

**Comment by nathanmarks** [comment]
Here is the jsdoc explanation `-X`

```
    {
        "comment": "/**\n * Returns the module name\n *\n * @return {string} module name\n */",
        "meta": {
            "range": [
                150,
                211
            ],
            "filename": "index.js",
            "lineno": 12,
            "path": "/Users/PoweredbySearch/Development/repos/nathanmarks/js-module-boilerplate/lib",
            "code": {
                "id": "astnode100000001",
                "name": "exports.info",
                "type": "FunctionDeclaration",
                "paramnames": []
            }
        },
        "description": "Returns the module name",
        "returns": [
            {
                "type": {
                    "names": [
                        "string"
                    ]
                },
                "description": "module name"
            }
        ],
        "name": "info",
        "longname": "module:js-module-boilerplate.info",
        "kind": "function",
        "memberof": "module:js-module-boilerplate",
        "scope": "static"
    },
```

Looks like we get a reference to it being an export here: `"name": "exports.info",`

**Comment by nathanmarks** [comment]
Additionally, it looks default exports, while picked up, are presented in the resulting markdown as `module.exports() => ....` which is not the case exactly. In es5, to access the module "default" you'd actually have to do `require('module-name').default` as the babel output is like so:

```
exports.info = info;
exports.default = JsModule;
```

I wonder if we can responsibly macgyver a solution here to present these exports in an obvious manner.

**Comment by nathanmarks** [comment]
Some more related, strange behaviour is the handling of inner members in the same file as a default export.

For example, this is data from the `jsdoc` explanation:
```
        "scope": "inner",
        "memberof": "module:js-module-boilerplate"
```

However, after going through `jsdoc-parse`, we see this:
```
 "memberof": "module:js-module-boilerplate--module.exports",
```

Which is definitely not correct, it's not an inner constant of `module.exports` which is how it gets listed in the resulting markdown:

#### module.exports~jsModule : <code>Object</code>

**Comment by nathanmarks** [comment]
The last problem I mentioned, I've tracked down to line 43 of transform.js in jsdoc-parse.

```
    newIDs.forEach(function (newID) {
      update(json, { isExported: undefined, '!kind': 'module' }, function (identifier) {
        return updateIDReferences(identifier, newID)
      })
    })
```

Loops through anything else in that module and applies the new ID to the name, resulting in the behaviour i described in the last comment

**Comment by 75lb** [comment]
hi there.. 

this is how I document default exports.. inside [this folder](https://github.com/jsdoc2md/testbed/tree/master/build/global/es6-modules-default2) you can each stage of the process, from source code to dmd output (the final jsdoc2md output).. to get the correct docs we need an `@alias`, exactly as we do currently with CommonJS/AMD modules.

[this folder](https://github.com/jsdoc2md/testbed/tree/master/build/global/es6-modules-named) shows how i document named exports.. again, the output from this syntax is exactly the same as the output from CommonJS/AMD modules which use the `exports` or `module.exports` keywords.

**Comment by nathanmarks** [comment]
Hey @75lb,

One problem with that is the exports from an ES6 style codebase using babel 6 will export a default export using:

```js
exports.default = ....
```

Which means that anyone using ES5 to `require()` the module needs to do `require().default`. The documentation is unable to reflect this easily.

Also, in your examples, the "kind" says:

**Kind**: static constant of <code>[es6-modules-named](#module_es6-modules-named)</code>  

Which means 2 things:
1. No "eject" icon in the output
2. Doesn't say "exported constant of...." where it usually does

**Comment by nathanmarks** [comment]
Adding the following code to `setIsExportedFlag()` in `jsdoc-parse/lib/transform.js` results in it detecting these named exports properly:

```
  } else if (/^exports\./.test(identifier.meta.code.name) && identifier.kind !== 'module') {
    identifier.isExported = true
    delete identifier.scope
  }
```

![image](https://cloud.githubusercontent.com/assets/4420103/12539369/d3a2fd00-c2be-11e5-9495-faa9c24763eb.png)

**Comment by nathanmarks** [comment]
Is there an easy way to skip this part of the transform?

```js
newIDs.forEach(function (newID) {
...
```

Also, I noticed that exports as seen here: https://github.com/jsdoc2md/testbed/blob/master/build/global/es6-modules-default/3-dmd.md

Don't include the module link in the "**Kind: Exported function" text -- would be nice for it to link to the module (much like any other members do if not exported)

**Comment by 75lb** [comment]
> the exports from an ES6 style codebase using babel 6

compiled Typescript, Babel, Coffeescript etc. is definitely beyond my control.. and jsdoc3 control.. not sure how to fix that.. not sure whether i should "teach" jsdoc-parse to detect the peculiarities of each compiler.. normally we'd address a problem like this with a separate module downstream of jsdoc-parse.. 

the `Kind: static constant of es6-modules-named` text is correct.. this is exactly how the equivalent to named exports in CommonJS (properties of the `exports` object) are documented..

**Comment by 75lb** [comment]
> Don't include the module link in the "Kind: Exported function" text -- would be nice for it to link to the module

it works this way for [CommonJS exported functions](https://github.com/jsdoc2md/testbed/blob/master/build/commonjs/function-alias/3-dmd.md) too.. i didn't think the link was necessary in this case but i'll bare that in mind for jsdoc2md version 2 (in progress).. in v2 it will be much easier to make your own personalisations.

**Comment by 75lb** [comment]
you can skip that part of the transformation in your own fork, for now..  (obviously, that step of the transformation is required by all other use cases)

**Comment by nathanmarks** [comment]
@75lb 

I understand about the default export (just looked at the output from jsdoc -X, it shoves it right into `module.exports` without mentioning the fact that it actually compiles to `exports.default` (essentially a property of the exports object for CommonJS).

Thanks for the clarification.

I'm looking at the default behaviour now -- and I see that `jsdoc` itself is responsible for the biggest confusion here -- the fact that ES6 "default" exports are represented incorrectly:

![image](https://cloud.githubusercontent.com/assets/4420103/12539495/eceb21b8-c2c1-11e5-9764-3181cd6fb8a0.png)


Whereas, this is the transpiled es5 code:

```
exports.info = info;
exports.default = JsModule;
```

I imagine that with this sort of output, my documentation ideally be showing both "default" and "info" as **static** functions of `module.exports`. `module.exports()` is an object rather than a function. I'm assuming this is something I should look into with the `jsdoc` library itself. 

I'm going to set up my own fork of `jsdoc-parse` for now to apply some customizations, but I'd love to see v2 have an opt-in/opt-out transform system with plugin support.

**Comment by nathanmarks** [comment]
Here's how the current documentation output makes me envisage the actual code and how to access the different parts:

```
export default function JsModule () {
  
  const jsModule = {};

  return jsModule;
}

JsModule.info = function info () {
  return 'Hello World';
};
```

When in actuality, it's quite a bit different than that. `info` is a named export and part of the `module.exports` object (as is 'default' if we're being technical). Whereas `jsModule` is an inner constant of the module itself, not the default export.

**Comment by 75lb** [comment]
are you running jsdoc2md against your ES6 source code or the Babel output? also, does jsdoc3 render acceptable docs from your source?

**Comment by nathanmarks** [comment]
@75lb es6, documenting the babel output doesn't even identify the functions as exports at all -- just "inner method".

**Comment by nathanmarks** [comment]
FWIW the jsdoc html output doesn't recognize the named exports at all, and even prints out invalid es5 code:

```
(require("js-module-boilerplate"))()
```

Which would not work without the babel interop function for default exports. There's related info in this thread here:
https://github.com/Microsoft/TypeScript/issues/2719

**Comment by nathanmarks** [comment]
Correction to my prev comment -- I suppose that `jsdoc` does document them "correctly" (below the inner/"private" object as a static method). Seems strange that exported functions are output with little importance attached to them (below the inner constant which you can't even directly access)

**Comment by nathanmarks** [comment]
@75lb I'm was about to write an issue on the jsdoc repo but would appreciate your input on the issue

If we're documenting with "es6 module" (not *really* a thing since there is no native support yet) users in mind, documenting a default export as `module.exports()` rather than `module.exports.default()` is correct as that is the expected es6 module behaviour.

However, it seems that the jsdoc output is geared towards creating es5 documentation, hence things like `require()` being used in the default documentation output. In this situation `module.exports()` is actually incorrect when transpiling **unless** the user is using a plugin such as https://www.npmjs.com/package/babel-plugin-add-module-exports.  or even babel 5 or another transpiler to transpile their code (babel 5 exported defaults differently, but in a way that broke es6 semantics).

Given that different transpiler configurations can lead to different behaviour -- it seems like this needs to be an option the user can put in the `conf.json` for jsdoc under an es6 section or something (a boolean perhaps to set whether it should interpret es6 imports as having commonjs default export interop functionality).

Here's where the naive assumption is made in the `jsdoc` library:
![image](https://cloud.githubusercontent.com/assets/4420103/12539940/a628091c-c2cb-11e5-892b-44c780c08be8.png)

(/lib/jsdoc/src/astnode.js)

**Comment by nathanmarks** [comment]
I think I can write a plugin for jsdoc that solves this issue, I'll reply here again if I get it working

**Comment by PierreLeBrun22** [comment]
Did you manage to solve the problem @nathanmarks ?
