### ISSUE TITLE
Easy re-organization of module index possible? Complex name selectors?

### ISSUE THREAD

**Issue by nathanmarks** [jsdoc2md/jsdoc-to-markdown#65]
Let's say I have the following modules in my app:

```
cache
router
server
queues/reportQueue
queues/queueHelpers
```

`jsdoc-to-markdown` will output the module index ordered alphabetically (as expected):

```
cache
queues/reportQueue
queues/queueHelpers
router
server
```

For the readability of the module index, it would be great to be able to easily sort the module list so nested modules are not mixed in with the top level as they are now. With everything mixed, it gets pretty unwieldily at a certain # of modules.

I can currently achieve this by manually creating an index template and selecting each module by name -- however this gets very tedious.

Is there a way to implement a way to select module names with a `startsWith` or regex parameter? This would make it much easier to create an organized, easy to read index.

**Comment by 75lb** [comment]
yes, you can filter by regexp.. it's not documented, sorry about that.. the helper you want is this
```hbs
{{#modules _name="<regular expression>"~}}
...
{{/modules}}
```

the `_name` attribute signifies you want to filter on the `name` property (from the input jsdoc-parse data).. the underscore means *filter by regexp*.. if you specified `name` instead of `_name` it would filter by exact value. 

for example, to print a list of names of modules beginning with "s":
```hbs
{{#modules _name="^s"~}}
{{name}}
{{/modules}}
```

is there a more specific example i can help with?

**Comment by 75lb** [comment]
[this partial](https://github.com/jsdoc2md/dmd/blob/master/partials/main-index/module-index/module-index-dl.hbs) generates the module index you see in the default output.. you could copy/paste this into a custom partial, or your README template and simply replace the `{{#modules~}}` line at the top with `{{#modules _name="^s" ~}}` or similar.

**Comment by nathanmarks** [comment]
@75lb Amazing! This looks great. Just what I was looking for.

Can I suggest adding this to the examples? I tried checking out https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/templating/selector%20helpers/module before asking here.

**Comment by 75lb** [comment]
[done](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/templating/selector%20helpers/module), thanks again.. let me know if there's anything else..
