### ISSUE TITLE
Default params of array: end bracket missing.

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/jsdoc-to-markdown#66]
If the default value is an array, say `[1,10,20]`, the output is `[1,10,20`

**Comment by 75lb** [comment]
this issue is with the main jsdoc2md? Or the bitbucket plugin?

**Comment by ambischof** [comment]
I tried it with both, and they had the same result, so I figured it was with jsdoc2md.

**Comment by 75lb** [comment]
interesting.. can you send me a snippet of source code i can use to reproduce please.

**Comment by ambischof** [comment]
```
...
		 * @param {number} options.startPage=1 - what page to start on
		 * @param {number[]} options.pageSizeOptions=[1,10,20] - available page sizes
		 * @param {boolean} options.showPageNumbers=true - whether to show the current page number and total page count
...
```

**Comment by 75lb** [comment]
your syntax is wrong.. param values with default values must be contained in square brackets, see [docs](http://usejsdoc.org/tags-param.html)

it should be
```
         * @param {number} [options.startPage=1] - what page to start on
         * @param {number[]} [options.pageSizeOptions=[1,10,20]] - available page sizes
         * @param {boolean} [options.showPageNumbers=true] - whether to show the current page number and total page count
```

**Comment by ambischof** [comment]
While it doesn't explicitly say all params with default values have to be optional, you might be right about that. Thanks.

**Comment by 75lb** [comment]
yeah.. you state a param is optional by wrapping it in square brackets.. additionally, you can give an optional a default value.
