### ISSUE TITLE
Outputs blank for single JS file

### ISSUE THREAD

**Issue by hgupta9** [jsdoc2md/jsdoc-to-markdown#67]
I'm a first time user. running jsdoc2md on a [single js file](https://github.com/josdejong/mathjs/blob/master/lib/type/matrix/DenseMatrix.js) on Win 7 and it outputs a blank 0kb file. However, if i use -j to print the JSON, then it outputs ~20 functions into a neat JSON file. The markdown refuses to generate. What gives?

This is the command I'm using (I've opened a command prompt on Win 7 at the correct dir)

    jsdoc2md SparseMatrix.js > api.md

This is how I installed jsdoc2md:

    npm install -g jsdoc-to-markdown

Which produced this output:

> jsdoc-to-markdown@1.3.3 C:\Users\MY_USER_NAME\AppData\Roaming\npm\node_modules\jsdoc
> -to-markdown
> ├── console-dope@0.3.6
> ├── home-path@1.0.1
> ├── stream-connect@1.0.2 (array-back@1.0.2)
> ├── object-tools@2.0.5 (object-get@2.0.0, typical@2.4.2, test-value@1.0.1, colle
> ct-json@1.0.7, array-tools@2.0.2)
> ├── dmd@1.3.5 (handlebars-json@1.0.0, handlebars-regexp@1.0.0, string-tools@1.0.
> 0, common-sequence@1.0.2, ansi-escape-sequences@2.2.2, handlebars-string@2.0.1,
> handlebars-array@0.2.0, handlebars-comparison@2.0.0, array-tools@2.0.2, file-set
> @0.2.8, ddata@0.1.23, stream-handlebars@0.1.6)
> ├── config-master@2.0.1 (walk-back@1.1.0, feature-detect-es6@1.2.0, babel-polyfi
> ll@6.5.0)
> ├── command-line-args@2.1.4 (typical@2.4.2, array-back@1.0.2, feature-detect-es6
> @1.2.0, find-replace@1.0.1, ansi-escape-sequences@2.2.2, command-line-usage@2.0.
> 2, core-js@2.1.0)
> └── jsdoc-parse@1.2.7 (test-value@1.0.1, command-line-tool@0.1.0, collect-json@1
> .0.7, ansi-escape-sequences@2.2.2, feature-detect-es6@1.2.0, array-tools@2.0.2,
> file-set@0.2.8, jsdoc-api@1.0.5, core-js@2.1.0)

**Comment by 75lb** [comment]
this file doesn't parse.. just run `jsdoc2md SparseMatrix.js` and you'll see the errors.. if you're not sure whether you have valid jsdoc, try running it through jsdoc too.. i.e. `jsdoc SparseMatrix.js`.. jsdoc2md depends on valid jsdoc syntax to work.

**Comment by hgupta9** [comment]
But if the file doesn't parse correctly, then how does the JSON generate just fine?!
