### ISSUE TITLE
Loading handlebars helper fails

### ISSUE THREAD

**Issue by AndyOGo** [jsdoc2md/jsdoc-to-markdown#69]
I run the following command:
````shell
jsdoc2md --helper "handlebars-helper-rawinclude" --template README.hbs "{./,lib/}*.js" --verbose > README.md
````
I have installed this helper for rawincludes [https://github.com/ain/handlebars-helper-rawinclude](https://github.com/ain/handlebars-helper-rawinclude)

If want to use this helper with:
````handlebars
{{rawinclude 'LICENSE'}}
````

I get this error:

> Error: Missing helper: "rawinclude"
>     at Array.<anonymous> (/Users/andy/npm/lib/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/base.js:86:13)
>     at Object.eval (eval at createFunctionContext (/Users/andy/npm/lib/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:8:108)
>     at ret (/Users/andy/npm/lib/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
>     at ret (/Users/andy/npm/lib/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
>     at CompileStream._flush (/Users/andy/npm/lib/node_modules/jsdoc-to-markdown/node_modules/dmd/node_modules/stream-handlebars/lib/stream-handlebars.js:89:69)
>     at CompileStream.<anonymous> (_stream_transform.js:118:12)
>     at CompileStream.g (events.js:260:16)
>     at emitNone (events.js:67:13)
>     at CompileStream.emit (events.js:166:7)
>     at prefinish (_stream_writable.js:458:12)

**Comment by 75lb** [comment]
sorry, it's probably not documented very well, but the `--helper` option takes one or more file paths to modules exporting helpers.. so, something like:

```
$ jsdoc2md --helper path/to/raw-include.js 
```

**Comment by 75lb** [comment]
it's designed that way as helper overrides are typically defined locally, per project.. but it would be better if it accepted either a file path *or* module name.. it does work that way in jsdoc2md version 2 (50% done)

**Comment by AndyOGo** [comment]
Ah I see, thanks for your quick answer.
Got it to work with an explicit path:)

**Comment by 75lb** [comment]
That's good
