### ISSUE TITLE
Kramdown specific: newlines before markdown headers

### ISSUE THREAD

**Issue by cjsauer** [jsdoc2md/jsdoc-to-markdown#72]
I'm currently trying to use this tool to generate a markdown file that will sit inside of a Jekyll site hosted using Github Pages. Jekyll uses the Kramdown markdown parser. My issue is that my header tags are not rendering correctly, as you can see [here](http://cjsauer.github.io/genetic-sandbox/docs/). The reason being that Kramdown [requires headers to be preceded by newlines](http://kramdown.gettalong.org/syntax.html#atx-style), but the output of jsdoc2md does not do this. Is there a way to generate headers that are atx-style compliant?

**Comment by 75lb** [comment]
Hi, quick win - if you look at the dmd project page there are instructions
on how to override templates. Or you can wait and i will fix this tonight
as it should be the default behaviour

**Comment by 75lb** [comment]
fixed and released in dmd 1.3.11.. please update your tool/plugin to pick up.. thanks for the report :+1:

**Comment by cjsauer** [comment]
Fix confirmed! :+1:

**Comment by cjsauer** [comment]
It looks like this bug actually appears in more than one place. For example, the "Example" header above an example code block also requires a new line. Here's my best attempt at a visual:

<**Example**>
< ----- THERE SHOULD BE A NEWLINE HERE ----- >
\`\`\`js
class Circle extends Shape {
}
\`\`\`

**Comment by 75lb** [comment]
for now, could you test a fix for this using a [plugin](https://github.com/jsdoc2md/dmd#customising).. obviously, these are Kramdown specific issues (jsdoc2md outputs valid GFM).. 

duplicate [this partial file](https://github.com/jsdoc2md/dmd/blob/master/partials/all-docs/docs/body/examples.hbs) locally.. add your [line break](https://daringfireball.net/projects/markdown/syntax#p) where you think it should go, then pass a path to the file
```
$ jsdoc2md --partial overrides/examples.hbs
```
It's possible you will need to add your linebreak within the `@example` tag itself. 

once we know all the Kramdown fixes i will integrate them..

**Comment by cjsauer** [comment]
Thanks for the info. I just published a little shim plugin called [dmd-kramdown-plugin](https://www.npmjs.com/package/dmd-kramdown-plugin). I'll keep adding fixes to partials as I find them. For now though this is working.

**Comment by 75lb** [comment]
ok, good.. if i get more Kramdown users i'll point them to your plugin, or look into absorbing it.. :+1:
