### ISSUE TITLE
List of Handlebars template tags

### ISSUE THREAD

**Issue by cjsauer** [jsdoc2md/jsdoc-to-markdown#74]
Do you happen to have a full list of handlebars template tags that are available for use? I've got a sense for what is available from reading examples, but a full list of every tag available in a template would be very helpful.

**Comment by cjsauer** [comment]
I believe I may have found them: https://github.com/jsdoc2md/dmd/tree/master/partials

I hand't realized that the markdown generation was actually a separate project!

**Comment by 75lb** [comment]
well, beside the [selector helpers](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/templating/selector%20helpers) the best place to look is in the [dmd partials](https://github.com/jsdoc2md/dmd/tree/master/partials).. the entry-point partial is `main.hbs`, everything else branches out from there. 

regarding helpers, they are a little messy atm.. but the main ones loaded are from [dmd](https://github.com/jsdoc2md/dmd/blob/master/helpers/helpers.js) and [ddata](https://github.com/jsdoc2md/ddata/blob/master/lib/ddata.js).

i'm working on jsdoc2md version 2 as we speak and it will be much easier to follow.

what do you want to achieve? probably quicker for me to help you..

**Comment by 75lb** [comment]
yes, the markdown generation is a separate project.. there is also a separate project for html doc generation..

**Comment by cjsauer** [comment]
Good to know. My project is still very young, I'm just getting a feel for what is possible. The three project repositories combined is now the full picture. 

Also :+1: for jsdoc2md V2!
