### ISSUE TITLE
Is there a way to specify initial header level?

### ISSUE THREAD

**Issue by alexindigo** [jsdoc2md/jsdoc-to-markdown#75]
I'd like to be able to have my top level class to be rendered as level 3 header (`###`),
to fit better under second level sub-header "API Reference", since I have other blocks in my readme file.

Thank you.

**Comment by alexindigo** [comment]
Ok, `{{depthIncrement}}` will do. :)

**Comment by 75lb** [comment]
See the  --heading-depth option

**Comment by alexindigo** [comment]
I see. Thanks :)
