### ISSUE TITLE
Question on type links

### ISSUE THREAD

**Issue by cjsauer** [jsdoc2md/jsdoc-to-markdown#79]
I'm having a bit of trouble getting my @param, @return, etc tags to actually link to their respective types. Instead of a link, I get something that looks like `[HexGrid](#HexGrid)`. 

Should the linking work using es6 classes? I'm doing the following:

```js
    /**
     * A grid of tiles serving as the main stage of the simulation
     * @type {HexGrid}
     */
    this.grid = grid;
```

Yet the link to HexGrid still appears as above. Does it matter that HexGrid has not been imported in this file? 

Here is a link to some of the docs I've published for some more examples: http://cjsauer.github.io/genetic-sandbox/docs/#App

**Comment by 75lb** [comment]
you need to make sure you use the correct jsdoc namepath.. to get a list of all the namepaths found in your sourcecode, run jsdoc2md with `--stats`.. the namepaths listed in this output are the ones you can use.. for example:

```
$ jsdoc2md --stats lib/handbrake-js.js
{
  "identifiers": {
    "module": [
      "module:handbrake-js"
    ],
    "class": [],
    "constructor": [],
    "mixin": [],
    "member": [
      "module:handbrake-js.cliOptions"
    ],
    "namespace": [],
    "constant": [],
    "function": [
      "module:handbrake-js.spawn",
      "module:handbrake-js.exec"
    ],
    "event": [],
    "typedef": [],
    "external": []
  }
}
```

in this case, the namepath for the `spawn` method is `module:handbrake-js.spawn`.. if the one you want to use is missing, you need to need to add its source file to the list of jsdoc2md input files..

**Comment by cjsauer** [comment]
Here is a snippet from my --stats output:

```json
{
  "identifiers": {
    "module": [],
    "class": [
      "App",
      "Coord",
      "HexGrid",
      "Tile",
      "TileComponentIndex",
      "Hexagon",
      "IShape",
      "Point",
      "DefaultGridRenderSystem",
      "ISystem",
      "MultiStringHashMap"
    ],
  ...
}
```

I'm not seeing any namepaths other than the name of the class itself.

**Comment by 75lb** [comment]
yes, that output is correct.. so, in your case `{HexGrid}` is the correct namepath to use and `[HexGrid](#HexGrid)` is the correct, expected markdown output. 

the issue you have is the markdown-to-html renderer you are using has not converted `[HexGrid](#HexGrid)` to a html hyperlink.. not sure why.. can you show me the markdown output from jsdoc2md?

**Comment by cjsauer** [comment]
Here's a link to the docs.md file in my repo: https://raw.githubusercontent.com/cjsauer/genetic-sandbox/master/site/docs.md

**Comment by 75lb** [comment]
the issue is with markdown like this: 

```
<code>[HexGrid](#HexGrid)</code>
```

ok, it seems that your markdown rendered does not render markdown inside html tags.. here, we want HexGrid to be formatted as both code *and* a link.. it should look like this:

<code>[HexGrid](http://example.com)</code>

so, to format as both code and a link is possible on GitHub and most other renderers, but not yours.. could you play around and see if you can find a solution? I believe you made a plugin with all these little tweaks in..

**Comment by cjsauer** [comment]
Sure thing, I'll look into it. Can you give me a hint on which partials would be affected by this? It seems like it could be more than one.

**Comment by 75lb** [comment]
https://github.com/jsdoc2md/dmd/blob/master/partials/shared/value/link.hbs

**Comment by cjsauer** [comment]
Awesome. Looks as though I can use the `markdown="1" attribute on the `code` tag to get kramdown rendering the links properly. I'll give it a try this evening. Thanks for your help, as always!
