### ISSUE TITLE
latest output not being rendered correctly by sublime & atom

### ISSUE THREAD

**Issue by IjzerenHein** [jsdoc2md/jsdoc-to-markdown#8]
Hi, I just updated to the latest grunt-jsdoc-to-markdown and noticed that the current output of my files is no longer being rendered correctly by Sublime (preview in browser) and also in Atom.io (preview-plugin).

It seems to be something related to the additional tabs/spaces in the beginning of the line. If you need for info on how to reproduce let me know.

Cheers

**Comment by 75lb** [comment]
Hi @IjzerenHein, long time no speak.. here is how famous-map currently looks with the next version of the tool: https://github.com/75lb/famous-map/blob/master/docs.md

i'm still working on it, it's not ready for release, so your input would help at this point!

install it
`$ npm install -g jsdoc-to-markdown@next`

then try it for yourself: 
`$ jsdoc2md Map*.js > docs.md`

take a look at the new options:
`$ jsdoc2md --help`

let me know of any flaws etc.. 

@JohnMBarry , same goes for you ;)

**Comment by IjzerenHein** [comment]
Looks pretty nice Lloyd!
I'll have a closer look the next time I'll update the documentation.
cheers, Hein

**Comment by 75lb** [comment]
cool, let me know once you've updated - i'd like to use your docs as an example, if poss ;)

**Comment by IjzerenHein** [comment]
Yeah sure, no problem at all :)

I'll probably have time to look at it this weekend.
Cheers

**Comment by IjzerenHein** [comment]
Hi, I'm just testing against my famous-flex library. Looking nice!
I did notice one things. I some cases I have @params which can receive multiple data-types, so I write them out like this:
```
@param {Array|ViewSequence|Object} [options.dataSource] Array, ViewSequence or Object with key/value pairs.
```

The resulting markdown is:
```
| \[options.dataSource\] | <code>Array</code> \| <code>ViewSequence</code> \| <code>Object</code> | Array, ViewSequence or Object with key/value pairs. |
```

When I view the result in Atom (I use the Atom markdown previewer), it doesn't render this correctly. I'm not sure if this is because of the markdown itself or whether Atom just can't render the escaped `|` characters in tables.

![image](https://cloud.githubusercontent.com/assets/6184593/5856315/6ce2c804-a242-11e4-9b77-adc9957e2f06.png)

**Comment by 75lb** [comment]
tbh, the Atom markdown previewer is at fault as it is not rendering github-flavoured-markdown correctly.. never-the-less, if you grab the latest @next: 

```
$ npm install -g jsdoc-to-markdown@next
```

then pass the `--no-gfm` option, e.g.:
```
$ jsdoc2md your-code.js --no-gfm
```

...then tables will be rendered using html instead of gfm tables.. if you look at the raw version of [this page](https://github.com/75lb/jsdoc-to-markdown/blob/next/example/format-options/md/no-gfm.md) you can see the difference in output:

**Comment by IjzerenHein** [comment]
I see. Well if the output is correct, then I'd rather stick to the new version. Do you have a suggestion for a good tool (Mac/website) to preview the output (and test the links in the page as well)?
Cheers and thanks!

**Comment by IjzerenHein** [comment]
Conversation was continued through email.

> Peace wrote

```
Hein,

I can't release the source for the real app, but here's a private link to the live demo:
- *links have been removed*

Currently it's not explicitly setting the Z order. This causes the surfaces to sporadically disappear with scrolling.

With the work-around to explicitly set Z order, the scrolling is fixed but the transform/translate of the FlexScrollView causes surfaces to randomly disappear. The hamburger icon will do the transform/translate.

Let me know if you want me to set the Z order, and if you want additional surfaces added.

Regards,
Peace
```

**Comment by IjzerenHein** [comment]
> Hein wrote

Ok thanks.
Can you also share a version using the Stock famo.us ScrollView (using 100 ListingView items) and an other version which uses the z-translations on different URL's so I can compare those?

**Comment by IjzerenHein** [comment]
> Peace wrote

Ok here they are --

FlexScrollView, no Z order adjustments:
*links have been removed*

FlexScrollView with Z order adjustments:
*links have been removed*

Stock ScrollView 100+ surfaces:
*links have been removed*

Note that the middle box ("Specials tonight") has a red border. With 100 of them stacked up and offset, it may look like a solid red box to the left. Zoom in and you'll see the individual borders.

**Comment by IjzerenHein** [comment]
> Hein wrote

Hi Peace,
Awesome!

Regarding the 100+ surfaces demo. What I meant was, can you add 100+ list-items to the scrollview? Not more surfaces to a single list-view item. 
What I'm trying to show/debug is that the stock famo.us scrollView will also show the DOM ordering issues once you give it more list-items to work with. This is because it has a different threshold for when it starts adding/removing items from the DOM, but once it starts doing so, it will show the same issues as you see with the FlexScrollView.

**Comment by IjzerenHein** [comment]
> Hein wrote

Oh, and can we please continue this conversation on github. Just remove the links and mention that you send me the links. It is important that this information is on github so that other people can view the discussion and learn from it, or I can refer to the discussion directly when a similar question comes up.

**Comment by IjzerenHein** [comment]
> Peace wrote

I updated the wwwScrollView demo as you suggested (100 list items instead of 100 surfaces per item lol).  You're right the stock ScrollView does eventually miss rendering surfaces.

I'll reply further on the GH thread.

**Comment by IjzerenHein** [comment]
> Hein wrote

Yes that's what I thought would happen. The FlexScrollView has different a threshold setting for when items are added/removed from the DOM, it will typically remove all elements from the DOM that are not in the view. I have found that this performs the best on all devices. The stock famo.us scrollview will keep always keep about 10+ list-items in the DOM.
You can also instruct the FlexScrollView to always keep all list-items in the DOM, which can be beneficial to performance when you render only a limited set of list-items. To do this, use:
var scrollView = new FlexScrollView({
  layoutAll: true
});

**Comment by IjzerenHein** [comment]
> Peace wrote

The layoutAll option works like a charm!  You might want to add that comment to the thread for other people's benefit too.

Is it bad to compose items with multiple surfaces?  I first tried a single surface containing markup to place the child elements, but it was such a hack merging a string of markup with variables inserted. Famo.us really could benefit from something like React's JSX.

**Comment by IjzerenHein** [comment]
No I don't want to give the recommendation to use that option.

The real cause of the problem is that you cannot control the order of the items in the DOM using famo.us (if you think this is a bug, then please report it to famo.us). What you need to do is fix your code and add z-translations to those surfaces that you want to be displayed in front. As your app evolves you will very likely get multiple views and you will start using a RenderController to show/hide the views. When you do that, it is very likely that you will get into the same mess and the ordering is different after using 'renderController.show', so using `layoutAll` wont help you there.
Have you taken the famo.us University? I think it should mention this behavior more clearly as lots of people who start using famo.us run into it (I know I did back then).

**Comment by IjzerenHein** [comment]
Oh as for your second question.

No, it's no problem to compose items with multiple surfaces, in many cases you will have to do this, and it is the only way to handle different click events on single list-item.
In those cases where I don't need to handle separate click events for the list-item, I often do create a single surface and pass the child-divs as content to the surface. I used to concat those strings in JS but it gets real messy as you may have noticed.
I now mostly use handlebars templates for that. Please have a look at the famous-flex-chat sourcecode, it uses handlebars to compile an HTML template and set the content for a surface:
https://github.com/IjzerenHein/famous-flex-chat

**Comment by IjzerenHein** [comment]
Oops, I just put this famous-flex conversation in the completely wrong thread... auch
sorry dude, cleaning it up as I type this, sowwy

**Comment by 75lb** [comment]
yes, the output is correct [github-flavoured-markdown](https://help.github.com/articles/github-flavored-markdown/) (`\|` means "this is a literal pipe character, not a table column delimiter").. the `--no-gfm` option avoids using github-specific syntax.. 

Well, i use [Mou](http://25.io/mou/) as it handles most gfm (except 'fenced code blocks') well.. i tried three of the top online markdown editors and none handle `\|` either (like Atom).. so best to preview your stuff in Mou, Github or use `--no-gfm`.. 

i will take a look at the famous-flex jsdoc2md output too, curious :)

**Comment by IjzerenHein** [comment]
Hi, I've just updated the docs of my famous-flex lib to the latest version of jsdoc2md, looking good :+1: :)

**Comment by 75lb** [comment]
great, pleased to hear it! I just had a flick through your docs (great library, btw) - looking good.. and there is still room for improvement - i'll show you later.. hopefully, famous-flex can become an example on the jsdoc2md readme of how a well-documented module *should* look :+1:

**Comment by IjzerenHein** [comment]
Yeah sure, just refer to it, no problem. :+1: :)
