### ISSUE TITLE
Unable to load plugins

### ISSUE THREAD

**Issue by vasyas** [jsdoc2md/jsdoc-to-markdown#82]
Using jsdoc-parse@1.2.7

My jsdoc.conf.js:
```
{
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "extensions": ["js", "es6", "jsx"],
    "presets": ["es2015", "stage-1", "react"],
    "plugins": ["transform-flow-strip-types", "babel-plugin-transform-decorators-legacy"]
  }
}
```

When running
```
jsdoc-parse -f src/index.js --conf jsdoc.conf.json
```
got error message
``` 
JSDOC_ERROR: ERROR: Unable to find the plugin "node_modules/jsdoc-babel"
```

jsdoc@3.4.0 works ok.

The same error with other jsdoc plugins (tested jsdoc-strip-async-await), so I beleive it's plugin-unrelated.

**Comment by 75lb** [comment]
does it work if you use an absolute path to your plugin? e.g. 

```
"plugins": ["/Users/me/somewhere/node_modules/jsdoc-babel"]
```

**Comment by vasyas** [comment]
No.
And absolute version works ok with jsdoc.

**Comment by 75lb** [comment]
i've traced this to a regression in jsdoc3, introduced by [this commit](https://github.com/jsdoc3/jsdoc/commit/6be9dac616549ce226e4c0064876c7cb3b64fe25).. jsdoc2md does not use jsdoc3@3.4.0, it uses [a fork](https://github.com/jsdoc2md/jsdoc) which tracks the `master` branch of jsdoc3.

This is fixed and released in v3.5.6 of [jsdoc-75lb](https://github.com/jsdoc2md/jsdoc).. please reinstall jsdoc2md and try again.

**Comment by 75lb** [comment]
if you still have problems, please re-open.

**Comment by vasyas** [comment]
Thanks, it has fixed my issue.
