### ISSUE TITLE
ES6 syntax

### ISSUE THREAD

**Issue by stoffern** [jsdoc2md/jsdoc-to-markdown#86]
it fails to parse await, async ++ words (ES6).
Is there a way to handle this?

**Comment by 75lb** [comment]
would using [jsdoc-babel](https://github.com/ctumolosus/jsdoc-babel) with the `--configure` option help? 

* * *
*[Try the jsdoc2md v2 pre-release](https://github.com/jsdoc2md/jsdoc-to-markdown/releases)*

**Comment by bgordon01** [comment]
Hi there

Just came across the same issue. The es2016 keywords async / await still not working. Tried the v2 pre-release and it's still failing. Get the following error:

Unexpected token function
at Explain.verifyOutput (/Users/brent.gordon/.nvm/versions/node/v6.3.1/lib/node_modules/jsdoc-to-markdown/node_modules/jsdoc-api/lib/jsdoc-command.js:108:19)
    at ChildProcess.handle.on.err (/Users/brent.gordon/.nvm/versions/node/v6.3.1/lib/node_modules/jsdoc-to-markdown/node_modules/jsdoc-api/lib/explain.js:48:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

Code:

```js
async function loadData(){
    try {
        await login();
    } catch(err){
        console.log(err);
    }
}
```

Is this issue fixed yet, or am I doing something wrong?

**Comment by 75lb** [comment]
@bgordon01 did you try using [jsdoc-babel](https://github.com/ctumolosus/jsdoc-babel)?

**Comment by bgordon01** [comment]
@75lb I did and I still get the same error

**Comment by 75lb** [comment]
i finally got around to trying this - it works fine.. the error you're seeing (`Unexpected token function`) is because you don't have the necessary babel plugin (transform-async-to-generator) installed..

To get async/wait code working, install these modules:
```
$ npm i jsdoc-babel babel-preset-es2015 babel-plugin-transform-async-to-generator
```

..create this jsdoc config file
```
{
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "presets": [ "es2015" ],
    "plugins": [ "transform-async-to-generator" ]
  }
}
```

and run jsdoc2md like this: (use `--conf` if still on v1.3.7)
```
$ jsdoc2md --configure the-config-above.json lib/your-code.js
```

* * *
*[Try the jsdoc2md v2 pre-release](https://github.com/jsdoc2md/jsdoc-to-markdown/releases)*

**Comment by bgordon01** [comment]
Awesome, this works perfectly now 👍  thanks for your help Lloyd
