### ISSUE TITLE
Link points the wrong anchor

### ISSUE THREAD

**Issue by jeffrose** [jsdoc2md/jsdoc-to-markdown#87]
I have a constructor which doubles as function.

````javascript
/**
 * Applies stuff
 * @function Stuff
 * @param {external:Object} obj
 * @example
 * let stuff = Object.create( null );
 * Stuff( stuff );
 */
/**
 * Constructs stuff
 * @class Stuff
 * @example
 * const stuff = new Stuff();
 */
function Stuff(){
    // ...
}
Stuff.prototype = Object.create( null );
Stuff.prototype.constructor = Stuff;
````

The document renders both entries.

> **Classes**
> Stuff
> Constructs stuff
>
> **Functions**
> Stuff(obj)
> Applies stuff.

However clicking on the Function entry takes you to the Class details because they both point to `#Stuff`. Ideally one should point to `#Stuff-class` and the other should point to `#Stuff-function`, or something similar.

**Comment by 75lb** [comment]
i can't solve your issue directly (jsdoc doesn't support documenting the same identifier twice) but does this work, as a workaround? 

```js
/**
 * Applies stuff
 * @function StuffFunc
 * @param {external:Object} obj
 * @example
 * let stuff = Object.create( null );
 * Stuff( stuff );
 */
StuffFunc = Stuff;

/**
 * Constructs stuff
 * @class Stuff
 * @example
 * const stuff = new Stuff();
 */
function Stuff(){
    // ...
}
Stuff.prototype = Object.create( null );
Stuff.prototype.constructor = Stuff;
```
