### ISSUE TITLE
v2.0.0-alpha.13 - no output when generating .md

### ISSUE THREAD

**Issue by chadxz** [jsdoc2md/jsdoc-to-markdown#89]
Using v2.0.0-alpha.13, I am getting no output when running the command `jsdoc2md -f src/Events.js` on the file https://github.com/chadxz/awry/blob/0be94a538ff13aca8f791147b662529612f70cda/src/Events.js

if i run the same command but with `--json` or `--jsdoc`, I get output. It's only when I try to generate the markdown that I get no output. I tried using `--verbose` but that flag doesn't seem to exist in v2

Not a blocker for me, as I was mostly just tinkering with this project. Just thought i'd report since it's still in alpha.

**Comment by 75lb** [comment]
hi, thanks for the report.. it's because there is nothing documented at the top level scope of the source (although identifiers deeper in the tree are documented).. generally, *all* modules must document the top-level else nothing will show up.. 

put a `@module` tag in there.. i.e. 

```
'use strict';
const Rx = require('rxjs/Rx');
const qs = require('querystring');
const ReconnectingWebSocket = require('./ReconnectingWebSocket');

/**
 * My module to do something. 
 * @module something
 * @typicalname ting
 */

module.exports = {
   ...
   ...
}
```

**Comment by chadxz** [comment]
Ah okay, thanks. Sorry for the noise

**Comment by 75lb** [comment]
please, don't be sorry - keep em coming, i appreciate the feedback!
