### ISSUE TITLE
module.exports declarations are not generated

### ISSUE THREAD

**Issue by ngryman** [jsdoc2md/jsdoc-to-markdown#91]
Hi!

This does not get generated:
```js
module.exports = function foo() { /* ... */ }
```

This does:
```js
function foo() { /* ... */ }
module.exports = foo
```

I was expecting the first to work properly. It's not a super blocker, but declaring/exporting is quite a trendy pattern in the nodejs community.

Thanks!

**Comment by 75lb** [comment]
i [reported this issue](https://github.com/jsdoc3/jsdoc/issues/679) ages ago, bro.. i'm afraid jsdoc3 does not correctly document code written in style 1 (above).. you need to write in style 2 for now (declare your function, document it, then export it).. 

let me know if you have any more issues!

**Comment by ngryman** [comment]
Alright! Sorry for the duplicate.
