### ISSUE TITLE
How can I obtain standard markdown output?

### ISSUE THREAD

**Issue by nomadster** [jsdoc2md/jsdoc-to-markdown#92]
I see that it outputs a very nice github flavoured markdown but unfortunatly I need standard markdown beacuse my target is not github.

How can I achieve this? There are some references on the documentation but this is not pointed out well.

Thanks for your help.

**Comment by 75lb** [comment]
hi, did you try the `—no-gfm` option? I will improve the documentation soon, sorry about that..

**Comment by nomadster** [comment]
Hi @75lb thanks for your reply :). How can I pass that option inside gulp?
I'm also using gulp-jsdoc-to-markdown because I have a large codebase to document and automating the process is essential and good :)

**Comment by 75lb** [comment]
in your gulp task, pass `'no-gfm': true` to jsdoc2md.. e.g. 

```
gulp.task('docs', function () {
  return gulp.src('lib/*.js')
    .pipe(gulpJsdoc2md({ 'no-gfm': true }))
    .on('error', function (err) {
      gutil.log(gutil.colors.red('jsdoc2md failed'), err.message)
    })
    .pipe(rename(function (path) {
      path.extname = '.md'
    }))
    .pipe(gulp.dest('api'))
})
```

**Comment by nomadster** [comment]
I've tried with the option you segguested but it still outputs a file with some html in it. Any other suggestion?

**Comment by 75lb** [comment]
a file with html in it might not be what you want but is still valid markdown.. the `--no-gfm` option removes Github-specific markdown, using only standard markdown (which may include html).

My only other suggestion for now is to look at the [dmd-bitbucket plugin](https://github.com/jsdoc2md/dmd-bitbucket) or see the [dmd](https://github.com/jsdoc2md/dmd/) docs on how to modify the output.

**Comment by 75lb** [comment]
i closed the issue as it's not a bug.. but feel free to ask more questions here or on the gitter page

**Comment by nomadster** [comment]
Thanks for you help
