### ISSUE TITLE
Allow other input files extension

### ISSUE THREAD

**Issue by ngryman** [jsdoc2md/jsdoc-to-markdown#94]
Hey,

It seems that **jsdoc** enforces `.js` for input files.

```sh
# yup
$ jsdoc2md index.js

# nop
$ jsdoc2md index.cjs
JSDOC_ERROR: There are no input files to process.

# workaround
cat index.cjs | jsdoc2md
```

Do you think it's possible to add support for custom extensions? Or am I missing something?

Thanks!

**Comment by 75lb** [comment]
you need to [configure jsdoc](http://usejsdoc.org/about-configuring-jsdoc.html) then specify your config file path using `jsdoc2md --conf my-config.json` (or `--configure my-config.json` on v2)

**Comment by ngryman** [comment]
Thanks!
