### ISSUE TITLE
Creating one markdown file per file

### ISSUE THREAD

**Issue by AndyOGo** [jsdoc2md/jsdoc-to-markdown#95]
I would like to generate one `.md` file per input file, skipping the automatic concatenation.
Something like this should work:

```bash
jsdoc2md  --configure=.jsdocrc --out=dist/jsdocs/ js/**/*.js
```

In:
```
+-- js/
|   +-- lib/
|       +-- foo.js
|   +-- a.js
|   +-- b.js
```

Out:
```
+-- dist/
|   +-- jsdocs/
|       +-- lib/
|           +-- foo.md
|       +-- a.md
|       +-- b.md
```

**Comment by 75lb** [comment]
take a look at [jsdoc2md v2 prerelease](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/next), it has a more flexible [API](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/next/docs/API.md) you could script to achieve what you need.

**Comment by kulakowka** [comment]
@75lb Could you add this capability in cli utility?

**Comment by 75lb** [comment]
hi @kulakowka.. i don't plan to add this specific behaviour to the cli because it is not what the majority of users need, sorry.

**Comment by MitchellBurton** [comment]
I just want to say that this functionality in the cli is exactly what I need right now.

**Comment by 75lb** [comment]
well, there is an example script showing how to achieve this in jsdoc2md v1.. i will write a similar example for v2 ASAP. 

I'm still working on V2 - almost there, it's at preview stage atm.

**Comment by 75lb** [comment]
i wrote a tutorial and example script showing how to achieve this using jsdoc2md v2 (latest version required):
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class

**Comment by uGuinea** [comment]
I used this solution for the problem:

`return gulp.src(fileSource)
        .pipe(tap(function (file, t) {
            basename = file.relative.split('.js')[0];
            //console.log("File " + file.path + "  " + file.relative.split('.js')[0]);
            jsdoc2md.render({
                files: file.path
            }).then(output => fs.writeFile(outputPath + baseName + '.md', output));
        }));`

**Comment by 75lb** [comment]
the example script for how to create one file per class now lives on the wiki: 
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-create-one-output-file-per-class

**Comment by gillyspy** [comment]
i believe that @uGuinea  is doing the spirit of what was asked in the original question -- albeit with `gulp` and `gulp-tap` .

**Comment by user72356** [comment]
I'm not sure why @75lb thinks the majority of user isn't after a well-organized documentation that contains a simple menu and 1 file per module. That's what all other API doc building tool does. Ah well. Now back looking for another package. Too bad this one actually works otherwise.
