### ISSUE TITLE
ES2016 arrow support

### ISSUE THREAD

**Issue by mkozjak** [jsdoc2md/jsdoc-to-markdown#96]
Arrows are not supported:
```
JSDOC_ERROR: ERROR: Unable to parse index.js: Line 67: Unexpected token =>
```

Steps to reproduce (according to https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-ES2016-features-like-async-&-await):
```
npm i -g jsdoc-to-markdown@^2.0.0-alpha
npm i jsdoc-babel babel-preset-es2015 babel-plugin-transform-async-to-generator

echo "{  
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "presets": [ "es2015" ],
    "plugins": [ "transform-async-to-generator" ]
  }
}" > .jsdoc

jsdoc2md --configure .jsdoc src/index.js // echoes nothing, even though 'index.js' is full of es7 code

jsdoc2md --config .jsdoc src/index.js 
{
  "files": [
    ".jsdoc",
    "src/index.js"
  ]
}
```

What am I doing wrong here?

**Comment by 75lb** [comment]
what version of node are you on?

**Comment by mkozjak** [comment]
v6.6.0

**Comment by mkozjak** [comment]
@75lb: btw, my source code is in Allman style!

**Comment by 75lb** [comment]
does [jsdoc](https://github.com/jsdoc3/jsdoc) work correctly with your sourcecode?  So, does this command produce the correct jsdoc output?
```
$ jsdoc --configure .jsdoc src/index.js
```

**Comment by 75lb** [comment]
it would be quicker and easier for me if you could send a failing test i could reproduce, like a gist or some failing code i could run.

**Comment by mkozjak** [comment]
```
jsdoc --configure .jsdoc src/index.js         
ERROR: Unable to find the plugin "node_modules/jsdoc-babel"
ERROR: Unable to parse /opt/dev/github.com/qaap/pharos/src/index.js: Line 67: Unexpected token =>```

Tried installing locally and globally.

```node_modules/jsdoc-babel``` definitely exists.

**Comment by 75lb** [comment]
could you send steps to reproduce this error please.. i can't help you or fix it if i can't reproduce it. 
```
JSDOC_ERROR: ERROR: Unable to parse index.js: Line 67: Unexpected token =>
```

**Comment by mkozjak** [comment]
Steps to reproduce are the same except the plugins bit, where I put 'lib/index'.

.jsdoc file:
```
{  
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "presets": [ "es2015" ],
    "plugins": [ "transform-async-to-generator" ]
  }
}
```

**Comment by 75lb** [comment]
sorry, i only just saw the edit you made to your comment above - i am testing on the code you linked to now - thanks

**Comment by 75lb** [comment]
Hi, i've tested this and everything works fine. The reason you are not getting any output is because there are no documented modules or globals in your code. [Read this](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-a-module).

**Comment by mkozjak** [comment]
Nice!

What about ```"plugins": ["node_modules/jsdoc-babel/lib/index"]```. Is that normal?

**Comment by 75lb** [comment]
it makes no difference, for me both these permutations work the same:

`"plugins": ["node_modules/jsdoc-babel/lib/index"]`
`"plugins": ["node_modules/jsdoc-babel"]`
