### ISSUE TITLE
Remove <code> from @require tags

### ISSUE THREAD

**Issue by denydias** [jsdoc2md/jsdoc-to-markdown#98]
Hi there!

I'm documenting `@requires` tags like this:

```
@requires module:myModule
```

But the parsed markdown is being printed like this:

```
**Requires**: <code>[myModule](#module_myModule)</code>
```

By looking at [default template](https://github.com/jsdoc2md/dmd/blob/master/partials/shared/value/defaultvalue.hbs), I can see that `<code>` tags comes from there, but I can't figure out a way on how to get rid of them.

Can someone provide some advice on how can I change my custom template to remove the enclosing `<code>` from `@requires` so the parsed markdown could read:

```
**Requires**: [myModule](#module_myModule)
```

This way the required modules are going to link to their section in the document, which is what I'm looking for.

Thanks in advance.

**Comment by 75lb** [comment]
hi! If you provide a valid namepath to `@requires` then it will automatically link to the appropriate docs. 

Your problem is that `module:myModule` is not a valid namepath.  Run this command to list the valid namepaths in your project: 

```
$ jsdoc2md --namepaths source-code.js
```

Take a look at [this wiki page](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin) for some info about creating custom partials.

**Comment by denydias** [comment]
Thanks a lot for the quick reply, @75lb! I'm going to look into it and let you know.

**Comment by denydias** [comment]
Quite interesting! These are my namepaths for a file:

```
jsdoc2md --namepaths scripts/d8ox-utils.js
{
  "module": [
    "module:d8ox-utils"
  ],
  "class": [],
  "constructor": [],
  "mixin": [],
  "member": [
    "mapURI",
    "queryState",
    "geoBaseURL",
    "cookieState",
    "initState",
    "oxOpt",
    "mapCurBase",
    "mapCurLayers",
    "breakpoint",
    "curBreakpoint",
    "superfish"
  ],
  "namespace": [],
  "constant": [],
  "function": [
    "debug",
    "debugTable",
    "breakpointDetect",
    "setCookie",
    "getCookie",
    "delCookie",
    "sfwr"
  ],
  "event": [],
  "typedef": [],
  "external": []
}
```

I'm referencing `module:d8ox-utils` on another file in the same directory. The command I'm using is:

```
jsdoc2md -t scripts/template.hbs -f scripts/*.js
```

And this is my gulp task:

```
gulp.task('jsdoc', function () {
  return jsdoc2md.render({
    files: [
      'scripts/d8ox-degmap.js',
      'scripts/d8ox-esri-leaflet-geocoder.js',
      'scripts/d8ox-inframap.js',
      'scripts/d8ox-utils.js'
    ],
    template: fs.readFileSync('scripts/d8ox-js.hbs', 'utf8'),
    configure: 'conf.json'
  })
  .then(output => fs.writeFile('../docs/d8ox-js.md', output));
})
```

In both cases, I get `@require` as `<code>`.  What I'm missing?

**Comment by denydias** [comment]
For the sake of completion, this is my `template.hbs`:

```
A header.

{{depthIncrement}}

## Index

{{#globals~}}
{{#if @first~}}{{>heading-indent}}Globals

<dl>
{{/if~}}
<dt>{{>sig-link-html}}</dt>
<dd>{{{md (inlineLinks '')}}}</dd>
{{#if @last~}}</dl>

{{/if~}}
{{/globals~}}

{{#modules~}}
{{#if @first~}}{{>heading-indent}}Modules

<dl>
{{/if~}}
<dt>{{>sig-link-html}}</dt>
<dd>{{{md (inlineLinks '')}}}</dd>
{{#if @last~}}</dl>

{{/if~}}
{{/modules~}}

## Globals

{{#globals}}
{{>header~}}
{{>body}}
{{>member-index~}}
{{>separator~}}
{{>members~}}
{{/globals}}

## Modules

{{#modules}}
{{>header~}}
{{>body}}
{{>member-index~}}
{{>separator~}}
{{>members~}}
{{/modules}}

* * *

A footer.
```

**Comment by 75lb** [comment]
`scripts/d8ox-utils.js` is not being passed into jsdoc2md by your gulp task, therefore jsdoc2md cannot find nor parse its data. Pass it in. Mark it with `@ignore` if you want to exclude it from docs.

**Comment by denydias** [comment]
LOL! How come? What is this setting telling jsdoc2md then?

```
files: [
  'scripts/d8ox-degmap.js',
  'scripts/d8ox-esri-leaflet-geocoder.js',
  'scripts/d8ox-inframap.js',
  'scripts/d8ox-utils.js'
]
```

I took this from here:

https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-gulp

**Comment by 75lb** [comment]
sorry, my fault - i read the issue too quickly. I'm out in the car, rushing around. Yes, you're passing in the file correctly. I sent a link earlier to a wiki page on how to create and pass in custom partials - did that help explain how to override the default partial?

[Here](https://github.com/jsdoc2md/testbed/blob/master/build/jsdoc/global/requires/3-dmd.md) is an example of the `@require` tag working correctly (formatted as code and with the hyperlinks). Do you not see this behaviour, does your hyperlink not render correctly?

**Comment by denydias** [comment]
No worries. It's good to see that amazing programmers are humans after all! :wink:

I understood the method of creating a plugin to replace a partial, but I haven't applied it yet. I rather prefer that jsdoc2md works as expected in my project than to add more code to something that should just work.

I know I'm doing something wrong, I just can'y figure out what and this is disappointing to me. Maybe I'm just too tired. I'll step away for a while and if I can't get it working during the week, I go for the partial or just leave it as is.

The interesting thing here is that jsdoc2md CLI produces the same results as the gulp task... At least my mistake is consistent. :smiley:

You may close this if you wish, @75lb. Thank you for the feedback.

**Comment by 75lb** [comment]
you don't need to create a whole plugin, only a custom partial.. it's a really quick job.. i will write a better tutorial later.. 

it would help me if i could reproduce your issue.. if your project (with the issue) is on github, please send me the link.. else i'll try to reproduce it tonight.

**Comment by denydias** [comment]
Sure! I figure that out! The point is there's tons of code from functional areas looking for some tenderness and a quickly approaching deadline...

Unfortunately not. It's on GitLab in a private project that I'm not authorized to disclose ATM. :(

I really thank you for your effort, @75lb. It's easy to see now why jsdoc2md is a success!

**Comment by denydias** [comment]
YAY!!!!!!!!!!!!!!! We're not doing nothing wrong!!!!!!!!!!!!!!

This [chrome extension](https://chrome.google.com/webstore/detail/markdown-reader/gpoigdifkoadgajcincpilkjmejcaanc?utm_source=chrome-app-launcher-info-dialog) is!!!!

I'm using it to preview my docs. It shows links enclosed in `<code>` as literal code and do not parse the markdown links. I've noted that by looking at the raw of your reference file, [3-dmd.md](https://github.com/jsdoc2md/testbed/blob/master/build/jsdoc/global/requires/3-dmd.md). The result are identical to mine. See:

![3-dmd](https://cloud.githubusercontent.com/assets/948202/19628068/7e38fd68-9934-11e6-860b-d8efe2b49d7f.png)

I'm very sorry for the noise. I'm glad this issue belongs to somewhere else!

**Comment by denydias** [comment]
Or maybe jsdoc2md should really avoid to enclose those links into `<code>` anyway. I'don't know how markdown parses over there behaves in that case. So we may have a situation here...

From a standard perspective, what comes inside `<code>` SHOULD be code, even links. We know now GFM ignores this and parses a link even inside `<code>`.

**Comment by 75lb** [comment]
glad to hear you found the cause of the issue.. the `<code>` formatting is required, i'm afraid because in regular markdown it is impossible to format a piece of text as both a link **and** code.

**Comment by denydias** [comment]
I see.

Well, in that case this another [chrome extension](https://chrome.google.com/webstore/detail/markdown-preview/jmchmkecamhbiokiopfpnfgbidieafmd/related) (Markdown Preview) plays nice with link, but messes with UTF-8 symbols tough.

Thank you a lot, @75lb! Have a very nice Sunday evening and a great week!

**Comment by 75lb** [comment]
i will test jsdoc2md with the Chrome extensions you mentioned.. thanks for the report, have a good week too 👍

**Comment by denydias** [comment]
Tried another one, [Markdown Preview Plus](https://chrome.google.com/webstore/detail/markdown-preview-plus/febilkbfcbhebfnokafefeacimjdckgl/related)... some hiccups with out-of-the-box settings, better after a tweak.

After install, go to extension's options and choose GitHub in Default CSS. Enable auto-reload if your gulp tasks also does that and you're all set. Links renders fine and there's no tofus.

**Comment by 75lb** [comment]
scripts/d8ox-utils.js is not being passed into jsdoc2md by your gulp task,
therefore jsdoc2md cannot find nor parse its data. Pass it in. Mark it with
@ignore if you want to exclude it from docs.
